import { expect, test, type Page } from '@playwright/test'
import { expectNoAxeViolations, expectNoOverflow, go } from './helpers'

// Staff 2FA against e2e/stub/twofactor.mjs (account tfa@example.test; valid TOTP is always 123456).
const EMAIL = 'tfa@example.test'
const PASSWORD = 'Tfa-Passw0rd!'
const API = `http://127.0.0.1:${process.env.E2E_API_PORT ?? 8791}/api/v1`
test.describe.configure({ mode: 'serial' })
test.use({ viewport: { width: 1280, height: 800 }, actionTimeout: 8000 })
test.setTimeout(40_000)

const reset = (request: import('@playwright/test').APIRequestContext, body: Record<string, unknown> = {}) => request.post(`${API}/__tfa_setup`, { data: body })
const axe = async (page: Page, label: string) => { await expectNoAxeViolations(page, label); await expectNoOverflow(page, label) }

async function password(page: Page, locale = 'en') {
  await go(page, `/${locale}/login`)
  await page.getByLabel(/^(Email|البريد الإلكتروني|E-mail)/).fill(EMAIL)
  await page.locator('input[type=password]').fill(PASSWORD)
  await page.locator('form button[type=submit]').click()
}
const cookieNames = async (page: Page) => (await page.context().cookies()).map(c => c.name)

test('staff without 2FA: admin shows the localized gate, setup shows QR locally, recovery codes appear once', async ({ page, request }) => {
  await reset(request)
  const external: string[] = []
  page.on('request', (r) => { const u = new URL(r.url()); if (!['127.0.0.1', 'localhost'].includes(u.hostname) && u.protocol.startsWith('http')) external.push(r.url()) })
  await password(page)
  await page.waitForURL(/\/en\/dashboard/)
  await go(page, '/en/admin')
  const gate = page.getByTestId('two-factor-gate')
  await expect(gate).toBeVisible()
  await axe(page, 'admin gate')
  await page.getByTestId('two-factor-gate-cta').click()
  await page.waitForURL(/\/en\/settings\/two-factor/)
  await expect(page.getByTestId('two-factor-required')).toContainText('Required for your role')
  await expect(page.getByTestId('two-factor-state')).toHaveText('Off')
  await axe(page, 'settings 2fa off')
  await page.getByTestId('two-factor-start').click()
  await expect(page.getByTestId('two-factor-qr')).toBeVisible()
  await page.getByText('Cannot scan the code?').click()
  await expect(page.getByTestId('two-factor-secret')).toHaveText('JBSW Y3DP EHPK 3PXP')
  await axe(page, 'settings 2fa setup')
  // wrong code first
  const code = page.getByLabel('6-digit code')
  await expect(code).toHaveAttribute('autocomplete', 'one-time-code')
  await expect(code).toHaveAttribute('inputmode', 'numeric')
  await code.fill('000000')
  await page.getByRole('button', { name: 'Confirm and turn on' }).click()
  await expect(page.getByText('That code is not correct.')).toBeVisible()
  await expect(code).toHaveAttribute('aria-invalid', 'true')
  await expect(code).toBeFocused()
  await code.fill('123 456')
  await page.getByRole('button', { name: 'Confirm and turn on' }).click()
  const codes = page.getByTestId('two-factor-codes')
  await expect(codes.getByRole('listitem')).toHaveCount(10)
  await expect(page.getByRole('heading', { name: 'Save your recovery codes' })).toBeFocused()
  await expect(page.getByTestId('two-factor-codes-done')).toBeDisabled()
  await axe(page, 'recovery codes')
  await page.getByLabel('I have saved these codes in a safe place').check()
  await page.getByTestId('two-factor-codes-done').click()
  await expect(page.getByText('abcd0-efgh0')).toHaveCount(0)
  await expect(page.getByTestId('two-factor-state')).toHaveText('On')
  await expect(page.getByTestId('two-factor-required')).toContainText('it is active')
  await axe(page, 'settings 2fa on')
  // the gate lifts as soon as setup is confirmed
  await go(page, '/en/admin')
  await expect(page.getByTestId('two-factor-gate')).toHaveCount(0)
  expect(external, 'the secret/QR must never go to a third party').toEqual([])
})

test('login with 2FA: no session after the password, code step, wrong then right code; token stays out of JS', async ({ page, request }) => {
  await reset(request, { enabled: true })
  await password(page)
  const step = page.getByTestId('two-factor-step')
  await expect(step).toBeVisible()
  await expect(page.getByLabel('6-digit code')).toBeFocused()
  expect(await cookieNames(page)).not.toContain('expa_token')
  const challenge = (await page.context().cookies()).find(c => c.name === 'expa_2fa')
  expect(challenge?.httpOnly).toBe(true)
  expect(await page.evaluate(() => document.cookie + JSON.stringify(Object.assign({}, localStorage, sessionStorage)))).not.toContain('tfc_')
  await expect(page.getByTestId('two-factor-countdown')).toContainText('expires in')
  await axe(page, 'login code step')
  const code = page.getByLabel('6-digit code')
  await code.fill('111111')
  await page.getByRole('button', { name: 'Verify and sign in' }).click()
  await expect(page.getByText('That code is not correct.')).toBeVisible()
  await expect(code).toBeFocused()
  await code.fill('123456')
  await page.getByRole('button', { name: 'Verify and sign in' }).click()
  await page.waitForURL(/\/en\/dashboard/)
  const names = await cookieNames(page)
  expect(names).toContain('expa_token')
  expect(names).not.toContain('expa_2fa')
  expect((await page.context().cookies()).find(c => c.name === 'expa_token')?.httpOnly).toBe(true)
})

test('recovery code works once and the stub sees only the cookie challenge', async ({ page, request }) => {
  await reset(request, { enabled: true })
  await password(page)
  await page.getByRole('button', { name: 'Use a recovery code instead' }).click()
  const rc = page.getByLabel('Recovery code')
  await expect(rc).toBeFocused()
  await axe(page, 'login recovery step')
  await rc.fill('ABCD0-EFGH0')
  await page.getByRole('button', { name: 'Verify and sign in' }).click()
  await page.waitForURL(/\/en\/dashboard/)
  const state = await (await request.get(`${API}/__tfa_state`)).json()
  expect(state.data.codes).toBe(9)
  expect(state.data.lastBody.challenge_token).toBe('tfc_stub')
  expect(state.data.lastBody.recovery_code).toBe('abcd0-efgh0')
})

test('expired challenge (client clock) offers to start again; a lost challenge restarts at the password step', async ({ page, request }) => {
  await reset(request, { enabled: true, expires_in: 30 })
  await page.clock.install()
  await password(page)
  await expect(page.getByTestId('two-factor-step')).toBeVisible()
  await page.clock.fastForward(35_000)
  await expect(page.getByText('This sign-in step has expired.').first()).toBeVisible()
  await page.getByTestId('two-factor-restart').click()
  await expect(page.getByLabel(/^Email/)).toBeVisible()
  await expect(page.getByText('This sign-in step has expired.')).toBeVisible()

  await reset(request, { enabled: true, dead_challenge: true })
  await page.locator('input[type=password]').fill(PASSWORD)
  await page.locator('form button[type=submit]').click()
  await page.getByLabel('6-digit code').fill('123456')
  await page.getByRole('button', { name: 'Verify and sign in' }).click()
  await expect(page.getByText('Your sign-in attempt is no longer valid.')).toBeVisible()
  await expect(page.getByLabel(/^Email/)).toBeVisible()
})

test('too many wrong codes: 429 shows the wait time and keeps the form from being hammered', async ({ page, request }) => {
  await reset(request, { enabled: true })
  await password(page)
  const code = page.getByLabel('6-digit code')
  for (let i = 0; i < 5; i++) {
    await code.fill('000000')
    await page.getByRole('button', { name: 'Verify and sign in' }).click()
    await expect(page.getByText('That code is not correct.')).toBeVisible()
  }
  await code.fill('123456')
  await page.getByRole('button', { name: 'Verify and sign in' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'Too many attempts. Try again in 3 seconds.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Verify and sign in' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Verify and sign in' })).toBeEnabled({ timeout: 8000 })
})

test('manage: new recovery codes and turn off need the password and a code', async ({ page, request, context, baseURL }) => {
  await reset(request, { enabled: true })
  await context.addCookies([{ name: 'expa_token', value: 'stub-tfa', url: baseURL! }])
  await go(page, '/en/settings/two-factor')
  await expect(page.getByTestId('two-factor-state')).toHaveText('On')
  await page.getByRole('button', { name: 'Create new recovery codes' }).click()
  const form = page.getByTestId('two-factor-regen')
  await expect(form).toBeVisible()
  await axe(page, 'regen form')
  await form.getByRole('button', { name: 'Create new codes' }).click()
  await expect(form.getByText('Enter your password.')).toBeVisible()
  await form.getByLabel('Current password').fill('wrong-password')
  await form.getByLabel('6-digit code').fill('123456')
  await form.getByRole('button', { name: 'Create new codes' }).click()
  await expect(form.getByText('The password is incorrect.')).toBeVisible()
  await form.getByLabel('Current password').fill(PASSWORD)
  await form.getByRole('button', { name: 'Create new codes' }).click()
  await expect(page.getByTestId('two-factor-codes').getByRole('listitem').first()).toHaveText('wxyz0-efgh0')
  await page.getByLabel('I have saved these codes in a safe place').check()
  await page.getByTestId('two-factor-codes-done').click()

  await page.getByRole('button', { name: 'Turn off two-factor authentication' }).click()
  const off = page.getByTestId('two-factor-disable')
  await off.getByLabel('Current password').fill(PASSWORD)
  await off.getByLabel('6-digit code').fill('123456')
  await off.getByRole('button', { name: 'Turn off', exact: true }).click()
  await expect(page.getByTestId('two-factor-state')).toHaveText('Off')
})

test('stale session flags: a 403 two_factor_setup_required from any admin call shows the gate', async ({ page, request, context, baseURL }) => {
  await reset(request, { stale: true })
  await context.addCookies([{ name: 'expa_token', value: 'stub-tfa', url: baseURL! }])
  await go(page, '/en/admin/users')
  await expect(page.getByTestId('two-factor-gate')).toBeVisible()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Set up two-factor authentication')
})

for (const locale of ['ar', 'it'] as const) {
  test(`${locale}: code step and settings pass axe`, async ({ page, request, context, baseURL }) => {
    await reset(request, { enabled: true })
    await password(page, locale)
    await expect(page.getByTestId('two-factor-step')).toBeVisible()
    await axe(page, `${locale} code step`)
    await page.getByLabel(locale === 'ar' ? 'رمز من 6 أرقام' : 'Codice a 6 cifre').fill('123456')
    await page.locator('form button[type=submit]').click()
    await page.waitForURL(new RegExp(`/${locale}/dashboard`))
    await go(page, `/${locale}/settings/two-factor`)
    await expect(page.getByTestId('two-factor-state')).toBeVisible()
    await axe(page, `${locale} settings`)
    await context.clearCookies()
    await reset(request)
    await context.addCookies([{ name: 'expa_token', value: 'stub-tfa', url: baseURL! }])
    await go(page, `/${locale}/settings/two-factor`)
    await page.getByTestId('two-factor-start').click()
    await expect(page.getByTestId('two-factor-qr')).toBeVisible()
    await axe(page, `${locale} setup`)
  })
}
