#!/usr/bin/env python3
"""Source table for the ARB files. Run: python3 tool/strings.py  (regenerates lib/l10n/app_{ar,en,it}.arb).
Arabic is the template language. Placeholders use {name}; all are Strings."""
import json, re, os
S = [
("appName","إكسبا","EXPA","EXPA"),
("appTagline","مساعدك في الحياة في إيطاليا","Your Life Assistant in Italy","Il tuo assistente per vivere in Italia"),
("tabHome","الرئيسية","Home","Home"),
("tabExplore","استكشف","Explore","Esplora"),
("tabAsk","اسأل EXPA","Ask EXPA","Chiedi a EXPA"),
("tabTasks","المهام","Tasks","Attività"),
("tabProfile","حسابي","Profile","Profilo"),
("retry","إعادة المحاولة","Try again","Riprova"),
("cancel","إلغاء","Cancel","Annulla"),
("save","حفظ","Save","Salva"),
("close","إغلاق","Close","Chiudi"),
("loading","جارٍ التحميل…","Loading…","Caricamento…"),
("errorGeneric","حدث خطأ ما. حاول مرة أخرى.","Something went wrong. Please try again.","Qualcosa è andato storto. Riprova."),
("errorNetwork","لا يوجد اتصال بالإنترنت. تحقق من الشبكة وحاول مرة أخرى.","No internet connection. Check your network and try again.","Nessuna connessione a Internet. Controlla la rete e riprova."),
("errorTimeout","استغرق الطلب وقتًا طويلًا. حاول مرة أخرى.","The request took too long. Please try again.","La richiesta ha impiegato troppo tempo. Riprova."),
("errorServer","الخدمة غير متاحة مؤقتًا. حاول لاحقًا.","The service is temporarily unavailable. Try again later.","Servizio temporaneamente non disponibile. Riprova più tardi."),
("errorForbidden","ليس لديك صلاحية لهذا الإجراء.","You are not allowed to do this.","Non hai i permessi per questa azione."),
("errorNotFound","لم نجد ما تبحث عنه.","We could not find what you are looking for.","Non abbiamo trovato ciò che cerchi."),
("errorRateLimited","طلبات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.","Too many requests. Wait a moment and try again.","Troppe richieste. Attendi un momento e riprova."),
("errorValidation","تحقق من البيانات المدخلة.","Please check the information you entered.","Controlla i dati inseriti."),
("emptyList","لا توجد عناصر لعرضها.","Nothing to show yet.","Niente da mostrare."),
("loadMore","عرض المزيد","Load more","Mostra altro"),
("openOfficialSite","فتح الموقع الرسمي","Open the official website","Apri il sito ufficiale"),
("linkUnsafe","تم حجب الرابط لأنه غير آمن.","This link was blocked because it is not secure.","Link bloccato perché non sicuro."),
("linkOpenFailed","تعذّر فتح الرابط.","The link could not be opened.","Impossibile aprire il link."),
("optional","اختياري","Optional","Facoltativo"),
("skip","تخطي","Skip","Salta"),
("next","التالي","Next","Avanti"),
("delete","حذف","Delete","Elimina"),
("saved","تم الحفظ.","Saved.","Salvato."),
("sessionExpired","انتهت الجلسة. سجّل الدخول مرة أخرى.","Your session has expired. Please sign in again.","Sessione scaduta. Accedi di nuovo."),
("consentRequired","هذا الإجراء يحتاج إلى موافقتك. يمكنك منحها من إعدادات الخصوصية.","This action needs your consent. You can grant it in privacy settings.","Questa azione richiede il tuo consenso. Puoi darlo nelle impostazioni sulla privacy."),
("grantConsent","منح الموافقة","Grant consent","Concedi il consenso"),
("loginTitle","تسجيل الدخول","Sign in","Accedi"),
("loginSubtitle","مرحبًا بعودتك إلى إكسبا","Welcome back to EXPA","Bentornato su EXPA"),
("email","البريد الإلكتروني","Email","Email"),
("password","كلمة المرور","Password","Password"),
("confirmPassword","تأكيد كلمة المرور","Confirm password","Conferma password"),
("name","الاسم","Name","Nome"),
("loginButton","دخول","Sign in","Accedi"),
("registerButton","إنشاء حساب","Create account","Crea account"),
("registerTitle","إنشاء حساب جديد","Create your account","Crea il tuo account"),
("forgotLink","نسيت كلمة المرور؟","Forgot your password?","Password dimenticata?"),
("noAccount","ليس لديك حساب؟ أنشئ حسابًا","No account yet? Create one","Non hai un account? Registrati"),
("haveAccount","لديك حساب؟ سجّل الدخول","Already have an account? Sign in","Hai già un account? Accedi"),
("acceptTerms","أوافق على شروط الاستخدام","I accept the terms of use","Accetto i termini d'uso"),
("acceptPrivacy","اطلعت على سياسة الخصوصية وأوافق عليها","I have read and accept the privacy policy","Ho letto e accetto l'informativa sulla privacy"),
("passwordHint","10 أحرف على الأقل، مع أحرف وأرقام","At least 10 characters, with letters and numbers","Almeno 10 caratteri, con lettere e numeri"),
("invalidCredentials","البريد الإلكتروني أو كلمة المرور غير صحيحة.","Incorrect email or password.","Email o password non corrette."),
("fieldRequired","هذا الحقل مطلوب.","This field is required.","Campo obbligatorio."),
("invalidEmail","أدخل بريدًا إلكترونيًا صحيحًا.","Enter a valid email address.","Inserisci un indirizzo email valido."),
("passwordsMismatch","كلمتا المرور غير متطابقتين.","The passwords do not match.","Le password non coincidono."),
("passwordTooShort","كلمة المرور قصيرة جدًا.","The password is too short.","La password è troppo corta."),
("mustAcceptBoth","يجب الموافقة على الشروط وسياسة الخصوصية.","You must accept the terms and the privacy policy.","Devi accettare i termini e l'informativa sulla privacy."),
("forgotTitle","استعادة كلمة المرور","Reset your password","Recupera la password"),
("forgotBody","أدخل بريدك الإلكتروني وسنرسل لك رابط الاستعادة إن كان الحساب موجودًا.","Enter your email and we will send a reset link if the account exists.","Inserisci la tua email: se l'account esiste, riceverai un link di recupero."),
("sendResetLink","إرسال الرابط","Send reset link","Invia il link"),
("resetSent","إذا كان الحساب موجودًا فقد أرسلنا رابط الاستعادة إلى بريدك.","If the account exists, a reset link is on its way to your email.","Se l'account esiste, ti abbiamo inviato un link di recupero."),
("verifyTitle","تحقق من بريدك الإلكتروني","Check your email","Controlla la tua email"),
("verifyBody","أرسلنا رابط التفعيل إلى بريدك. افتح الرابط ثم ارجع إلى التطبيق. بعض الميزات مثل اسأل EXPA تتطلب بريدًا مفعّلًا.","We sent a verification link to your email. Open it, then come back to the app. Some features such as Ask EXPA need a verified email.","Abbiamo inviato un link di verifica alla tua email. Aprilo e torna nell'app. Alcune funzioni, come Chiedi a EXPA, richiedono un'email verificata."),
("verifyBanner","بريدك الإلكتروني غير مفعّل بعد.","Your email is not verified yet.","La tua email non è ancora verificata."),
("resendVerification","إعادة إرسال رابط التفعيل","Resend verification email","Reinvia l'email di verifica"),
("verificationSent","تم إرسال رابط التفعيل.","Verification email sent.","Email di verifica inviata."),
("verifiedCheck","لقد فعّلت بريدي","I have verified my email","Ho verificato l'email"),
("continueToApp","المتابعة إلى التطبيق","Continue to the app","Continua nell'app"),
("logout","تسجيل الخروج","Sign out","Esci"),
("accountSuspended","هذا الحساب موقوف.","This account is suspended.","Questo account è sospeso."),
("language","اللغة","Language","Lingua"),
("langAr","العربية","العربية","العربية"),
("langEn","English","English","English"),
("langIt","Italiano","Italiano","Italiano"),
("homeGreeting","مرحبًا {name}","Welcome {name}","Ciao {name}"),
("scoreTitle","درجة EXPA","EXPA Score","Punteggio EXPA"),
("scoreHow","كيف تُحسب؟","How is it calculated?","Come viene calcolato?"),
("scoreUnavailable","لا توجد بيانات كافية لحساب الدرجة بعد.","Not enough information to calculate your score yet.","Non ci sono ancora dati sufficienti per calcolare il punteggio."),
("scoreSemantics","درجة EXPA {percent} بالمئة","EXPA score {percent} percent","Punteggio EXPA {percent} per cento"),
("nextActions","ماذا أفعل الآن؟","What should I do next?","Cosa devo fare adesso?"),
("nextActionsEmpty","لا توجد إجراءات مقترحة الآن.","No suggested actions right now.","Nessuna azione suggerita al momento."),
("personalizationOff","التخصيص متوقف. فعّله من الخصوصية للحصول على اقتراحات تناسبك.","Personalization is off. Turn it on in privacy settings for tailored suggestions.","La personalizzazione è disattivata. Attivala nella privacy per suggerimenti su misura."),
("onboardingContinue","أكمل ملفك الشخصي","Complete your profile","Completa il tuo profilo"),
("tasksTitle","مهام الاستقرار","Setup tasks","Attività di inserimento"),
("taskMarkDone","تم","Mark done","Fatto"),
("taskReopen","إعادة فتح","Reopen","Riapri"),
("taskDismiss","لا ينطبق عليّ","Not for me","Non mi riguarda"),
("taskDone","مكتملة","Done","Completata"),
("tasksDocuments","وثائقي","My documents","I miei documenti"),
("guidesTitle","الأدلة","Guides","Guide"),
("searchHint","ابحث…","Search…","Cerca…"),
("allCategories","الكل","All","Tutte"),
("sourceLabel","المصدر","Source","Fonte"),
("sourceOfficial","رسمي","Official","Ufficiale"),
("sourceInstitutional","مؤسسي","Institutional","Istituzionale"),
("sourceVerifiedPartner","شريك موثّق","Verified partner","Partner verificato"),
("sourceThirdParty","طرف ثالث","Third party","Terze parti"),
("lastVerified","آخر تحقق: {date}","Last verified: {date}","Ultima verifica: {date}"),
("neverVerified","لم يتم التحقق من المصدر بعد","Not verified yet","Non ancora verificato"),
("freshFresh","محدّث","Up to date","Aggiornato"),
("freshStale","قد يكون قديمًا","May be outdated","Potrebbe essere datato"),
("freshOutdated","قديم – تحقق من الموقع الرسمي","Outdated: check the official site","Obsoleto: controlla il sito ufficiale"),
("freshUnverified","غير موثّق","Unverified","Non verificato"),
("fallbackLocale","هذا المحتوى غير متوفر بلغتك، يُعرض بلغة أخرى.","This content is not available in your language and is shown in another one.","Questo contenuto non è disponibile nella tua lingua ed è mostrato in un'altra."),
("secWhatIs","ما هو؟","What is it?","Che cos'è?"),
("secWhoNeeds","من يحتاجه؟","Who needs it?","Chi ne ha bisogno?"),
("secDocuments","الوثائق المطلوبة","Required documents","Documenti richiesti"),
("secSteps","الخطوات","Steps","Passaggi"),
("secWhere","أين تقدّم؟","Where to apply","Dove presentare la domanda"),
("secBook","كيف تحجز؟","How to book","Come prenotare"),
("secCosts","التكاليف","Costs","Costi"),
("secTime","مدة المعالجة","Processing time","Tempi di elaborazione"),
("verifyOfficialNotice","معلومات عامة للإرشاد. تحقق دائمًا من المصدر الرسمي قبل أي قرار.","General guidance. Always check the official source before deciding.","Informazioni generali di orientamento. Verifica sempre la fonte ufficiale prima di decidere."),
("documentsTitle","وثائقي","My documents","I miei documenti"),
("addDocument","إضافة وثيقة","Add a document","Aggiungi documento"),
("docType","نوع الوثيقة","Document type","Tipo di documento"),
("docLabel","تسمية (اختياري)","Label (optional)","Etichetta (facoltativa)"),
("issueDate","تاريخ الإصدار","Issue date","Data di rilascio"),
("expiryDate","تاريخ الانتهاء","Expiry date","Data di scadenza"),
("notes","ملاحظات","Notes","Note"),
("remindersEnabled","تذكيري قبل الانتهاء","Remind me before it expires","Ricordami prima della scadenza"),
("noExpiry","بدون تاريخ انتهاء","No expiry date","Nessuna scadenza"),
("daysRemaining","متبقي {n} يوم","{n} days left","{n} giorni rimasti"),
("expiredDaysAgo","انتهت منذ {n} يوم","Expired {n} days ago","Scaduto da {n} giorni"),
("statusValid","سارية","Valid","Valido"),
("statusExpiringSoon","تنتهي قريبًا","Expiring soon","In scadenza"),
("statusExpired","منتهية","Expired","Scaduto"),
("statusNoExpiry","بلا انتهاء","No expiry","Senza scadenza"),
("pickDate","اختر التاريخ","Pick a date","Scegli la data"),
("clearDate","مسح","Clear","Cancella"),
("docsEmpty","لم تضف أي وثيقة بعد. أضف جواز السفر أو تصريح الإقامة لنذكّرك قبل انتهائهما.","You have not added any document yet. Add your passport or residence permit and we will remind you before they expire.","Non hai ancora aggiunto documenti. Aggiungi passaporto o permesso di soggiorno e ti avviseremo prima della scadenza."),
("deleteDocConfirm","حذف هذه الوثيقة؟","Delete this document?","Eliminare questo documento?"),
("consentNeededDocs","لحفظ وثائقك نحتاج موافقتك على تخزين الوثائق.","To save your documents we need your consent to store them.","Per salvare i documenti serve il tuo consenso alla conservazione."),
("docAttachmentsNote","المرفقات متاحة في الموقع. هذه النسخة تتتبع التواريخ فقط.","Attachments are available on the website. This version tracks dates only.","Gli allegati sono disponibili sul sito. Questa versione gestisce solo le date."),
("askTitle","اسأل EXPA","Ask EXPA","Chiedi a EXPA"),
("askHint","اكتب سؤالك بالعربية أو الإنجليزية أو الإيطالية","Type your question in Arabic, English or Italian","Scrivi la tua domanda in arabo, inglese o italiano"),
("askSend","إرسال","Send","Invia"),
("askIntro","اسألني عن الإقامة والوثائق والخدمات الحكومية. أجيب اعتمادًا على مصادر موثّقة وأذكرها لك.","Ask me about residence, documents and government services. I answer from verified sources and show them to you.","Chiedimi di permesso di soggiorno, documenti e servizi pubblici. Rispondo da fonti verificate e te le mostro."),
("askUsage","المتبقي اليوم: {n}","Remaining today: {n}","Rimaste oggi: {n}"),
("askResets","يتجدد الحد في {date}","Limit resets on {date}","Il limite si azzera il {date}"),
("askLimitReached","وصلت إلى حدّ الأسئلة اليومي.","You have reached today's question limit.","Hai raggiunto il limite giornaliero di domande."),
("askVerifyEmail","فعّل بريدك الإلكتروني لاستخدام اسأل EXPA.","Verify your email to use Ask EXPA.","Verifica la tua email per usare Chiedi a EXPA."),
("askFailed","تعذّرت المعالجة الآن. حاول مرة أخرى.","I couldn't process that right now. Please try again.","Non sono riuscito a elaborare la richiesta. Riprova."),
("askDegraded","تعذّر استخدام الذكاء الاصطناعي الآن. هذه إجابة محدودة، تصفّح الأدلة للحصول على معلومات موثّقة.","The AI is unavailable right now. This is a limited answer; browse the guides for verified information.","L'IA non è disponibile ora. Questa è una risposta limitata: consulta le guide per informazioni verificate."),
("askBrowseGuides","تصفّح الأدلة","Browse the guides","Sfoglia le guide"),
("askSourcesTitle","المصادر","Sources","Fonti"),
("askNoSources","لا توجد مصادر موثّقة لهذه الإجابة.","There are no verified sources for this answer.","Nessuna fonte verificata per questa risposta."),
("askNoticeTitle","تنبيه","Notice","Avviso"),
("askYou","أنت","You","Tu"),
("askAssistant","EXPA","EXPA","EXPA"),
("askSuggested","إجراءات مقترحة","Suggested actions","Azioni suggerite"),
("askLabelOfficial","معلومات رسمية","Official information","Informazione ufficiale"),
("askLabelGeneral","إرشاد عام","General guidance","Orientamento generale"),
("askLabelAi","شرح بالذكاء الاصطناعي","AI explanation","Spiegazione dell'IA"),
("askLabelThird","خدمة أو مصدر من طرف ثالث","Third-party service or source","Servizio o fonte di terzi"),
("learnTitle","تعلّم الإيطالية","Learn Italian","Impara l'italiano"),
("dailyTitle","إيطالية اليوم – 10 دقائق","Daily 10-minute Italian","Italiano in 10 minuti al giorno"),
("dailyDone","تم اليوم","Done today","Fatto oggi"),
("minutes","{n} دقيقة","{n} min","{n} min"),
("streak","سلسلة الأيام: {n}","Day streak: {n}","Giorni consecutivi: {n}"),
("lessonsTitle","الدروس","Lessons","Lezioni"),
("lessonStart","ابدأ الدرس","Start lesson","Inizia la lezione"),
("lessonComplete","أنهيت الدرس","Mark as completed","Segna come completata"),
("lessonCompleted","مكتمل","Completed","Completata"),
("lessonsEmpty","لا توجد دروس متاحة بعد.","No lessons available yet.","Nessuna lezione disponibile."),
("jobsTitle","الوظائف","Jobs","Lavoro"),
("matchScore","نسبة التوافق: {n}%","Match score: {n}%","Compatibilità: {n}%"),
("matchUnknown","لا توجد بيانات كافية للمطابقة","Not enough data to match","Dati insufficienti per il confronto"),
("matchReasons","لماذا هذه النتيجة؟","Why this score?","Perché questo punteggio?"),
("reasonMatch","متوافق","Matches","Corrisponde"),
("reasonPartial","متوافق جزئيًا","Partly matches","Corrisponde in parte"),
("reasonMismatch","غير متوافق","Does not match","Non corrisponde"),
("reasonUnknown","غير معروف (لا يؤثر سلبًا)","Unknown (not counted against you)","Sconosciuto (non penalizza)"),
("applyOriginal","التقديم في الموقع الأصلي","Apply on the original site","Candidati sul sito originale"),
("applyNotice","EXPA لا يقدّم الطلب نيابةً عنك. ستنتقل إلى صفحة التقديم الأصلية.","EXPA does not submit applications. You will go to the original application page.","EXPA non invia candidature. Andrai alla pagina originale di candidatura."),
("visaStated","ذكر المصدر دعم التأشيرة","The source states visa sponsorship","La fonte indica sponsorizzazione del visto"),
("visaNotStated","لا يذكر المصدر دعم التأشيرة","Visa sponsorship is not stated","Sponsorizzazione del visto non indicata"),
("jobsEmpty","لا توجد وظائف مطابقة الآن.","No matching jobs right now.","Nessun lavoro corrispondente al momento."),
("jobSource","المصدر: {name}","Source: {name}","Fonte: {name}"),
("jobsSignInForMatch","سجّل الدخول وأكمل ملفك لرؤية نسبة التوافق.","Sign in and complete your profile to see match scores.","Accedi e completa il profilo per vedere la compatibilità."),
("notificationsTitle","الإشعارات","Notifications","Notifiche"),
("markAllRead","تعليم الكل كمقروء","Mark all as read","Segna tutto come letto"),
("notificationsEmpty","لا توجد إشعارات.","No notifications.","Nessuna notifica."),
("apptTitle","حجز المواعيد","Appointments","Appuntamenti"),
("apptNotice","EXPA لا يحجز نيابةً عنك. سنوجّهك إلى الجهة الرسمية لإتمام الحجز بنفسك.","EXPA does not book for you. We point you to the official body so you can complete the booking yourself.","EXPA non prenota per te. Ti indichiamo l'ente ufficiale per completare la prenotazione."),
("apptOfficeType","نوع الجهة","Office type","Tipo di ufficio"),
("apptCity","المدينة","City","Città"),
("apptSearch","عرض الجهات","Show offices","Mostra uffici"),
("apptGoOfficial","الانتقال إلى صفحة الحجز الرسمية","Go to the official booking page","Vai alla pagina ufficiale di prenotazione"),
("apptNoUrl","لا يوجد رابط حجز رسمي مسجّل. راجع الموقع الرسمي للجهة.","No official booking link is on file. Check the office's official website.","Nessun link ufficiale di prenotazione. Controlla il sito ufficiale dell'ufficio."),
("apptEmpty","لا توجد جهات مسجّلة لهذه المدينة.","No offices on file for this city.","Nessun ufficio registrato per questa città."),
("exploreTitle","استكشف","Explore","Esplora"),
("exploreGuides","الأدلة والوثائق","Guides & documents","Guide e documenti"),
("exploreLearn","تعلّم الإيطالية","Learn Italian","Impara l'italiano"),
("exploreJobs","الوظائف","Jobs","Lavoro"),
("exploreAppointments","حجز المواعيد","Appointments","Appuntamenti"),
("exploreMyDocs","وثائقي وتواريخ الانتهاء","My documents & expiry dates","I miei documenti e scadenze"),
("exploreNotifications","الإشعارات","Notifications","Notifiche"),
("profileTitle","حسابي","Profile","Profilo"),
("profilePrivacy","الخصوصية والموافقات","Privacy & consents","Privacy e consensi"),
("profileOnboarding","ملفي الشخصي","My profile details","I miei dati"),
("pushNote","الإشعارات الفورية غير مفعّلة في هذه النسخة.","Push notifications are not enabled in this version.","Le notifiche push non sono attive in questa versione."),
("privacyTitle","الخصوصية","Privacy","Privacy"),
("consentsTitle","موافقاتك","Your consents","I tuoi consensi"),
("consentRequiredBadge","مطلوب","Required","Obbligatorio"),
("consentsHint","يمكنك تغيير الموافقات الاختيارية في أي وقت.","You can change optional consents at any time.","Puoi modificare i consensi facoltativi in qualsiasi momento."),
("exportTitle","تصدير بياناتي","Export my data","Esporta i miei dati"),
("exportBody","اطلب نسخة من بياناتك الشخصية. الحد الأقصى 5 طلبات في الساعة.","Request a copy of your personal data. Limit: 5 requests per hour.","Richiedi una copia dei tuoi dati personali. Limite: 5 richieste all'ora."),
("exportRequest","طلب التصدير","Request export","Richiedi l'esportazione"),
("exportDone","تم تجهيز بياناتك ({n} أقسام). لم يتم حفظها على الجهاز.","Your data is ready ({n} sections). It was not saved on this device.","I tuoi dati sono pronti ({n} sezioni). Non sono stati salvati sul dispositivo."),
("deleteAccountTitle","حذف الحساب","Delete account","Elimina account"),
("deleteAccountBody","الحذف نهائي. يتوقف الوصول فورًا ويكتمل مسح البيانات لاحقًا. أدخل كلمة المرور للتأكيد.","Deletion is permanent. Access stops immediately and erasure completes later. Enter your password to confirm.","L'eliminazione è definitiva. L'accesso si interrompe subito e la cancellazione si completa dopo. Inserisci la password per confermare."),
("deleteAccountConfirm","طلب حذف الحساب","Request account deletion","Richiedi eliminazione account"),
("deleteRequested","تم تقديم طلب الحذف.","Deletion requested.","Richiesta di eliminazione inviata."),
("onboardingTitle","عن وضعك في إيطاليا","About you in Italy","La tua situazione in Italia"),
("onboardingIntro","نجمع فقط ما يلزم للتخصيص. يمكنك تخطي الأسئلة الاختيارية.","We only collect what personalization needs. You can skip optional questions.","Raccogliamo solo ciò che serve alla personalizzazione. Puoi saltare le domande facoltative."),
("fieldSegment","وضعك الحالي","Current status","Situazione attuale"),
("fieldNationality","الجنسية (رمز من حرفين، مثل EG)","Nationality (2-letter code, e.g. EG)","Nazionalità (codice a 2 lettere, es. EG)"),
("fieldCity","المدينة","City","Città"),
("fieldResidence","نوع الإقامة","Residence type","Tipo di soggiorno"),
("fieldItalian","مستوى الإيطالية","Italian level","Livello di italiano"),
("fieldEnglish","مستوى الإنجليزية","English level","Livello di inglese"),
("fieldGoals","أهدافك","Your goals","I tuoi obiettivi"),
("fieldAge","الفئة العمرية","Age range","Fascia d'età"),
("notSelected","غير محدد","Not set","Non impostato"),
("completeOnboarding","إنهاء","Finish","Fine"),
("onboardingSegmentRequired","اختر وضعك الحالي لإنهاء الإعداد.","Choose your current status to finish.","Scegli la tua situazione per terminare."),
("offlineBanner","لا يوجد اتصال بالإنترنت. تُعرض البيانات المحفوظة على جهازك فقط.","You are offline. Only data saved on your device is shown.","Sei offline. Vengono mostrati solo i dati salvati sul dispositivo."),
("apptGuidesTitle","أدلة الحجز","Booking guides","Guide alla prenotazione"),
("apptNotBookedByExpa","إكسبا لا يحجز نيابةً عنك: ستُحوَّل إلى الجهة الرسمية.","EXPA does not book for you: you are sent to the official body.","EXPA non prenota per te: vieni indirizzato all'ente ufficiale."),
("officeQuestura","الشرطة (Questura)","Police headquarters (Questura)","Questura"),
("officePrefettura","المحافظة (Prefettura)","Prefecture (Prefettura)","Prefettura"),
("officeComune","البلدية (Comune)","Municipality (Comune)","Comune"),
("officeAnagrafe","السجل المدني (Anagrafe)","Civil registry (Anagrafe)","Anagrafe"),
("officeAsl","هيئة الصحة المحلية (ASL)","Local health authority (ASL)","ASL"),
("officeInps","التأمينات الاجتماعية (INPS)","Social security (INPS)","INPS"),
("officeAgenziaEntrate","وكالة الإيرادات (Agenzia delle Entrate)","Revenue Agency (Agenzia delle Entrate)","Agenzia delle Entrate"),
("officePoste","البريد الإيطالي (Poste Italiane)","Italian Post (Poste Italiane)","Poste Italiane"),
("officeMotorizzazione","إدارة المركبات (Motorizzazione)","Vehicle licensing (Motorizzazione)","Motorizzazione"),
("officeUniversity","جامعة","University","Università"),
("officeOther","جهة أخرى","Other body","Altro ente"),
("officePhone","الهاتف","Phone","Telefono"),
("secAdmission","شروط القبول","Admission requirements","Requisiti di ammissione"),
("secTips","نصائح","Tips","Consigli"),
("secCautions","تنبيهات","Cautions","Avvertenze"),
("secNotes","ملاحظات","Notes","Note"),
("exploreGovernment","الخدمات الحكومية","Government services","Servizi pubblici"),
("explorePatente","رخصة القيادة (Patente)","Driving licence (Patente)","Patente"),
("exploreStudy","الدراسة في إيطاليا","Study in Italy","Studiare in Italia"),
("exploreScan","مسح خطاب أو مستند","Scan a letter or document","Scansiona una lettera o un documento"),
("exploreSaved","المحفوظات للعمل دون إنترنت","Saved for offline","Salvati offline"),
("govTitle","الخدمات الحكومية","Government services","Servizi pubblici"),
("govServices","الخدمات","Services","Servizi"),
("govOffices","المكاتب","Offices","Uffici"),
("govEmpty","لا يوجد محتوى منشور بعد. تتم إضافة الخدمات الحكومية بعد مراجعتها من مصادر رسمية.","Nothing is published yet. Government services are added after review against official sources.","Nessun contenuto pubblicato per ora. I servizi vengono aggiunti dopo la verifica su fonti ufficiali."),
("govRelatedGuide","الدليل المرتبط","Related guide","Guida collegata"),
("studyTitle","الدراسة في إيطاليا","Study in Italy","Studiare in Italia"),
("studyPrograms","البرامج","Programs","Corsi"),
("studyUniversities","الجامعات","Universities","Università"),
("studyScholarships","المنح","Scholarships","Borse di studio"),
("studyEmpty","لا يوجد محتوى منشور بعد.","Nothing is published yet.","Nessun contenuto pubblicato per ora."),
("studyTuition","الرسوم الدراسية","Tuition","Tasse universitarie"),
("studyPerYear","سنويًا","per year","all'anno"),
("studyDeadline","آخر موعد للتقديم","Application deadline","Scadenza della domanda"),
("jobsSavedTitle","الوظائف المحفوظة","Saved jobs","Lavori salvati"),
("jobsSavedEmpty","لم تحفظ أي وظيفة بعد.","You have not saved any jobs yet.","Non hai ancora salvato nessun lavoro."),
("jobSave","حفظ الوظيفة","Save job","Salva il lavoro"),
("jobUnsave","إزالة من المحفوظات","Remove from saved","Rimuovi dai salvati"),
("lessonTip","نصيحة","Tip","Consiglio"),
("askHistoryTitle","المحادثات السابقة","Past conversations","Conversazioni precedenti"),
("askHistoryEmpty","لا توجد محادثات سابقة.","No past conversations.","Nessuna conversazione precedente."),
("askHistoryUntitled","محادثة","Conversation","Conversazione"),
("askHistoryDelete","حذف المحادثة","Delete conversation","Elimina la conversazione"),
("askHistoryDeleteBody","سيتم حذف هذه المحادثة نهائيًا.","This conversation will be permanently deleted.","Questa conversazione verrà eliminata definitivamente."),
("askNewChat","محادثة جديدة","New conversation","Nuova conversazione"),
("searchTitle","البحث","Search","Cerca"),
("searchMinChars","اكتب حرفين على الأقل ثم اضغط بحث.","Type at least 2 characters, then search.","Scrivi almeno 2 caratteri e avvia la ricerca."),
("searchEmpty","لا توجد نتائج. جرّب كلمات أخرى.","No results. Try other words.","Nessun risultato. Prova con altre parole."),
("savedTitle","المحفوظات","Saved","Salvati"),
("savedEmpty","لم تحفظ أي دليل أو درس بعد. اضغط على علامة الحفظ داخل الدليل أو الدرس.","Nothing saved yet. Tap the bookmark inside a guide or lesson.","Ancora nulla di salvato. Tocca il segnalibro in una guida o lezione."),
("savedHint","هذه النسخ محفوظة على جهازك ويمكن فتحها دون إنترنت. تحقق من تاريخ آخر مراجعة قبل الاعتماد عليها.","These copies are stored on your device and open without internet. Check the last-verified date before relying on them.","Queste copie sono sul tuo dispositivo e si aprono senza Internet. Controlla la data dell'ultima verifica prima di affidarti ad esse."),
("savedAdd","احفظ للعمل دون إنترنت","Save for offline","Salva per l'offline"),
("savedRemove","إزالة من المحفوظات","Remove from saved","Rimuovi dai salvati"),
("savedAdded","تم الحفظ على جهازك.","Saved on your device.","Salvato sul dispositivo."),
("savedRemoved","تمت الإزالة من المحفوظات.","Removed from saved.","Rimosso dai salvati."),
("savedOfflineCopy","هذه نسخة محفوظة بتاريخ {date}. تعذّر تحديثها الآن.","This is the copy saved on {date}. It could not be refreshed now.","Questa è la copia salvata il {date}. Non è stato possibile aggiornarla ora."),
("savedRefreshing","نسخة محفوظة. جارٍ التحديث…","Saved copy. Refreshing…","Copia salvata. Aggiornamento in corso…"),
("savedOn","حُفظ في {date}","Saved on {date}","Salvato il {date}"),
("savedStale","قد تكون هذه النسخة قديمة. تأكد من الموقع الرسمي.","This copy may be out of date. Check the official website.","Questa copia potrebbe essere superata. Controlla il sito ufficiale."),
("patenteTitle","رخصة القيادة (Patente)","Driving licence (Patente)","Patente"),
("patenteDisclaimer","محتوى تعليمي عام. قواعد الامتحان والأسئلة الرسمية تحددها الجهات الإيطالية، وتحقق دائمًا من المصدر الرسمي.","General learning content. Exam rules and official questions are set by the Italian authorities; always check the official source.","Contenuto didattico generale. Regole d'esame e quiz ufficiali sono stabiliti dalle autorità italiane: verifica sempre la fonte ufficiale."),
("patenteEmpty","لم يُنشر محتوى الباتينتي بعد. لا ننشر أسئلة إلا إذا كانت لدينا حقوق استخدامها. سنُعلمك عند توفرها.","Patente content is not published yet. We only publish questions we have the rights to use. It will appear here once available.","I contenuti Patente non sono ancora pubblicati. Pubblichiamo solo quiz di cui abbiamo i diritti. Appariranno qui appena disponibili."),
("patenteMockExam","امتحان تجريبي","Mock exam","Simulazione d'esame"),
("patenteRules","{questions} سؤالًا، أقصى عدد للأخطاء {errors}، المدة {minutes} دقيقة.","{questions} questions, up to {errors} errors, {minutes} minutes.","{questions} domande, massimo {errors} errori, {minutes} minuti."),
("patenteStartExam","ابدأ الامتحان التجريبي","Start mock exam","Inizia la simulazione"),
("patenteProgress","تقدمك","Your progress","I tuoi progressi"),
("patenteProgressLine","امتحانات أجريتها: {taken}، ناجحة: {passed}","Exams taken: {taken}, passed: {passed}","Simulazioni svolte: {taken}, superate: {passed}"),
("patentePassRate","نسبة النجاح في آخر الامتحانات: {rate}٪","Recent pass rate: {rate}%","Percentuale di successo recente: {rate}%"),
("patenteWeakTopics","مواضيع تحتاج إلى مراجعة: {topics}","Topics to review: {topics}","Argomenti da ripassare: {topics}"),
("patentePracticeWeak","تدرّب على المواضيع الضعيفة","Practise weak topics","Esercitati sugli argomenti deboli"),
("patenteTopics","المواضيع","Topics","Argomenti"),
("patenteTopicsHint","اضغط على موضوع للدراسة، أو حدّد مواضيع للتدرّب عليها.","Tap a topic to study it, or tick topics to practise.","Tocca un argomento per studiarlo o seleziona gli argomenti da esercitare."),
("patenteNoTopics","لا توجد مواضيع منشورة بعد.","No topics published yet.","Nessun argomento pubblicato per ora."),
("patenteQuestionCount","{n} سؤالًا","{n} questions","{n} domande"),
("patentePractice","تدرّب على المواضيع المحددة","Practise selected topics","Esercitati sugli argomenti selezionati"),
("patenteCategories","فئات الرخصة","Licence categories","Categorie di patente"),
("patenteTrue","صح (Vero)","True (Vero)","Vero"),
("patenteFalse","خطأ (Falso)","False (Falso)","Falso"),
("patenteSubmit","إنهاء وتسليم الإجابات","Finish and submit","Termina e consegna"),
("patenteAnswered","أجبت عن {done} من {total}","Answered {done} of {total}","Risposto a {done} su {total}"),
("patenteMaxErrors","أقصى عدد للأخطاء المسموح: {n}","Maximum errors allowed: {n}","Errori massimi consentiti: {n}"),
("patenteTimeLeft","الوقت المتبقي {time}","Time left {time}","Tempo rimasto {time}"),
("patenteTooEarly","لا يمكن تسليم الامتحان بهذه السرعة. أجب عن الأسئلة أولًا ثم حاول مرة أخرى.","The exam cannot be submitted this quickly. Answer the questions, then try again.","L'esame non può essere consegnato così presto. Rispondi alle domande e riprova."),
("patentePassed","نجحت في هذا الامتحان التجريبي","You passed this mock exam","Hai superato questa simulazione"),
("patenteFailed","لم تنجح في هذا الامتحان التجريبي","You did not pass this mock exam","Non hai superato questa simulazione"),
("patenteResultLine","إجابات صحيحة: {correct}، أخطاء: {errors} (الحد الأقصى {max})","Correct: {correct}, errors: {errors} (maximum {max})","Corrette: {correct}, errori: {errors} (massimo {max})"),
("patentePracticeResult","إجابات صحيحة: {correct} من {total}","Correct: {correct} of {total}","Corrette: {correct} su {total}"),
("patenteTimedOut","انتهى الوقت وتم تسليم الإجابات تلقائيًا.","Time ran out and your answers were submitted automatically.","Il tempo è scaduto e le risposte sono state consegnate automaticamente."),
("patenteReview","مراجعة الأسئلة","Review","Revisione"),
("patenteNotAnswered","لم تجب عن هذا السؤال","You did not answer this question","Non hai risposto a questa domanda"),
("patenteYourAnswer","إجابتك: {answer}","Your answer: {answer}","La tua risposta: {answer}"),
("patenteCorrectAnswer","الإجابة الصحيحة: {answer}","Correct answer: {answer}","Risposta corretta: {answer}"),
("patenteBack","العودة إلى الباتينتي","Back to Patente","Torna alla Patente"),
("pushTitle","الإشعارات الفورية","Push notifications","Notifiche push"),
("pushSubtitle","تذكيرات بمواعيد انتهاء وثائقك والأمور المهمة.","Reminders about your document deadlines and important things.","Promemoria sulle scadenze dei documenti e su cose importanti."),
("pushRationaleTitle","تفعيل الإشعارات؟","Turn on notifications?","Attivare le notifiche?"),
("pushRationaleBody","سنرسل لك تذكيرات قبل انتهاء وثائقك (مثل تصريح الإقامة) وتنبيهات مهمة. لن نرسل إعلانات. يمكنك إيقافها في أي وقت. سيطلب منك النظام الإذن بعد هذه الخطوة.","We will send reminders before your documents (such as your residence permit) expire, and important alerts. No advertising. You can turn this off at any time. Your device will ask for permission after this step.","Ti invieremo promemoria prima della scadenza dei documenti (come il permesso di soggiorno) e avvisi importanti. Nessuna pubblicità. Puoi disattivarle in qualsiasi momento. Dopo questo passaggio il dispositivo chiederà il permesso."),
("pushAllow","متابعة","Continue","Continua"),
("pushDenied","تم رفض إذن الإشعارات. يمكنك تفعيله من إعدادات الجهاز.","Notification permission was denied. You can enable it in your device settings.","Il permesso per le notifiche è stato negato. Puoi attivarlo nelle impostazioni del dispositivo."),
("pushFailed","تعذّر تفعيل الإشعارات الآن. حاول مرة أخرى لاحقًا.","Notifications could not be turned on right now. Please try again later.","Impossibile attivare le notifiche ora. Riprova più tardi."),
("pushEnabledNote","تم تفعيل الإشعارات على هذا الجهاز.","Notifications are on for this device.","Le notifiche sono attive su questo dispositivo."),
("logoutConfirmTitle","تسجيل الخروج؟","Sign out?","Uscire?"),
("logoutConfirmBody","ستُحذف البيانات المحفوظة على هذا الجهاز وسيتوقف استلام الإشعارات.","Data saved on this device will be removed and notifications will stop.","I dati salvati su questo dispositivo verranno rimossi e le notifiche si interromperanno."),
("deleteConfirmBody","حذف الحساب لا يمكن التراجع عنه. هل أنت متأكد؟","Deleting your account cannot be undone. Are you sure?","L'eliminazione dell'account non può essere annullata. Sei sicuro?"),
("exportShare","مشاركة أو حفظ نسخة…","Share or save a copy…","Condividi o salva una copia…"),
("exportShareConfirmTitle","مشاركة بياناتك الشخصية","Share your personal data","Condividi i tuoi dati personali"),
("exportShareConfirmBody","الملف يحتوي على بياناتك الشخصية. اختر وجهة آمنة فقط (مثل تطبيق ملاحظات خاص بك أو بريدك). لا يحفظه إكسبا على الجهاز.","The file contains your personal data. Choose a safe destination only (such as your own notes app or your email). EXPA does not store it on the device.","Il file contiene i tuoi dati personali. Scegli solo una destinazione sicura (ad esempio la tua app di note o la tua email). EXPA non lo salva sul dispositivo."),
("nationalityInvalid","أدخل رمز الدولة من حرفين (مثل EG) أو اتركه فارغًا.","Enter a 2-letter country code (e.g. EG) or leave it empty.","Inserisci un codice paese di 2 lettere (es. EG) oppure lascia vuoto."),
("resetTitle","كلمة مرور جديدة","Set a new password","Nuova password"),
("resetButton","حفظ كلمة المرور","Save password","Salva la password"),
("resetDone","تم تغيير كلمة المرور. سجّل الدخول بكلمة المرور الجديدة.","Your password was changed. Sign in with the new password.","Password modificata. Accedi con la nuova password."),
("resetInvalidLink","رابط إعادة التعيين غير صالح أو ناقص. اطلب رابطًا جديدًا.","The reset link is invalid or incomplete. Request a new one.","Il link di reimpostazione non è valido o è incompleto. Richiedine uno nuovo."),
("verifySuccess","تم تأكيد بريدك الإلكتروني.","Your email address is verified.","Il tuo indirizzo email è stato verificato."),
("verifyInvalidLink","رابط التأكيد غير صالح أو منتهي. اطلب رابطًا جديدًا من داخل التطبيق.","The verification link is invalid or expired. Request a new one from inside the app.","Il link di verifica non è valido o è scaduto. Richiedine uno nuovo dall'app."),
("scannerTitle","مسح خطاب أو مستند","Scan a letter or document","Scansiona una lettera o un documento"),
("scannerIntro","صوّر خطابًا (مثل خطاب من البلدية أو فاتورة) أو الصق نصه، وسنشرح لك محتواه وأهم تواريخه.","Photograph a letter (for example from the Comune, or a bill) or paste its text, and we will explain it and its key dates.","Fotografa una lettera (ad esempio del Comune, o una bolletta) oppure incolla il testo: ti spiegheremo il contenuto e le date importanti."),
("scannerPrivacy","لا يُرسل شيء إلى إكسبا قبل أن تراجعه بنفسك وتضغط «إرسال». الشرح ليس استشارة قانونية.","Nothing is sent to EXPA until you have reviewed it and tap Send. The explanation is not legal advice.","Nulla viene inviato a EXPA finché non lo hai controllato e premi Invia. La spiegazione non è una consulenza legale."),
("scannerCameraWhy","نستخدم الكاميرا فقط عندما تضغط على زر المسح، لتصوير المستند الذي تختاره.","The camera is used only when you tap scan, to photograph the document you choose.","La fotocamera viene usata solo quando tocchi scansiona, per fotografare il documento che scegli."),
("scannerUseCamera","تصوير بالكاميرا","Use the camera","Usa la fotocamera"),
("scannerUseGallery","اختيار صورة من الجهاز","Choose a photo","Scegli una foto"),
("scannerPasteText","لصق النص يدويًا","Paste the text instead","Incolla il testo"),
("scannerNoCamera","الكاميرا غير متاحة على هذا الجهاز. يمكنك لصق نص المستند.","The camera is not available on this device. You can paste the document text.","La fotocamera non è disponibile su questo dispositivo. Puoi incollare il testo del documento."),
("scannerPermissionDenied","لم يُسمح بالوصول إلى الكاميرا أو الصور. يمكنك السماح به من إعدادات الجهاز، أو لصق النص يدويًا.","Access to the camera or photos was not allowed. You can allow it in device settings, or paste the text instead.","L'accesso a fotocamera o foto non è stato consentito. Puoi consentirlo nelle impostazioni o incollare il testo."),
("scannerReviewTitle","راجع قبل الإرسال","Review before sending","Controlla prima di inviare"),
("scannerPreview","معاينة الصورة الملتقطة","Preview of the captured photo","Anteprima della foto acquisita"),
("scannerNoOcr","قراءة النص على الجهاز غير متاحة في هذه النسخة. اكتب أو الصق النص أدناه، أو أرسل الصورة نفسها.","On-device text recognition is not available in this version. Type or paste the text below, or send the photo itself.","Il riconoscimento del testo sul dispositivo non è disponibile in questa versione. Scrivi o incolla il testo qui sotto, oppure invia la foto."),
("scannerTextLabel","نص المستند","Document text","Testo del documento"),
("scannerTextHint","الصق هنا النص الذي تريد شرحه","Paste the text you want explained","Incolla qui il testo da spiegare"),
("scannerSendsText","سيُرسل هذا النص فقط إلى خوادم إكسبا لشرحه.","Only this text will be sent to EXPA servers to be explained.","Solo questo testo verrà inviato ai server EXPA per essere spiegato."),
("scannerSendsImage","ستُرسل هذه الصورة إلى خوادم إكسبا لشرحها.","This photo will be sent to EXPA servers to be explained.","Questa foto verrà inviata ai server EXPA per essere spiegata."),
("scannerNothingToSend","لا يوجد شيء للإرسال بعد.","There is nothing to send yet.","Non c'è ancora nulla da inviare."),
("scannerSend","إرسال للشرح","Send for explanation","Invia per la spiegazione"),
("scannerDiscard","تجاهل وبدء من جديد","Discard and start over","Scarta e ricomincia"),
("scannerBackendUnavailable","خدمة شرح المستندات غير متاحة بعد. حاول لاحقًا.","The document explanation service is not available yet. Please try again later.","Il servizio di spiegazione dei documenti non è ancora disponibile. Riprova più tardi."),
("scannerNoSummary","لم نتمكن من استخراج ملخص.","We could not extract a summary.","Non siamo riusciti a ricavare un riassunto."),
("scannerKeyDates","تواريخ مهمة","Key dates","Date importanti"),
("scannerCreateReminder","إضافة وثيقة وتذكير","Add a document and reminder","Aggiungi un documento e un promemoria"),
("scannerActions","الخطوات المقترحة","Suggested actions","Azioni suggerite"),
("scannerDefaultDisclaimer","هذا شرح آلي عام وليس استشارة قانونية أو رسمية. تأكد من الجهة المرسلة للخطاب.","This is a general automated explanation, not legal or official advice. Check with the sender of the letter.","Questa è una spiegazione automatica generale, non una consulenza legale o ufficiale. Verifica con il mittente della lettera."),
("scannerAnother","شرح مستند آخر","Explain another document","Spiega un altro documento"),
]
import glob, importlib, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
for _f in sorted(glob.glob(os.path.join(os.path.dirname(os.path.abspath(__file__)), "strings_x_*.py"))):
    S += importlib.import_module(os.path.basename(_f)[:-3]).S
ph = re.compile(r"\{(\w+)\}")
S_EN = {r[0]: r[2] for r in S}
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
for i, lang in enumerate(["ar","en","it"], start=1):
    d = {"@@locale": lang}
    for row in S:
        k, v = row[0], row[i]
        d[k] = v
        if lang == "ar":
            names = ph.findall(S_EN[k])
            if names:
                d["@"+k] = {"placeholders": {n: {"type": "String"} for n in names}}
    keys = {r[0] for r in S}
    assert len(keys) == len(S), "duplicate keys"
    for r in S:
        assert set(ph.findall(r[1])) == set(ph.findall(r[2])) == set(ph.findall(r[3])), r[0]
    json.dump(d, open(f"lib/l10n/app_{lang}.arb","w"), ensure_ascii=False, indent=2)
print(len(S), "keys")
