S = [
("patenteWeakTitle","مواضيعي الضعيفة","My weak topics","I miei argomenti deboli"),
("patenteWeakIntro","المواضيع التي تقل دقتك فيها عن {threshold}% بعد {min} إجابات على الأقل.","Topics where your accuracy is below {threshold}% after at least {min} answers.","Argomenti in cui la tua precisione è sotto il {threshold}% dopo almeno {min} risposte."),
("patenteWeakNone","لا توجد مواضيع ضعيفة حتى الآن. حلّ مزيدًا من الأسئلة ليظهر التحليل.","No weak topics yet. Answer more questions so the analysis can appear.","Ancora nessun argomento debole. Rispondi a più domande per vedere l'analisi."),
("patenteWeakList","مواضيع تحتاج مراجعة","Topics to review","Argomenti da ripassare"),
("patenteUntouched","مواضيع لم تجرّبها بعد","Topics you have not tried yet","Argomenti non ancora provati"),
("patenteRecommended","موضوع مقترح للبدء: {t}","Suggested topic to start with: {t}","Argomento consigliato da cui iniziare: {t}"),
("patenteTopicAccuracy","الدقة {acc}% ({correct} من {answered})","Accuracy {acc}% ({correct} of {answered})","Precisione {acc}% ({correct} su {answered})"),
("patentePracticeTopic","تدرّب على هذا الموضوع","Practise this topic","Esercitati su questo argomento"),
("patentePracticeAllWeak","تدرّب على كل المواضيع الضعيفة","Practise all weak topics","Esercitati su tutti gli argomenti deboli"),
("patenteNoWeakToPractice","لا توجد مواضيع ضعيفة للتدرّب عليها بعد.","There are no weak topics to practise yet.","Non ci sono ancora argomenti deboli su cui esercitarsi."),
("patenteNotEnoughQuestions","لا توجد أسئلة كافية لهذه الجلسة بعد.","There are not enough questions for this session yet.","Non ci sono ancora abbastanza domande per questa sessione."),
("patenteWeakOpen","تحليل المواضيع الضعيفة","Weak-topic analysis","Analisi degli argomenti deboli"),
("patenteGlossaryOpen","قاموس مصطلحات الرخصة (إيطالي ← عربي)","Driving glossary (Italian to Arabic)","Glossario della patente (italiano - arabo)"),
("patenteGlossaryTitle","قاموس الباتنتي","Patente glossary","Glossario patente"),
("patenteGlossaryEmpty","لا توجد مصطلحات منشورة بعد.","No glossary terms are published yet.","Non ci sono ancora termini pubblicati."),
("patenteCheck","تحقق من إجابتي","Check my answer","Controlla la mia risposta"),
("patenteCheckPick","اختر صحيح أو خطأ أولًا.","Choose true or false first.","Scegli prima vero o falso."),
("patenteFeedbackCorrect","إجابة صحيحة","Correct","Corretto"),
("patenteFeedbackWrong","إجابة غير صحيحة. الجواب الصحيح: {a}","Not correct. The right answer: {a}","Non corretto. La risposta giusta: {a}"),
("patenteExplanationIt","الشرح بالإيطالية","Explanation in Italian","Spiegazione in italiano"),
("patenteExplanationAr","الشرح بالعربية","Explanation in Arabic","Spiegazione in arabo"),
("patenteExplanationEn","الشرح بالإنجليزية","Explanation in English","Spiegazione in inglese"),
]
