S = [
("tfChallengeTitle","التحقق بخطوتين","Two-step verification","Verifica in due passaggi"),
("tfChallengeSubtitle","أدخل الرمز المكوّن من 6 أرقام من تطبيق المصادقة.","Enter the 6-digit code from your authenticator app.","Inserisci il codice a 6 cifre della tua app di autenticazione."),
("tfCodeLabel","رمز التحقق","Verification code","Codice di verifica"),
("tfCodeInvalid","أدخل رمزًا من 6 أرقام.","Enter a 6-digit code.","Inserisci un codice a 6 cifre."),
("tfVerify","تحقق","Verify","Verifica"),
("tfUseRecovery","استخدام رمز استرداد","Use a recovery code","Usa un codice di recupero"),
("tfUseApp","استخدام رمز التطبيق","Use the authenticator code","Usa il codice dell'app"),
("tfRecoveryLabel","رمز الاسترداد","Recovery code","Codice di recupero"),
("tfRecoveryHint","بالشكل xxxxx-xxxxx، ويعمل مرة واحدة فقط.","Format xxxxx-xxxxx; it works only once.","Formato xxxxx-xxxxx; funziona una sola volta."),
("tfBackToLogin","العودة إلى تسجيل الدخول","Back to sign in","Torna all'accesso"),
("tfChallengeExpired","انتهت صلاحية خطوة التحقق. سجّل الدخول من جديد.","This verification step has expired. Please sign in again.","Questo passaggio di verifica è scaduto. Accedi di nuovo."),
("tfInvalidCode","الرمز غير صحيح أو سبق استخدامه. حاول مرة أخرى.","The code is incorrect or was already used. Try again.","Il codice non è corretto o è già stato usato. Riprova."),
("tfTooManyAttempts","محاولات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.","Too many attempts. Wait a while and try again.","Troppi tentativi. Attendi un po' e riprova."),
("tfSetupRequired","يتطلب حسابك تفعيل التحقق بخطوتين. افتح حسابي ثم الأمان لتفعيله.","Your account must use two-step verification. Open Profile, then Security, to turn it on.","Il tuo account deve usare la verifica in due passaggi. Apri Profilo, poi Sicurezza, per attivarla."),
("tfSecurityTitle","الأمان","Security","Sicurezza"),
("tfSecuritySubtitle","التحقق بخطوتين ورموز الاسترداد","Two-step verification and recovery codes","Verifica in due passaggi e codici di recupero"),
("tfStatusOn","التحقق بخطوتين مفعّل","Two-step verification is on","La verifica in due passaggi è attiva"),
("tfStatusOff","التحقق بخطوتين غير مفعّل","Two-step verification is off","La verifica in due passaggi non è attiva"),
("tfIntro","يضيف رمزًا من تطبيق مصادقة عند تسجيل الدخول لحماية حسابك.","Adds a code from an authenticator app when you sign in, to protect your account.","Aggiunge un codice da un'app di autenticazione all'accesso per proteggere il tuo account."),
("tfRecoveryRemaining","رموز الاسترداد المتبقية: {n}","Recovery codes left: {n}","Codici di recupero rimasti: {n}"),
("tfRequiredNotice","هذا الحساب يتطلب التحقق بخطوتين.","This account is required to use two-step verification.","Questo account deve usare la verifica in due passaggi."),
("tfEnable","تفعيل التحقق بخطوتين","Turn on two-step verification","Attiva la verifica in due passaggi"),
("tfSetupStep1","1. أضف هذا المفتاح إلى تطبيق المصادقة (يمكنك مسح الرمز أو نسخ المفتاح).","1. Add this key to your authenticator app (scan the code or copy the key).","1. Aggiungi questa chiave alla tua app di autenticazione (inquadra il codice o copia la chiave)."),
("tfSetupStep2","2. أدخل الرمز المكوّن من 6 أرقام الذي يظهر في التطبيق.","2. Enter the 6-digit code shown in the app.","2. Inserisci il codice a 6 cifre mostrato nell'app."),
("tfQrLabel","رمز QR لإعداد تطبيق المصادقة","QR code to set up your authenticator app","Codice QR per configurare l'app di autenticazione"),
("tfSecretLabel","مفتاح الإعداد","Setup key","Chiave di configurazione"),
("tfCopy","نسخ","Copy","Copia"),
("tfCopySecret","نسخ المفتاح","Copy key","Copia la chiave"),
("tfCopyUri","نسخ رابط otpauth","Copy otpauth link","Copia il link otpauth"),
("tfCopied","تم النسخ.","Copied.","Copiato."),
("tfConfirm","تأكيد وتفعيل","Confirm and turn on","Conferma e attiva"),
("tfCancelSetup","إلغاء الإعداد","Cancel setup","Annulla la configurazione"),
("tfCodesTitle","رموز الاسترداد","Recovery codes","Codici di recupero"),
("tfCodesWarning","احفظ هذه الرموز الآن في مكان آمن. لن تظهر مرة أخرى، ويعمل كل رمز مرة واحدة فقط إذا فقدت هاتفك.","Save these codes now in a safe place. They will not be shown again, and each works only once if you lose your phone.","Salva questi codici ora in un luogo sicuro. Non verranno mostrati di nuovo e ognuno funziona una sola volta se perdi il telefono."),
("tfCopyCodes","نسخ كل الرموز","Copy all codes","Copia tutti i codici"),
("tfCodesSaved","حفظت الرموز","I have saved them","Li ho salvati"),
("tfDisable","إيقاف التحقق بخطوتين","Turn off two-step verification","Disattiva la verifica in due passaggi"),
("tfRegenerate","إنشاء رموز استرداد جديدة","Generate new recovery codes","Genera nuovi codici di recupero"),
("tfRegenerateHint","الرموز الجديدة تلغي القديمة.","New codes replace the old ones.","I nuovi codici sostituiscono i vecchi."),
("tfConfirmIdentity","تأكيد هويتك","Confirm it is you","Conferma la tua identità"),
("tfPasswordWrong","كلمة المرور غير صحيحة.","The password is incorrect.","La password non è corretta."),
("tfDisabledDone","تم إيقاف التحقق بخطوتين.","Two-step verification is off.","La verifica in due passaggi è stata disattivata."),
("tfAlreadyEnabled","التحقق بخطوتين مفعّل بالفعل.","Two-step verification is already on.","La verifica in due passaggi è già attiva."),
("tfLoadFailed","تعذّر تحميل حالة الأمان.","Could not load the security status.","Impossibile caricare lo stato di sicurezza."),
]
S += [
("patenteExplainQuestion","اشرح لي هذا السؤال","Explain this question","Spiegami questa domanda"),
("patenteQuestionPrompt","اشرح لي سؤال الباتنتي هذا بشكل مبسّط: {statement}","Explain this driving-licence question simply: {statement}","Spiegami in modo semplice questa domanda della patente: {statement}"),
]
