S = [
("recoTitle","مقترحات لك","Recommended for you","Consigliati per te"),
("recoGuides","أدلة مقترحة","Guides","Guide"),
("recoLessons","دروس مقترحة","Lessons","Lezioni"),
("recoServices","خدمات مقترحة","Services","Servizi"),
("recoReminders","تذكيرات مقترحة","Reminders","Promemoria"),
("recoWhy","السبب","Why","Perché"),
("recoThirdParty","خدمة من طرف ثالث، لا تضمنها EXPA","Third-party service, not guaranteed by EXPA","Servizio di terzi, non garantito da EXPA"),
("recoPersonalized","هذه المقترحات مبنية على ملفك وأهدافك بموافقتك.","These suggestions use your profile and goals, with your consent.","Questi suggerimenti usano il tuo profilo e i tuoi obiettivi, con il tuo consenso."),
("recoNotPersonalized","مقترحات عامة فقط، لأن التخصيص غير مفعّل. فعّل موافقة التخصيص للحصول على مقترحات أدق.","General suggestions only, because personalization is off. Turn on the personalization consent for better suggestions.","Solo suggerimenti generali, perché la personalizzazione è disattivata. Attiva il consenso alla personalizzazione per suggerimenti migliori."),
("recoManageConsent","إدارة الموافقات","Manage consents","Gestisci i consensi"),
("recoEmpty","لا توجد مقترحات الآن. أكمل ملفك الشخصي أو أضف مستنداتك.","No suggestions right now. Complete your profile or add your documents.","Nessun suggerimento al momento. Completa il profilo o aggiungi i documenti."),
("netTitle","حاسبة الراتب الصافي","Net salary estimator","Stima dello stipendio netto"),
("netIntro","قدّر الراتب الصافي من الإجمالي السنوي. الحساب تقريبي ولا يُحفظ شيء.","Estimate net pay from the gross annual salary. It is approximate and nothing is stored.","Stima lo stipendio netto dal lordo annuo. È indicativa e non viene salvato nulla."),
("netGross","الراتب الإجمالي السنوي (RAL)","Gross annual salary (RAL)","Retribuzione annua lorda (RAL)"),
("netInvalid","أدخل رقمًا صحيحًا بين 0 و 10,000,000.","Enter a valid number between 0 and 10,000,000.","Inserisci un numero valido tra 0 e 10.000.000."),
("netMonths","عدد الرواتب في السنة","Salaries per year","Mensilità all'anno"),
("netCalculate","احسب","Calculate","Calcola"),
("netUnavailableTitle","التقدير غير متاح","Estimate not available","Stima non disponibile"),
("netUnavailable","لم تُنشر بعد جداول ضرائب موثّقة، ولا تخمّن EXPA الأرقام.","No verified tax tables have been published yet, and EXPA does not guess figures.","Non sono ancora state pubblicate tabelle fiscali verificate e EXPA non inventa cifre."),
("netMonthly","الصافي الشهري التقريبي","Estimated monthly net","Netto mensile stimato"),
("netAnnual","الصافي السنوي","Annual net","Netto annuo"),
("netGrossLine","الإجمالي السنوي","Annual gross","Lordo annuo"),
("netContributions","الاشتراكات","Contributions","Contributi"),
("netDeduction","خصم ثابت","Flat deduction","Detrazione fissa"),
("netTaxable","الدخل الخاضع للضريبة","Taxable income","Reddito imponibile"),
("netIncomeTax","ضريبة الدخل","Income tax","Imposta sul reddito"),
("netTable","الجدول المستخدم: {name} ({year})","Table used: {name} ({year})","Tabella usata: {name} ({year})"),
("netDisclaimer","تقدير للاسترشاد فقط وليس كشف راتب أو نصيحة ضريبية. اسأل commercialista أو CAF أو Patronato.","An estimate for orientation only, not a payslip or tax advice. Ask a commercialista, CAF or Patronato.","Stima solo orientativa, non una busta paga né una consulenza fiscale. Chiedi a un commercialista, CAF o Patronato."),
("travelTitle","متطلبات السفر","Travel requirements","Requisiti di viaggio"),
("travelIntro","اعرف المتطلبات الموثّقة للسفر بين بلدين حسب جنسيتك.","Look up the verified requirements for travelling between two countries for your nationality.","Cerca i requisiti verificati per viaggiare tra due paesi in base alla tua nazionalità."),
("travelPrivacy","تُرسل البلدان فقط للبحث ولا تُحفظ ولا تُقرأ من ملفك.","Only the two countries are sent for the lookup; they are not stored or read from your profile.","Per la ricerca vengono inviati solo i due paesi; non sono salvati né letti dal tuo profilo."),
("travelNationality","الجنسية (رمز من حرفين)","Nationality (2-letter code)","Nazionalità (codice di 2 lettere)"),
("travelDestination","وجهة السفر (رمز من حرفين)","Destination (2-letter code)","Destinazione (codice di 2 lettere)"),
("travelCodeHelp","رمز ISO مثل EG أو IT","ISO code such as EG or IT","Codice ISO come EG o IT"),
("travelCodeInvalid","أدخل حرفين لاتينيين.","Enter two Latin letters.","Inserisci due lettere latine."),
("travelSearch","بحث","Search","Cerca"),
("travelNoneTitle","لا توجد معلومات موثّقة","No verified information","Nessuna informazione verificata"),
("travelNone","ليست لدينا معلومات موثّقة لهذه الحالة. هذا لا يعني أن السفر مسموح، تحقق من المصدر الرسمي.","We have no verified information for this case. This does not mean travel is allowed: check the official source.","Non abbiamo informazioni verificate per questo caso. Non significa che il viaggio sia consentito: controlla la fonte ufficiale."),
("travelDisclaimer","معلومات عامة للاسترشاد وقد تتغير. تحقق دائمًا من المصدر الرسمي قبل السفر.","General information that may change. Always check the official source before travelling.","Informazioni generali che possono cambiare. Controlla sempre la fonte ufficiale prima di viaggiare."),
("scannerRedactTitle","قد يحتوي النص على بيانات حساسة","The text may contain sensitive data","Il testo potrebbe contenere dati sensibili"),
("scannerRedactBody","وجدنا ما يشبه رقم IBAN أو الرقم الضريبي أو بريدًا أو رقمًا طويلًا. يمكنك حذفه من الحقل قبل الإرسال؛ الشرح لا يحتاجه عادةً.","We found something that looks like an IBAN, tax code, e-mail or long number. You can delete it in the field before sending; the explanation usually does not need it.","Abbiamo trovato qualcosa che sembra un IBAN, un codice fiscale, un'e-mail o un numero lungo. Puoi cancellarlo nel campo prima di inviare; la spiegazione di solito non ne ha bisogno."),
("scannerRedactGeneral","نصيحة: احذف أرقام الحسابات والبيانات الشخصية غير اللازمة قبل الإرسال.","Tip: remove account numbers and unneeded personal data before sending.","Suggerimento: elimina numeri di conto e dati personali non necessari prima di inviare."),
("notificationsDelete","حذف الإشعار","Delete notification","Elimina notifica"),
("notificationsSettings","إعدادات الإشعارات","Notification settings","Impostazioni notifiche"),
("patenteTeacherTitle","معلّم الباتنتي بالذكاء الاصطناعي","AI Patente teacher","Insegnante di patente con IA"),
("patenteTeacherIntro","اطلب شرحًا مبسّطًا لهذا الموضوع. الإجابة مبنية على محتوى منشور مع ذكر المصادر.","Ask for a simple explanation of this topic. The answer is grounded in published content, with sources.","Chiedi una spiegazione semplice di questo argomento. La risposta si basa su contenuti pubblicati, con le fonti."),
("patenteTeacherAsk","اشرح لي هذا الموضوع","Explain this topic to me","Spiegami questo argomento"),
("patenteTeacherPrompt","اشرح لي موضوع الباتنتي هذا بشكل مبسّط: {title}","Explain this driving-licence topic simply: {title}","Spiegami in modo semplice questo argomento della patente: {title}"),
("patenteTeacherOffline","أنت غير متصل: المعلّم يحتاج إلى الإنترنت.","You are offline: the teacher needs internet.","Sei offline: l'insegnante richiede internet."),
]
