S = [
("practiceTitle","تدريب الإيطالية","Italian practice","Pratica d'italiano"),
("practiceOpen","تدريب: مفردات وتمارين ومراجعة","Practice: vocabulary, exercises, review","Pratica: vocabolario, esercizi, ripasso"),
("practiceNotReviewed","هذا المحتوى لم يراجعه معلّم بعد. قد يحتوي على أخطاء.","This content has not been reviewed by a teacher yet. It may contain mistakes.","Questo contenuto non è ancora stato rivisto da un insegnante. Può contenere errori."),
("practiceReviewed","راجعه معلّم","Reviewed by a teacher","Rivisto da un insegnante"),
("practiceReviewedOn","راجعه معلّم في {date}","Reviewed by a teacher on {date}","Rivisto da un insegnante il {date}"),
("practiceDue","بطاقات مستحقة الآن: {n}","Cards due now: {n}","Schede da ripassare ora: {n}"),
("practiceMastered","بطاقات متقنة: {n}","Mastered cards: {n}","Schede padroneggiate: {n}"),
("practiceLearning","بطاقات قيد التعلّم: {n}","Cards in learning: {n}","Schede in apprendimento: {n}"),
("practiceAccuracy","الدقة: {n}%","Accuracy: {n}%","Precisione: {n}%"),
("practiceAttempts","محاولات التمارين: {n}","Exercise attempts: {n}","Tentativi negli esercizi: {n}"),
("practiceReviewCards","مراجعة البطاقات (تكرار متباعد)","Review cards (spaced repetition)","Ripasso schede (ripetizione dilazionata)"),
("practiceVocabulary","المفردات","Vocabulary","Vocabolario"),
("practiceExercises","التمارين","Exercises","Esercizi"),
("practiceScenarios","مواقف من الحياة اليومية","Real-life scenarios","Situazioni di vita reale"),
("vocabEmpty","لا توجد مفردات منشورة بعد.","No vocabulary is published yet.","Non c'è ancora vocabolario pubblicato."),
("exercisesEmpty","لا توجد تمارين منشورة بعد.","No exercises are published yet.","Non ci sono ancora esercizi pubblicati."),
("scenariosEmpty","لا توجد مواقف متاحة بعد.","No scenarios are available yet.","Non ci sono ancora situazioni disponibili."),
("scenarioCounts","دروس: {lessons} · مفردات: {vocab} · تمارين: {exercises}","Lessons: {lessons} · Vocabulary: {vocab} · Exercises: {exercises}","Lezioni: {lessons} · Vocaboli: {vocab} · Esercizi: {exercises}"),
("scenarioLessons","دروس هذا الموقف","Lessons for this scenario","Lezioni di questa situazione"),
("vocabExample","مثال","Example","Esempio"),
("vocabBox","مستوى الحفظ: {n}","Memory box: {n}","Livello di memoria: {n}"),
("vocabAudioNote","يوجد تسجيل صوتي لهذه الكلمة، لكن التشغيل غير متاح في هذه النسخة من التطبيق.","A recording exists for this word, but playback is not available in this app version.","Esiste una registrazione per questa parola, ma la riproduzione non è disponibile in questa versione dell'app."),
("reviewTitle","مراجعة البطاقات","Card review","Ripasso schede"),
("reviewEmpty","لا توجد بطاقات للمراجعة الآن. عُد لاحقًا.","No cards to review right now. Come back later.","Nessuna scheda da ripassare ora. Torna più tardi."),
("reviewShow","إظهار المعنى","Show meaning","Mostra significato"),
("reviewKnew","كنت أعرفها","I knew it","Lo sapevo"),
("reviewNotYet","ليس بعد","Not yet","Non ancora"),
("reviewNew","كلمة جديدة","New word","Parola nuova"),
("reviewProgress","بطاقة {i} من {n}","Card {i} of {n}","Scheda {i} di {n}"),
("reviewDone","أحسنت! أنهيت مراجعة اليوم: {n} بطاقة.","Well done! You finished today's review: {n} cards.","Ottimo! Hai finito il ripasso di oggi: {n} schede."),
("reviewSaveFailed","تعذّر حفظ إجابتك. حاول مرة أخرى.","Your answer could not be saved. Try again.","Non è stato possibile salvare la risposta. Riprova."),
("exTypeAll","كل الأنواع","All types","Tutti i tipi"),
("exTypeMultiple","اختيار من متعدد","Multiple choice","Scelta multipla"),
("exTypeListening","استماع","Listening","Ascolto"),
("exTypeFill","املأ الفراغ","Fill in the blank","Completa lo spazio"),
("exTypeMatch","مطابقة","Match","Abbina"),
("exCheck","تحقق من إجابتي","Check my answer","Controlla la risposta"),
("exCorrect","إجابة صحيحة","Correct","Corretto"),
("exWrong","إجابة غير صحيحة","Not correct","Non corretto"),
("exCorrectAnswer","الإجابة الصحيحة: {a}","Correct answer: {a}","Risposta corretta: {a}"),
("exAnswerHint","اكتب الكلمة الناقصة","Type the missing word","Scrivi la parola mancante"),
("exMatchChoose","اختر","Choose","Scegli"),
("exMatchAll","طابق كل العناصر قبل التحقق.","Match every item before checking.","Abbina tutti gli elementi prima di controllare."),
("exNoAudio","لا يوجد تسجيل صوتي لهذا التمرين بعد. اقرأ الخيارات بنفسك.","There is no recording for this exercise yet. Read the choices yourself.","Non c'è ancora una registrazione per questo esercizio. Leggi tu le opzioni."),
("exAudioUnsupported","التسجيل الصوتي غير متاح للتشغيل في هذه النسخة. اقرأ الخيارات بنفسك.","The recording cannot be played in this app version. Read the choices yourself.","La registrazione non può essere riprodotta in questa versione. Leggi tu le opzioni."),
("exTryAnother","تمرين آخر","Another exercise","Un altro esercizio"),
("exChooseOne","اختر إجابة أولًا.","Choose an answer first.","Scegli prima una risposta."),
("exTypeFirst","اكتب إجابتك أولًا.","Type your answer first.","Scrivi prima la tua risposta."),
]
