S = [
("exploreCommunity","المجتمع (أسئلة وأجوبة)","Community Q&A","Community (domande e risposte)"),
("communityTitle","مجتمع إكسبا","EXPA community","Community EXPA"),
("communityNoticeFallback","إجابات المجتمع من أعضاء عاديين وليست معلومات رسمية ولا موثّقة. تحقق من المصادر الرسمية.","Community answers come from ordinary members and are not official or verified information. Check official sources.","Le risposte della community vengono da utenti comuni e non sono informazioni ufficiali o verificate. Controlla le fonti ufficiali."),
("communityEmpty","لا توجد أسئلة بعد.","No questions yet.","Ancora nessuna domanda."),
("communityMineOnly","أسئلتي فقط","My questions only","Solo le mie domande"),
("communityAskOpen","اطرح سؤالًا","Ask a question","Fai una domanda"),
("communityQuestionTitle","عنوان السؤال","Question title","Titolo della domanda"),
("communityQuestionBody","تفاصيل السؤال","Question details","Dettagli della domanda"),
("communityTopic","الموضوع","Topic","Argomento"),
("communityNoTopic","بدون موضوع","No topic","Nessun argomento"),
("communityPost","نشر","Post","Pubblica"),
("communityPostedPending","استلمنا مشاركتك وقد تنتظر المراجعة قبل ظهورها للآخرين.","We received your post; it may wait for moderation before others can see it.","Abbiamo ricevuto il tuo contributo: potrebbe attendere la moderazione prima di essere visibile agli altri."),
("communityAnswers","الأجوبة ({n})","Answers ({n})","Risposte ({n})"),
("communityNoAnswers","لا توجد أجوبة بعد.","No answers yet.","Ancora nessuna risposta."),
("communityWriteAnswer","اكتب جوابًا","Write an answer","Scrivi una risposta"),
("communityAccepted","الجواب المعتمد من صاحب السؤال","Answer accepted by the asker","Risposta accettata da chi ha chiesto"),
("communityOfficialGuide","الدليل الرسمي المرتبط","Linked official guide","Guida ufficiale collegata"),
("communityMine","مشاركتي","My post","Il mio contributo"),
("communityPendingStatus","بانتظار المراجعة","Pending moderation","In attesa di moderazione"),
("communityHiddenStatus","مخفي من المشرفين","Hidden by moderators","Nascosto dai moderatori"),
("communityDelete","حذف سؤالي","Delete my question","Elimina la mia domanda"),
("communityDeleted","حُذف السؤال.","Question deleted.","Domanda eliminata."),
("communityComments","التعليقات ({n})","Comments ({n})","Commenti ({n})"),
]
