S = [
("provTitle","بوابة مزوّد الخدمة","Provider portal","Portale fornitore"),
("provBecome","كن مزوّد خدمة","Become a provider","Diventa fornitore"),
("provApplyTitle","التقديم كمزوّد خدمة","Apply as a provider","Candidati come fornitore"),
("provApplyIntro","أنشئ قائمة خدماتك. تبقى مسودة خاصة حتى يراجعها فريق EXPA وينشرها.","Create your listing. It stays a private draft until the EXPA team reviews and publishes it.","Crea la tua scheda. Resta una bozza privata finché il team EXPA non la verifica e la pubblica."),
("provApplyNotice","النشر لا يعني توصية أو ضمانًا من EXPA. تظهر شارة التوثيق فقط بعد مراجعة المستندات.","Publication is not an endorsement or guarantee by EXPA. A verified badge appears only after documents are reviewed.","La pubblicazione non è una raccomandazione né una garanzia di EXPA. Il badge verificato compare solo dopo la revisione dei documenti."),
("provApply","تقديم الطلب","Apply","Invia candidatura"),
("provExists","لديك قائمة مزوّد بالفعل.","You already have a provider listing.","Hai già una scheda fornitore."),
("provRequiredFields","الاسم والفئة والعنوان الرئيسي مطلوبة.","Name, category and headline are required.","Nome, categoria e titolo sono obbligatori."),
("provDisplayName","الاسم المعروض","Display name","Nome visualizzato"),
("provCategory","الفئة","Category","Categoria"),
("provHeadline","العنوان الرئيسي","Headline","Titolo"),
("provLanguageNote","يُحفظ بلغة التطبيق الحالية. غيّر اللغة لإضافة ترجمة أخرى.","Saved in the current app language. Switch language to add another translation.","Salvato nella lingua corrente dell'app. Cambia lingua per aggiungere un'altra traduzione."),
("provDescription","الوصف","Description","Descrizione"),
("provContactEmail","بريد التواصل","Contact e-mail","E-mail di contatto"),
("provContactPhone","هاتف التواصل","Contact phone","Telefono di contatto"),
("provWebsite","الموقع الإلكتروني","Website","Sito web"),
("provServesOnline","يقدّم الخدمة عن بُعد","Serves online","Servizio online"),
("provTabProfile","الملف","Profile","Profilo"),
("provTabVerification","التوثيق","Verification","Verifica"),
("provTabLeads","الطلبات","Requests","Richieste"),
("provTabReviews","التقييمات","Reviews","Recensioni"),
("provStatusDraft","مسودة","Draft","Bozza"),
("provStatusReview","قيد المراجعة","In review","In revisione"),
("provStatusApproved","معتمد","Approved","Approvato"),
("provStatusPublished","منشور","Published","Pubblicato"),
("provStatusArchived","مؤرشف","Archived","Archiviato"),
("provVerified","موثّق","Verified","Verificato"),
("provVerifPending","التوثيق قيد المراجعة","Verification pending","Verifica in corso"),
("provVerifRejected","التوثيق مرفوض","Verification rejected","Verifica rifiutata"),
("provVerifExpired","انتهى التوثيق","Verification expired","Verifica scaduta"),
("provVerifNone","غير موثّق","Not verified","Non verificato"),
("provPendingChanges","تعديلات بانتظار الموافقة","Changes awaiting approval","Modifiche in attesa di approvazione"),
("provPublishedEditNote","القائمة منشورة: تظهر تعديلاتك بعد موافقة المشرف، وتبقى النسخة الحالية كما هي.","The listing is live: your edits appear after an admin approves them; the current version stays unchanged.","La scheda è pubblicata: le modifiche compaiono dopo l'approvazione di un amministratore; la versione attuale resta invariata."),
("provProblems","ما ينقص قبل التقديم","Missing before submitting","Cosa manca prima dell'invio"),
("provListingIncomplete","القائمة غير مكتملة بعد. أكملها ثم أعد المحاولة.","The listing is not complete yet. Complete it and try again.","La scheda non è ancora completa. Completala e riprova."),
("provSave","حفظ التعديلات","Save changes","Salva modifiche"),
("provSaved","تم الحفظ.","Saved.","Salvato."),
("provSavedPendingApproval","تم إرسال التعديلات للموافقة.","Your changes were sent for approval.","Le modifiche sono state inviate per approvazione."),
("provSubmit","إرسال للمراجعة","Submit for review","Invia in revisione"),
("provSubmitted","تم الإرسال للمراجعة.","Submitted for review.","Inviato in revisione."),
("provServicesWebOnly","تعديل الخدمات والمناطق متاح حاليًا على موقع الويب فقط.","Editing services and areas is available on the website only for now.","La modifica di servizi e aree è per ora disponibile solo sul sito web."),
("provVerifIntro","ارفع مستندات تثبت نشاطك. يراجعها فريق EXPA فقط ولا تظهر للمستخدمين.","Upload documents that prove your business. Only the EXPA team reviews them; users never see them.","Carica documenti che dimostrano la tua attività. Solo il team EXPA li esamina; gli utenti non li vedono."),
("provEvidenceNote","تُخزَّن المستندات مشفّرة وتُقرأ عبر لوحة الإدارة فقط. ارفع الصور اللازمة فقط.","Documents are stored encrypted and read through the admin panel only. Upload only what is needed.","I documenti sono archiviati cifrati e letti solo dal pannello di amministrazione. Carica solo il necessario."),
("provEvidenceTitle","مستندات التوثيق","Verification documents","Documenti di verifica"),
("provEvidenceNone","لم ترفع أي مستند بعد.","No documents uploaded yet.","Nessun documento caricato."),
("provEvidenceAdd","إضافة صورة من المعرض","Add a photo from the gallery","Aggiungi una foto dalla galleria"),
("provEvidenceDelete","حذف المستند","Delete document","Elimina documento"),
("provEvidenceUploaded","تم رفع المستند.","Document uploaded.","Documento caricato."),
("provEvidencePdfWeb","ملفات PDF تُرفع من موقع الويب. الحد الأقصى 5 ملفات.","PDF files are uploaded on the website. Maximum 5 files.","I PDF si caricano dal sito web. Massimo 5 file."),
("provVerifRequest","طلب التوثيق","Request verification","Richiedi la verifica"),
("provVerifRequested","تم إرسال طلب التوثيق.","Verification requested.","Verifica richiesta."),
("provLeadsPrivacy","بيانات التواصل هنا أعطاها المستخدم بموافقته لهذا الطلب فقط. استخدمها للرد عليه فقط.","The contact details here were given by the user, with consent, for this request only. Use them only to reply.","I contatti qui sono stati forniti dall'utente, con consenso, solo per questa richiesta. Usali solo per rispondere."),
("provLeadsEmpty","لا توجد طلبات بعد.","No requests yet.","Nessuna richiesta per ora."),
("provLeadNew","جديد","New","Nuova"),
("provLeadSeen","تمت رؤيته","Seen","Vista"),
("provLeadClosed","مغلق","Closed","Chiusa"),
("provLeadMarkSeen","تمييز كمقروء","Mark as seen","Segna come vista"),
("provLeadClose","إغلاق الطلب","Close request","Chiudi richiesta"),
("provReviewsEmpty","لا توجد تقييمات معتمدة بعد.","No approved reviews yet.","Nessuna recensione approvata per ora."),
("provReply","رد","Reply","Rispondi"),
("provReplyEdit","تعديل الرد","Edit reply","Modifica risposta"),
("provReplyTitle","الرد على التقييم","Reply to review","Rispondi alla recensione"),
("provReplyNote","يظهر ردّك بعد موافقة المشرف.","Your reply appears after an admin approves it.","La tua risposta compare dopo l'approvazione di un amministratore."),
("provReplySend","إرسال الرد","Send reply","Invia risposta"),
("provReplySent","تم إرسال الرد للمراجعة.","Reply sent for review.","Risposta inviata in revisione."),
("provReplyPending","الرد بانتظار الموافقة","Reply awaiting approval","Risposta in attesa di approvazione"),
("provReplyPublished","الرد منشور","Reply published","Risposta pubblicata"),
]
