S = [
("exploreArticles","المقالات","Articles","Articoli"),
("exploreCities","المدن","Cities","Città"),
("exploreServices","مزوّدو الخدمات","Service providers","Fornitori di servizi"),
("exploreLegal","الوثائق القانونية","Legal documents","Documenti legali"),
("articlesTitle","المقالات","Articles","Articoli"),
("articlesEmpty","لا توجد مقالات منشورة بعد.","No articles are published yet.","Non ci sono ancora articoli pubblicati."),
("articleEditorial","مقال تحريري — ليس مصدرًا رسميًا","Editorial article, not an official source","Articolo editoriale, non una fonte ufficiale"),
("articleRelatedGuides","أدلة ذات صلة","Related guides","Guide correlate"),
("articleRelatedArticles","مقالات ذات صلة","Related articles","Articoli correlati"),
("articleTags","الوسوم","Tags","Tag"),
("articleDefaultDisclaimer","محتوى عام للإرشاد وليس استشارة قانونية أو رسمية. تحقق من المصادر الرسمية.","General guidance, not legal or official advice. Check official sources.","Contenuto di orientamento generale, non consulenza legale o ufficiale. Verifica le fonti ufficiali."),
("citiesTitle","المدن","Cities","Città"),
("citiesEmpty","لا توجد ملفات مدن منشورة بعد.","No city profiles are published yet.","Non ci sono ancora profili di città pubblicati."),
("cityOfficial","معلومات رسمية","Official information","Informazioni ufficiali"),
("cityGeneral","إرشاد عام","General guidance","Indicazione generale"),
("cityGuides","أدلة تنطبق على هذه المدينة","Guides for this city","Guide per questa città"),
("cityArticles","مقالات عن المدينة","Articles about the city","Articoli sulla città"),
("cityOffices","عدد المكاتب الحكومية المسجّلة: {n}","Government offices listed: {n}","Uffici pubblici elencati: {n}"),
("cityOfficesOpen","عرض الجهات الحكومية","Browse government offices","Vedi gli uffici pubblici"),
("providersTitle","مزوّدو الخدمات","Service providers","Fornitori di servizi"),
("providersEmpty","لا يوجد مزوّدون مطابقون.","No matching providers.","Nessun fornitore corrispondente."),
("providersVerifiedOnly","الموثّقون فقط","Verified only","Solo verificati"),
("providersThirdParty","خدمة طرف ثالث — غير رسمية","Third-party service, not official","Servizio di terze parti, non ufficiale"),
("providersNoticeFallback","هذا المزوّد طرف ثالث مستقل وليس جهة رسمية ولا تابعًا لإكسبا. تحقق بنفسك قبل الدفع أو مشاركة بياناتك.","This provider is an independent third party, not an official body and not part of EXPA. Check for yourself before paying or sharing your data.","Questo fornitore è una terza parte indipendente, non un ente ufficiale né parte di EXPA. Verifica di persona prima di pagare o condividere i tuoi dati."),
("providersRating","التقييم: {avg} ({count})","Rating: {avg} ({count})","Valutazione: {avg} ({count})"),
("providersNoRatings","لا تقييمات بعد","No ratings yet","Nessuna valutazione"),
("providersContact","بيانات التواصل المعلنة","Published contact details","Contatti pubblicati"),
("providersWebsite","الموقع الإلكتروني","Website","Sito web"),
("providersRequestContact","طلب تواصل","Request contact","Richiedi un contatto"),
("leadTitle","طلب تواصل مع المزوّد","Contact request","Richiesta di contatto"),
("leadIntro","هذا طلب تواصل وليس حجزًا ولا اتفاقًا. سيصل المزوّد رسالتك فقط.","This is a contact request, not a booking or an agreement. The provider only receives your message.","È una richiesta di contatto, non una prenotazione né un accordo. Il fornitore riceve solo il tuo messaggio."),
("leadMessage","رسالتك","Your message","Il tuo messaggio"),
("leadConsent","أوافق على مشاركة بيانات التواصل الخاصة بي (الاسم والبريد) مع هذا المزوّد ليردّ عليّ.","I agree to share my contact details (name and e-mail) with this provider so they can reply.","Acconsento a condividere i miei dati di contatto (nome ed e-mail) con questo fornitore perché possa rispondermi."),
("leadSend","إرسال الطلب","Send request","Invia richiesta"),
("leadSent","أُرسل طلبك. هذا ليس حجزًا مؤكدًا؛ ينتظر ردّ المزوّد.","Your request was sent. It is not a confirmed booking; wait for the provider's reply.","Richiesta inviata. Non è una prenotazione confermata: attendi la risposta del fornitore."),
("leadCooldown","أرسلت طلبًا إلى هذا المزوّد مؤخرًا. انتظر 24 ساعة قبل طلب جديد.","You sent this provider a request recently. Wait 24 hours before sending another.","Hai inviato da poco una richiesta a questo fornitore. Attendi 24 ore prima di inviarne un'altra."),
("leadNeedConsent","يجب الموافقة على مشاركة بيانات التواصل لإرسال الطلب.","You must agree to share your contact details to send the request.","Devi acconsentire alla condivisione dei contatti per inviare la richiesta."),
("leadMessageRequired","اكتب رسالة قصيرة للمزوّد.","Write a short message to the provider.","Scrivi un breve messaggio al fornitore."),
("accountTooNew","حسابك جديد جدًا لهذا الإجراء. حاول لاحقًا.","Your account is too new for this action. Try again later.","Il tuo account è troppo recente per questa azione. Riprova più tardi."),
("reviewsTitle","التقييمات","Reviews","Recensioni"),
("reviewsEmpty","لا توجد تقييمات معتمدة بعد.","No approved reviews yet.","Nessuna recensione approvata."),
("reviewWrite","اكتب تقييمًا","Write a review","Scrivi una recensione"),
("reviewRating","التقييم (1 إلى 5)","Rating (1 to 5)","Valutazione (da 1 a 5)"),
("reviewBody","تعليقك (اختياري)","Your comment (optional)","Il tuo commento (facoltativo)"),
("reviewSend","إرسال التقييم","Submit review","Invia recensione"),
("reviewPending","تم استلام تقييمك وهو بانتظار المراجعة قبل ظهوره.","Your review was received and awaits moderation before it appears.","Recensione ricevuta: sarà moderata prima di comparire."),
("reviewExists","لقد قيّمت هذا المزوّد من قبل.","You have already reviewed this provider.","Hai già recensito questo fornitore."),
("reviewRatingRequired","اختر تقييمًا من 1 إلى 5.","Choose a rating from 1 to 5.","Scegli una valutazione da 1 a 5."),
("reviewReport","إبلاغ","Report","Segnala"),
("reviewReportReason","سبب البلاغ","Reason for the report","Motivo della segnalazione"),
("reviewReportSend","إرسال البلاغ","Send report","Invia segnalazione"),
("reviewReportSent","شكرًا. وصل بلاغك إلى المشرفين.","Thank you. Your report reached the moderators.","Grazie. La segnalazione è arrivata ai moderatori."),
("reviewAlreadyReported","سبق أن أبلغت عن هذا التقييم.","You already reported this review.","Hai già segnalato questa recensione."),
("reasonSpam","محتوى مزعج أو إعلاني","Spam or advertising","Spam o pubblicità"),
("reasonAbuse","إساءة أو لغة مسيئة","Abusive language","Linguaggio offensivo"),
("reasonMisleading","تقييم مضلِّل أو مزيّف","Misleading or fake","Fuorviante o falsa"),
("reasonIllegal","محتوى غير قانوني","Illegal content","Contenuto illegale"),
("reasonPersonalData","يتضمن بيانات شخصية","Contains personal data","Contiene dati personali"),
("reasonOther","سبب آخر","Other","Altro"),
("myRequestsTitle","طلباتي وتقييماتي","My requests and reviews","Le mie richieste e recensioni"),
("myRequestsLeads","طلبات التواصل","Contact requests","Richieste di contatto"),
("myRequestsReviews","تقييماتي","My reviews","Le mie recensioni"),
("myRequestsEmpty","لا توجد طلبات تواصل بعد.","No contact requests yet.","Nessuna richiesta di contatto."),
("myReviewsEmpty","لم تكتب تقييمات بعد.","You have not written any reviews.","Non hai scritto recensioni."),
("myReviewDelete","حذف تقييمي","Delete my review","Elimina la mia recensione"),
("myReviewDeleted","حُذف التقييم.","Review deleted.","Recensione eliminata."),
("statusPending","بانتظار المراجعة","Pending","In attesa"),
("statusApproved","معتمد","Approved","Approvato"),
("statusRejected","مرفوض","Rejected","Rifiutato"),
("statusSeen","اطّلع عليه المزوّد","Seen by the provider","Visto dal fornitore"),
("statusClosed","مغلق","Closed","Chiuso"),
("statusNew","تم الإرسال","Sent","Inviata"),
("providerPortalNote","بوابة المزوّدين متاحة على الموقع فقط وليس في التطبيق.","The provider portal is available on the website only, not in the app.","Il portale fornitori è disponibile solo sul sito web, non nell'app."),
]
