S = [
("billingTitle","الاشتراك والفواتير","Plan and invoices","Piano e fatture"),
("billingUnavailableTitle","المدفوعات غير مفعّلة","Payments are not enabled","I pagamenti non sono attivi"),
("billingUnavailableBody","الدفع غير متاح حاليًا، لذلك لا يمكن شراء خطة أو ترقيتها من التطبيق. خطتك الحالية تعمل كما هي، ولن يُخصم منك أي مبلغ.","Payment is not available yet, so a plan cannot be bought or upgraded in the app. Your current plan keeps working and you will not be charged.","Il pagamento non è ancora disponibile, quindi non si può acquistare o cambiare piano nell'app. Il tuo piano attuale continua a funzionare e non ti verrà addebitato nulla."),
("billingUnavailableShort","الدفع غير متاح حاليًا.","Payment is not available right now.","Il pagamento non è al momento disponibile."),
("billingCurrent","خطتك الحالية","Your current plan","Il tuo piano attuale"),
("billingPlans","الخطط","Plans","Piani"),
("billingNoPlans","لا توجد خطط منشورة بعد.","No plans have been published yet.","Nessun piano è ancora stato pubblicato."),
("billingFree","مجاني","Free","Gratuito"),
("billingPerMonth","{amount} / شهريًا","{amount} / month","{amount} / mese"),
("billingPerYear","{amount} / سنويًا","{amount} / year","{amount} / anno"),
("billingYourPlan","خطتك","Your plan","Il tuo piano"),
("billingChoose","اختيار هذه الخطة","Choose this plan","Scegli questo piano"),
("billingFeatAi","{n} أسئلة للمساعد يوميًا","{n} assistant questions per day","{n} domande all'assistente al giorno"),
("billingFeatReminders","تذكيرات متقدمة","Advanced reminders","Promemoria avanzati"),
("billingFeatDocAi","تحليل المستندات بالذكاء الاصطناعي","AI document analysis","Analisi dei documenti con IA"),
("billingFeatHuman","{n} رصيد مساعدة بشرية","{n} human-assistance credits","{n} crediti di assistenza umana"),
("billingStatusActive","نشط","Active","Attivo"),
("billingStatusPastDue","الدفع متأخر","Payment past due","Pagamento in ritardo"),
("billingStatusCanceled","ملغى","Canceled","Annullato"),
("billingStatusFree","خطة مجانية","Free plan","Piano gratuito"),
("billingAccessUntil","يبقى الوصول حتى {date}","Access until {date}","Accesso fino al {date}"),
("billingRenews","يتجدد في {date}","Renews on {date}","Si rinnova il {date}"),
("billingEnding","سينتهي في نهاية الفترة","Ends at period end","Termina a fine periodo"),
("billingCancel","إلغاء عند نهاية الفترة","Cancel at period end","Annulla a fine periodo"),
("billingCancelTitle","إلغاء الاشتراك؟","Cancel subscription?","Annullare l'abbonamento?"),
("billingCancelBody","ستحتفظ بمزايا خطتك حتى نهاية الفترة المدفوعة، ثم لن يتجدد الاشتراك.","You keep your plan's features until the end of the paid period, then it will not renew.","Mantieni le funzioni del piano fino alla fine del periodo pagato, poi non si rinnoverà."),
("billingCancelConfirm","نعم، ألغِ","Yes, cancel","Sì, annulla"),
("billingCancelled","تم الإلغاء عند نهاية الفترة.","Cancellation set for the end of the period.","Annullamento impostato a fine periodo."),
("billingNothingToCancel","لا يوجد اشتراك قابل للإلغاء.","There is no subscription to cancel.","Non c'è nessun abbonamento da annullare."),
("billingCheckoutFailed","تعذّر فتح صفحة الدفع.","The checkout page could not be opened.","Impossibile aprire la pagina di pagamento."),
("billingAlreadySubscribed","لديك اشتراك نشط بالفعل.","You already have an active subscription.","Hai già un abbonamento attivo."),
("billingPlanNotPurchasable","هذه الخطة غير متاحة للشراء.","This plan cannot be purchased.","Questo piano non è acquistabile."),
("billingInvoices","الفواتير","Invoices","Fatture"),
("billingNoInvoices","لا توجد فواتير بعد.","No invoices yet.","Nessuna fattura per ora."),
("billingPricesNote","الأسعار قابلة للتعديل وتُعرض كما يرسلها الخادم. الدفع يتم في المتصفح ولا يمرّ ببيانات بطاقتك عبر التطبيق.","Prices can change and are shown as the server sends them. Payment happens in the browser; the app never handles your card details.","I prezzi possono cambiare e sono mostrati come li invia il server. Il pagamento avviene nel browser; l'app non gestisce mai i dati della tua carta."),
]
