S = [
("exploreHousing","فاحص عقد الإيجار","Rental checker","Verifica affitto"),
("housingTitle","فاحص عقد الإيجار","Rental checker","Verifica affitto"),
("housingIntro","الصق نص إعلان الإيجار أو العقد لنُبرز النقاط المهمة وعلامات التحذير والأسئلة التي يجب طرحها.","Paste the rental listing or contract text to highlight key terms, red flags and questions to ask.","Incolla il testo dell'annuncio o del contratto per evidenziare condizioni chiave, segnali di allarme e domande da fare."),
("housingConsentNeeded","فحص الإيجار يحتاج موافقتك على «تحليل السكن». لا نحفظ النص.","The rental check needs your consent to \"housing analysis\". The text is not saved.","La verifica richiede il tuo consenso all'«analisi dell'alloggio». Il testo non viene salvato."),
("housingConsentGranted","تم منح الموافقة. اضغط «افحص» مرة أخرى.","Consent granted. Tap \"Check\" again.","Consenso concesso. Tocca di nuovo «Verifica»."),
("housingTextLabel","نص الإعلان أو العقد","Listing or contract text","Testo dell'annuncio o del contratto"),
("housingTextHint","الصق النص هنا (20 حرفًا على الأقل)","Paste the text here (at least 20 characters)","Incolla qui il testo (almeno 20 caratteri)"),
("housingTextTooShort","النص قصير جدًا. الصق 20 حرفًا على الأقل.","The text is too short. Paste at least 20 characters.","Il testo è troppo corto. Incolla almeno 20 caratteri."),
("housingExtraTitle","تكاليف إضافية تعرفها (اختياري)","Extra costs you know (optional)","Costi aggiuntivi che conosci (facoltativo)"),
("housingRent","الإيجار الشهري","Monthly rent","Affitto mensile"),
("housingUtilities","الخدمات (شهريًا)","Utilities (monthly)","Utenze (mensili)"),
("housingCondo","رسوم العمارة (شهريًا)","Condo fees (monthly)","Spese condominiali (mensili)"),
("housingInternet","الإنترنت (شهريًا)","Internet (monthly)","Internet (mensile)"),
("housingExplain","أضف شرحًا بالذكاء الاصطناعي","Add an AI explanation","Aggiungi una spiegazione con IA"),
("housingSend","افحص","Check","Verifica"),
("housingQuotaLeft","الفحوصات المتبقية: {n}","Checks left: {n}","Verifiche rimaste: {n}"),
("housingQuotaReached","وصلت إلى حدّ فحوصات السكن. حاول لاحقًا أو راجع خطتك.","You have reached your rental-check limit. Try again later or check your plan.","Hai raggiunto il limite di verifiche. Riprova più tardi o controlla il tuo piano."),
("housingConfidence","ثقة التحليل: {level}","Analysis confidence: {level}","Affidabilità dell'analisi: {level}"),
("housingFacts","ما وجدناه في النص","What we found in the text","Cosa abbiamo trovato nel testo"),
("housingFactRent","الإيجار الشهري: {v}","Monthly rent: {v}","Affitto mensile: {v}"),
("housingFactDeposit","التأمين (الضمان): {v}","Deposit: {v}","Deposito cauzionale: {v}"),
("housingFactDepositMonths","التأمين: {v} شهر/أشهر","Deposit: {v} month(s)","Deposito: {v} mese/i"),
("housingFactUtilitiesIncluded","الخدمات: مشمولة","Utilities: included","Utenze: incluse"),
("housingFactUtilitiesExcluded","الخدمات: غير مشمولة","Utilities: not included","Utenze: escluse"),
("housingFactExpenses","مصاريف شهرية: {v}","Monthly expenses: {v}","Spese mensili: {v}"),
("housingRedFlags","علامات تحذير محتملة","Possible red flags","Possibili segnali di allarme"),
("housingNoRedFlags","لم نجد علامات تحذير واضحة في النص، وهذا لا يعني أن العقد سليم.","We found no clear red flags in the text, which does not mean the contract is sound.","Non abbiamo trovato segnali di allarme evidenti nel testo, il che non significa che il contratto sia a posto."),
("housingSevWarning","تحذير","Warning","Attenzione"),
("housingSevCaution","تنبيه","Caution","Cautela"),
("housingSevInfo","معلومة","Info","Info"),
("housingOneDeposit","التأمين (مرة واحدة)","Deposit","Deposito cauzionale"),
("housingOneAgencyFee","عمولة الوكالة","Agency fee","Commissione d'agenzia"),
("housingBasisGeneral","إرشاد عام","General guidance","Indicazione generale"),
("housingBasisSourced","مبني على مصدر","Based on a source","Basato su una fonte"),
("housingQuestions","أسئلة تطرحها على المؤجّر","Questions to ask the landlord","Domande da fare al proprietario"),
("housingCouldNotDetect","لم نستطع تحديد هذه البنود","Things we could not detect","Cose che non siamo riusciti a rilevare"),
("housingCost","تقدير التكلفة الشهرية","Estimated monthly cost","Costo mensile stimato"),
("housingCostTotal","الإجمالي التقريبي: {v} شهريًا","Approximate total: {v} per month","Totale approssimativo: {v} al mese"),
("housingCostUnknown","لا يمكن حساب إجمالي موثوق من المعلومات المتاحة.","A reliable total cannot be computed from the available information.","Non è possibile calcolare un totale affidabile con le informazioni disponibili."),
("housingCompRent","الإيجار","Rent","Affitto"),
("housingCompUtilities","الخدمات","Utilities","Utenze"),
("housingCompCondo","رسوم العمارة","Condo fees","Spese condominiali"),
("housingCompInternet","الإنترنت","Internet","Internet"),
("housingSourceUser","أدخلتَه أنت","you entered","inserito da te"),
("housingSourceText","من النص","from the text","dal testo"),
("housingAssumptions","افتراضات التقدير","Assumptions behind the estimate","Ipotesi alla base della stima"),
("housingOneTime","تكاليف لمرة واحدة","One-time costs","Costi una tantum"),
("housingNotes","ملاحظات","Notes","Note"),
("housingAiExplanation","شرح بالذكاء الاصطناعي","AI explanation","Spiegazione IA"),
("housingDisclaimerTitle","تنبيه","Disclaimer","Avvertenza"),
("housingFallbackDisclaimer","هذه إرشادات عامة وليست استشارة قانونية. استشر محاميًا أو جهة مختصة قبل التوقيع.","This is general guidance, not legal advice. Ask a lawyer or qualified body before signing.","Indicazioni generali, non consulenza legale. Rivolgiti a un avvocato o a un ente qualificato prima di firmare."),
("housingAnother","فحص نص آخر","Check another text","Verifica un altro testo"),
]
