S = [
("scannerOcrFallback","تعذّر على الخادم قراءة النص من الصورة. الصق نص الخطاب هنا بدلًا من ذلك.","The server could not read the text from the photo. Paste the letter's text here instead.","Il server non è riuscito a leggere il testo dalla foto. Incolla invece il testo della lettera."),
("scannerConsentNeeded","شرح المستندات يحتاج موافقتك على «تحليل المستندات». لن يُحفظ المستند.","Explaining documents needs your consent to \"document analysis\". The document is not stored.","Spiegare i documenti richiede il tuo consenso all'«analisi dei documenti». Il documento non viene salvato."),
("scannerConsentGranted","تم منح الموافقة. اضغط «إرسال للشرح» مرة أخرى.","Consent granted. Tap \"Send for explanation\" again.","Consenso concesso. Tocca di nuovo «Invia per la spiegazione»."),
("scannerQuotaReached","وصلت إلى حدّك اليومي لشرح المستندات. حاول لاحقًا أو راجع خطتك.","You have reached your limit for document explanations. Try again later or check your plan.","Hai raggiunto il limite di spiegazioni di documenti. Riprova più tardi o controlla il tuo piano."),
("scannerQuotaLeft","المحاولات المتبقية: {n}","Explanations left: {n}","Spiegazioni rimaste: {n}"),
("scannerFileTypeNotAllowed","نوع الملف غير مسموح. استخدم صورة JPG أو PNG أو ملف PDF.","This file type is not allowed. Use a JPG or PNG photo or a PDF.","Tipo di file non consentito. Usa una foto JPG o PNG o un PDF."),
("scannerFileTooLarge","الصورة كبيرة جدًا. التقط صورة أصغر أو الصق النص.","The image is too large. Take a smaller photo or paste the text.","L'immagine è troppo grande. Scatta una foto più piccola o incolla il testo."),
("scannerPdfTooLong","ملف PDF يحتوي صفحات كثيرة جدًا.","The PDF has too many pages.","Il PDF ha troppe pagine."),
("scannerFileRejected","تعذّر قبول الملف. جرّب ملفًا آخر أو الصق النص.","The file could not be accepted. Try another file or paste the text.","Il file non è stato accettato. Prova un altro file o incolla il testo."),
("scannerUnavailableLater","فحص الملفات غير متاح مؤقتًا ولم يُحفظ شيء. حاول لاحقًا.","File checking is temporarily unavailable and nothing was stored. Try again later.","Il controllo dei file non è al momento disponibile e non è stato salvato nulla. Riprova più tardi."),
("scannerDateNotClear","التاريخ غير واضح","Date not clear","Data non chiara"),
("scannerYearMissing","السنة غير مذكورة في المستند","The year is not stated in the document","L'anno non è indicato nel documento"),
("scannerDatePast","هذا التاريخ مضى","This date has passed","Questa data è passata"),
("scannerConfidence","درجة الثقة: {level}","Confidence: {level}","Affidabilità: {level}"),
("confLow","منخفضة","low","bassa"),
("confMedium","متوسطة","medium","media"),
("confHigh","عالية","high","alta"),
("scannerDegraded","تعذّر استخدام الذكاء الاصطناعي بالكامل، لذلك هذا الشرح مبسّط.","The AI could not be fully used, so this explanation is simplified.","L'IA non ha potuto essere usata pienamente, quindi questa spiegazione è semplificata."),
("scannerCheckDates","تحقق دائمًا من التواريخ في المستند الأصلي.","Always check the dates on the original document.","Controlla sempre le date sul documento originale."),
]
