#!/usr/bin/env python3
"""Source table for the ARB files. Run: python3 tool/strings.py  (regenerates lib/l10n/app_{ar,en,it}.arb).
Arabic is the template language. Placeholders use {name}; all are Strings."""
import json, re, os
S = [
("appName","إكسبا","EXPA","EXPA"),
("appTagline","مساعدك في الحياة في إيطاليا","Your Life Assistant in Italy","Il tuo assistente per vivere in Italia"),
("tabHome","الرئيسية","Home","Home"),
("tabExplore","استكشف","Explore","Esplora"),
("tabAsk","اسأل EXPA","Ask EXPA","Chiedi a EXPA"),
("tabTasks","المهام","Tasks","Attività"),
("tabProfile","حسابي","Profile","Profilo"),
("retry","إعادة المحاولة","Try again","Riprova"),
("cancel","إلغاء","Cancel","Annulla"),
("save","حفظ","Save","Salva"),
("close","إغلاق","Close","Chiudi"),
("loading","جارٍ التحميل…","Loading…","Caricamento…"),
("errorGeneric","حدث خطأ ما. حاول مرة أخرى.","Something went wrong. Please try again.","Qualcosa è andato storto. Riprova."),
("errorNetwork","لا يوجد اتصال بالإنترنت. تحقق من الشبكة وحاول مرة أخرى.","No internet connection. Check your network and try again.","Nessuna connessione a Internet. Controlla la rete e riprova."),
("errorTimeout","استغرق الطلب وقتًا طويلًا. حاول مرة أخرى.","The request took too long. Please try again.","La richiesta ha impiegato troppo tempo. Riprova."),
("errorServer","الخدمة غير متاحة مؤقتًا. حاول لاحقًا.","The service is temporarily unavailable. Try again later.","Servizio temporaneamente non disponibile. Riprova più tardi."),
("errorForbidden","ليس لديك صلاحية لهذا الإجراء.","You are not allowed to do this.","Non hai i permessi per questa azione."),
("errorNotFound","لم نجد ما تبحث عنه.","We could not find what you are looking for.","Non abbiamo trovato ciò che cerchi."),
("errorRateLimited","طلبات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.","Too many requests. Wait a moment and try again.","Troppe richieste. Attendi un momento e riprova."),
("errorValidation","تحقق من البيانات المدخلة.","Please check the information you entered.","Controlla i dati inseriti."),
("emptyList","لا توجد عناصر لعرضها.","Nothing to show yet.","Niente da mostrare."),
("loadMore","عرض المزيد","Load more","Mostra altro"),
("openOfficialSite","فتح الموقع الرسمي","Open the official website","Apri il sito ufficiale"),
("linkUnsafe","تم حجب الرابط لأنه غير آمن.","This link was blocked because it is not secure.","Link bloccato perché non sicuro."),
("linkOpenFailed","تعذّر فتح الرابط.","The link could not be opened.","Impossibile aprire il link."),
("optional","اختياري","Optional","Facoltativo"),
("skip","تخطي","Skip","Salta"),
("next","التالي","Next","Avanti"),
("delete","حذف","Delete","Elimina"),
("saved","تم الحفظ.","Saved.","Salvato."),
("sessionExpired","انتهت الجلسة. سجّل الدخول مرة أخرى.","Your session has expired. Please sign in again.","Sessione scaduta. Accedi di nuovo."),
("consentRequired","هذا الإجراء يحتاج إلى موافقتك. يمكنك منحها من إعدادات الخصوصية.","This action needs your consent. You can grant it in privacy settings.","Questa azione richiede il tuo consenso. Puoi darlo nelle impostazioni sulla privacy."),
("grantConsent","منح الموافقة","Grant consent","Concedi il consenso"),
("loginTitle","تسجيل الدخول","Sign in","Accedi"),
("loginSubtitle","مرحبًا بعودتك إلى إكسبا","Welcome back to EXPA","Bentornato su EXPA"),
("email","البريد الإلكتروني","Email","Email"),
("password","كلمة المرور","Password","Password"),
("confirmPassword","تأكيد كلمة المرور","Confirm password","Conferma password"),
("name","الاسم","Name","Nome"),
("loginButton","دخول","Sign in","Accedi"),
("registerButton","إنشاء حساب","Create account","Crea account"),
("registerTitle","إنشاء حساب جديد","Create your account","Crea il tuo account"),
("forgotLink","نسيت كلمة المرور؟","Forgot your password?","Password dimenticata?"),
("noAccount","ليس لديك حساب؟ أنشئ حسابًا","No account yet? Create one","Non hai un account? Registrati"),
("haveAccount","لديك حساب؟ سجّل الدخول","Already have an account? Sign in","Hai già un account? Accedi"),
("acceptTerms","أوافق على شروط الاستخدام","I accept the terms of use","Accetto i termini d'uso"),
("acceptPrivacy","اطلعت على سياسة الخصوصية وأوافق عليها","I have read and accept the privacy policy","Ho letto e accetto l'informativa sulla privacy"),
("passwordHint","10 أحرف على الأقل، مع أحرف وأرقام","At least 10 characters, with letters and numbers","Almeno 10 caratteri, con lettere e numeri"),
("invalidCredentials","البريد الإلكتروني أو كلمة المرور غير صحيحة.","Incorrect email or password.","Email o password non corrette."),
("fieldRequired","هذا الحقل مطلوب.","This field is required.","Campo obbligatorio."),
("invalidEmail","أدخل بريدًا إلكترونيًا صحيحًا.","Enter a valid email address.","Inserisci un indirizzo email valido."),
("passwordsMismatch","كلمتا المرور غير متطابقتين.","The passwords do not match.","Le password non coincidono."),
("passwordTooShort","كلمة المرور قصيرة جدًا.","The password is too short.","La password è troppo corta."),
("mustAcceptBoth","يجب الموافقة على الشروط وسياسة الخصوصية.","You must accept the terms and the privacy policy.","Devi accettare i termini e l'informativa sulla privacy."),
("forgotTitle","استعادة كلمة المرور","Reset your password","Recupera la password"),
("forgotBody","أدخل بريدك الإلكتروني وسنرسل لك رابط الاستعادة إن كان الحساب موجودًا.","Enter your email and we will send a reset link if the account exists.","Inserisci la tua email: se l'account esiste, riceverai un link di recupero."),
("sendResetLink","إرسال الرابط","Send reset link","Invia il link"),
("resetSent","إذا كان الحساب موجودًا فقد أرسلنا رابط الاستعادة إلى بريدك.","If the account exists, a reset link is on its way to your email.","Se l'account esiste, ti abbiamo inviato un link di recupero."),
("verifyTitle","تحقق من بريدك الإلكتروني","Check your email","Controlla la tua email"),
("verifyBody","أرسلنا رابط التفعيل إلى بريدك. افتح الرابط ثم ارجع إلى التطبيق. بعض الميزات مثل اسأل EXPA تتطلب بريدًا مفعّلًا.","We sent a verification link to your email. Open it, then come back to the app. Some features such as Ask EXPA need a verified email.","Abbiamo inviato un link di verifica alla tua email. Aprilo e torna nell'app. Alcune funzioni, come Chiedi a EXPA, richiedono un'email verificata."),
("verifyBanner","بريدك الإلكتروني غير مفعّل بعد.","Your email is not verified yet.","La tua email non è ancora verificata."),
("resendVerification","إعادة إرسال رابط التفعيل","Resend verification email","Reinvia l'email di verifica"),
("verificationSent","تم إرسال رابط التفعيل.","Verification email sent.","Email di verifica inviata."),
("verifiedCheck","لقد فعّلت بريدي","I have verified my email","Ho verificato l'email"),
("continueToApp","المتابعة إلى التطبيق","Continue to the app","Continua nell'app"),
("logout","تسجيل الخروج","Sign out","Esci"),
("accountSuspended","هذا الحساب موقوف.","This account is suspended.","Questo account è sospeso."),
("language","اللغة","Language","Lingua"),
("langAr","العربية","العربية","العربية"),
("langEn","English","English","English"),
("langIt","Italiano","Italiano","Italiano"),
("homeGreeting","مرحبًا {name}","Welcome {name}","Ciao {name}"),
("scoreTitle","درجة EXPA","EXPA Score","Punteggio EXPA"),
("scoreHow","كيف تُحسب؟","How is it calculated?","Come viene calcolato?"),
("scoreUnavailable","لا توجد بيانات كافية لحساب الدرجة بعد.","Not enough information to calculate your score yet.","Non ci sono ancora dati sufficienti per calcolare il punteggio."),
("scoreSemantics","درجة EXPA {percent} بالمئة","EXPA score {percent} percent","Punteggio EXPA {percent} per cento"),
("nextActions","ماذا أفعل الآن؟","What should I do next?","Cosa devo fare adesso?"),
("nextActionsEmpty","لا توجد إجراءات مقترحة الآن.","No suggested actions right now.","Nessuna azione suggerita al momento."),
("personalizationOff","التخصيص متوقف. فعّله من الخصوصية للحصول على اقتراحات تناسبك.","Personalization is off. Turn it on in privacy settings for tailored suggestions.","La personalizzazione è disattivata. Attivala nella privacy per suggerimenti su misura."),
("onboardingContinue","أكمل ملفك الشخصي","Complete your profile","Completa il tuo profilo"),
("tasksTitle","مهام الاستقرار","Setup tasks","Attività di inserimento"),
("taskMarkDone","تم","Mark done","Fatto"),
("taskReopen","إعادة فتح","Reopen","Riapri"),
("taskDismiss","لا ينطبق عليّ","Not for me","Non mi riguarda"),
("taskDone","مكتملة","Done","Completata"),
("tasksDocuments","وثائقي","My documents","I miei documenti"),
("guidesTitle","الأدلة","Guides","Guide"),
("searchHint","ابحث…","Search…","Cerca…"),
("allCategories","الكل","All","Tutte"),
("sourceLabel","المصدر","Source","Fonte"),
("sourceOfficial","رسمي","Official","Ufficiale"),
("sourceInstitutional","مؤسسي","Institutional","Istituzionale"),
("sourceVerifiedPartner","شريك موثّق","Verified partner","Partner verificato"),
("sourceThirdParty","طرف ثالث","Third party","Terze parti"),
("lastVerified","آخر تحقق: {date}","Last verified: {date}","Ultima verifica: {date}"),
("neverVerified","لم يتم التحقق من المصدر بعد","Not verified yet","Non ancora verificato"),
("freshFresh","محدّث","Up to date","Aggiornato"),
("freshStale","قد يكون قديمًا","May be outdated","Potrebbe essere datato"),
("freshOutdated","قديم – تحقق من الموقع الرسمي","Outdated: check the official site","Obsoleto: controlla il sito ufficiale"),
("freshUnverified","غير موثّق","Unverified","Non verificato"),
("fallbackLocale","هذا المحتوى غير متوفر بلغتك، يُعرض بلغة أخرى.","This content is not available in your language and is shown in another one.","Questo contenuto non è disponibile nella tua lingua ed è mostrato in un'altra."),
("secWhatIs","ما هو؟","What is it?","Che cos'è?"),
("secWhoNeeds","من يحتاجه؟","Who needs it?","Chi ne ha bisogno?"),
("secDocuments","الوثائق المطلوبة","Required documents","Documenti richiesti"),
("secSteps","الخطوات","Steps","Passaggi"),
("secWhere","أين تقدّم؟","Where to apply","Dove presentare la domanda"),
("secBook","كيف تحجز؟","How to book","Come prenotare"),
("secCosts","التكاليف","Costs","Costi"),
("secTime","مدة المعالجة","Processing time","Tempi di elaborazione"),
("verifyOfficialNotice","معلومات عامة للإرشاد. تحقق دائمًا من المصدر الرسمي قبل أي قرار.","General guidance. Always check the official source before deciding.","Informazioni generali di orientamento. Verifica sempre la fonte ufficiale prima di decidere."),
("documentsTitle","وثائقي","My documents","I miei documenti"),
("addDocument","إضافة وثيقة","Add a document","Aggiungi documento"),
("docType","نوع الوثيقة","Document type","Tipo di documento"),
("docLabel","تسمية (اختياري)","Label (optional)","Etichetta (facoltativa)"),
("issueDate","تاريخ الإصدار","Issue date","Data di rilascio"),
("expiryDate","تاريخ الانتهاء","Expiry date","Data di scadenza"),
("notes","ملاحظات","Notes","Note"),
("remindersEnabled","تذكيري قبل الانتهاء","Remind me before it expires","Ricordami prima della scadenza"),
("noExpiry","بدون تاريخ انتهاء","No expiry date","Nessuna scadenza"),
("daysRemaining","متبقي {n} يوم","{n} days left","{n} giorni rimasti"),
("expiredDaysAgo","انتهت منذ {n} يوم","Expired {n} days ago","Scaduto da {n} giorni"),
("statusValid","سارية","Valid","Valido"),
("statusExpiringSoon","تنتهي قريبًا","Expiring soon","In scadenza"),
("statusExpired","منتهية","Expired","Scaduto"),
("statusNoExpiry","بلا انتهاء","No expiry","Senza scadenza"),
("pickDate","اختر التاريخ","Pick a date","Scegli la data"),
("clearDate","مسح","Clear","Cancella"),
("docsEmpty","لم تضف أي وثيقة بعد. أضف جواز السفر أو تصريح الإقامة لنذكّرك قبل انتهائهما.","You have not added any document yet. Add your passport or residence permit and we will remind you before they expire.","Non hai ancora aggiunto documenti. Aggiungi passaporto o permesso di soggiorno e ti avviseremo prima della scadenza."),
("deleteDocConfirm","حذف هذه الوثيقة؟","Delete this document?","Eliminare questo documento?"),
("consentNeededDocs","لحفظ وثائقك نحتاج موافقتك على تخزين الوثائق.","To save your documents we need your consent to store them.","Per salvare i documenti serve il tuo consenso alla conservazione."),
("docAttachmentsNote","المرفقات متاحة في الموقع. هذه النسخة تتتبع التواريخ فقط.","Attachments are available on the website. This version tracks dates only.","Gli allegati sono disponibili sul sito. Questa versione gestisce solo le date."),
("askTitle","اسأل EXPA","Ask EXPA","Chiedi a EXPA"),
("askHint","اكتب سؤالك بالعربية أو الإنجليزية أو الإيطالية","Type your question in Arabic, English or Italian","Scrivi la tua domanda in arabo, inglese o italiano"),
("askSend","إرسال","Send","Invia"),
("askIntro","اسألني عن الإقامة والوثائق والخدمات الحكومية. أجيب اعتمادًا على مصادر موثّقة وأذكرها لك.","Ask me about residence, documents and government services. I answer from verified sources and show them to you.","Chiedimi di permesso di soggiorno, documenti e servizi pubblici. Rispondo da fonti verificate e te le mostro."),
("askUsage","المتبقي اليوم: {n}","Remaining today: {n}","Rimaste oggi: {n}"),
("askResets","يتجدد الحد في {date}","Limit resets on {date}","Il limite si azzera il {date}"),
("askLimitReached","وصلت إلى حدّ الأسئلة اليومي.","You have reached today's question limit.","Hai raggiunto il limite giornaliero di domande."),
("askVerifyEmail","فعّل بريدك الإلكتروني لاستخدام اسأل EXPA.","Verify your email to use Ask EXPA.","Verifica la tua email per usare Chiedi a EXPA."),
("askFailed","تعذّرت المعالجة الآن. حاول مرة أخرى.","I couldn't process that right now. Please try again.","Non sono riuscito a elaborare la richiesta. Riprova."),
("askDegraded","تعذّر استخدام الذكاء الاصطناعي الآن. هذه إجابة محدودة، تصفّح الأدلة للحصول على معلومات موثّقة.","The AI is unavailable right now. This is a limited answer; browse the guides for verified information.","L'IA non è disponibile ora. Questa è una risposta limitata: consulta le guide per informazioni verificate."),
("askBrowseGuides","تصفّح الأدلة","Browse the guides","Sfoglia le guide"),
("askSourcesTitle","المصادر","Sources","Fonti"),
("askNoSources","لا توجد مصادر موثّقة لهذه الإجابة.","There are no verified sources for this answer.","Nessuna fonte verificata per questa risposta."),
("askNoticeTitle","تنبيه","Notice","Avviso"),
("askYou","أنت","You","Tu"),
("askAssistant","EXPA","EXPA","EXPA"),
("askSuggested","إجراءات مقترحة","Suggested actions","Azioni suggerite"),
("askLabelOfficial","معلومات رسمية","Official information","Informazione ufficiale"),
("askLabelGeneral","إرشاد عام","General guidance","Orientamento generale"),
("askLabelAi","شرح بالذكاء الاصطناعي","AI explanation","Spiegazione dell'IA"),
("askLabelThird","خدمة أو مصدر من طرف ثالث","Third-party service or source","Servizio o fonte di terzi"),
("learnTitle","تعلّم الإيطالية","Learn Italian","Impara l'italiano"),
("dailyTitle","إيطالية اليوم – 10 دقائق","Daily 10-minute Italian","Italiano in 10 minuti al giorno"),
("dailyDone","تم اليوم","Done today","Fatto oggi"),
("minutes","{n} دقيقة","{n} min","{n} min"),
("streak","سلسلة الأيام: {n}","Day streak: {n}","Giorni consecutivi: {n}"),
("lessonsTitle","الدروس","Lessons","Lezioni"),
("lessonStart","ابدأ الدرس","Start lesson","Inizia la lezione"),
("lessonComplete","أنهيت الدرس","Mark as completed","Segna come completata"),
("lessonCompleted","مكتمل","Completed","Completata"),
("lessonsEmpty","لا توجد دروس متاحة بعد.","No lessons available yet.","Nessuna lezione disponibile."),
("jobsTitle","الوظائف","Jobs","Lavoro"),
("matchScore","نسبة التوافق: {n}%","Match score: {n}%","Compatibilità: {n}%"),
("matchUnknown","لا توجد بيانات كافية للمطابقة","Not enough data to match","Dati insufficienti per il confronto"),
("matchReasons","لماذا هذه النتيجة؟","Why this score?","Perché questo punteggio?"),
("reasonMatch","متوافق","Matches","Corrisponde"),
("reasonPartial","متوافق جزئيًا","Partly matches","Corrisponde in parte"),
("reasonMismatch","غير متوافق","Does not match","Non corrisponde"),
("reasonUnknown","غير معروف (لا يؤثر سلبًا)","Unknown (not counted against you)","Sconosciuto (non penalizza)"),
("applyOriginal","التقديم في الموقع الأصلي","Apply on the original site","Candidati sul sito originale"),
("applyNotice","EXPA لا يقدّم الطلب نيابةً عنك. ستنتقل إلى صفحة التقديم الأصلية.","EXPA does not submit applications. You will go to the original application page.","EXPA non invia candidature. Andrai alla pagina originale di candidatura."),
("visaStated","ذكر المصدر دعم التأشيرة","The source states visa sponsorship","La fonte indica sponsorizzazione del visto"),
("visaNotStated","لا يذكر المصدر دعم التأشيرة","Visa sponsorship is not stated","Sponsorizzazione del visto non indicata"),
("jobsEmpty","لا توجد وظائف مطابقة الآن.","No matching jobs right now.","Nessun lavoro corrispondente al momento."),
("jobSource","المصدر: {name}","Source: {name}","Fonte: {name}"),
("jobsSignInForMatch","سجّل الدخول وأكمل ملفك لرؤية نسبة التوافق.","Sign in and complete your profile to see match scores.","Accedi e completa il profilo per vedere la compatibilità."),
("notificationsTitle","الإشعارات","Notifications","Notifiche"),
("markAllRead","تعليم الكل كمقروء","Mark all as read","Segna tutto come letto"),
("notificationsEmpty","لا توجد إشعارات.","No notifications.","Nessuna notifica."),
("apptTitle","حجز المواعيد","Appointments","Appuntamenti"),
("apptNotice","EXPA لا يحجز نيابةً عنك. سنوجّهك إلى الجهة الرسمية لإتمام الحجز بنفسك.","EXPA does not book for you. We point you to the official body so you can complete the booking yourself.","EXPA non prenota per te. Ti indichiamo l'ente ufficiale per completare la prenotazione."),
("apptOfficeType","نوع الجهة","Office type","Tipo di ufficio"),
("apptCity","المدينة","City","Città"),
("apptSearch","عرض الجهات","Show offices","Mostra uffici"),
("apptGoOfficial","الانتقال إلى صفحة الحجز الرسمية","Go to the official booking page","Vai alla pagina ufficiale di prenotazione"),
("apptNoUrl","لا يوجد رابط حجز رسمي مسجّل. راجع الموقع الرسمي للجهة.","No official booking link is on file. Check the office's official website.","Nessun link ufficiale di prenotazione. Controlla il sito ufficiale dell'ufficio."),
("apptEmpty","لا توجد جهات مسجّلة لهذه المدينة.","No offices on file for this city.","Nessun ufficio registrato per questa città."),
("exploreTitle","استكشف","Explore","Esplora"),
("exploreGuides","الأدلة والوثائق","Guides & documents","Guide e documenti"),
("exploreLearn","تعلّم الإيطالية","Learn Italian","Impara l'italiano"),
("exploreJobs","الوظائف","Jobs","Lavoro"),
("exploreAppointments","حجز المواعيد","Appointments","Appuntamenti"),
("exploreMyDocs","وثائقي وتواريخ الانتهاء","My documents & expiry dates","I miei documenti e scadenze"),
("exploreNotifications","الإشعارات","Notifications","Notifiche"),
("profileTitle","حسابي","Profile","Profilo"),
("profilePrivacy","الخصوصية والموافقات","Privacy & consents","Privacy e consensi"),
("profileOnboarding","ملفي الشخصي","My profile details","I miei dati"),
("pushNote","الإشعارات الفورية غير مفعّلة في هذه النسخة.","Push notifications are not enabled in this version.","Le notifiche push non sono attive in questa versione."),
("privacyTitle","الخصوصية","Privacy","Privacy"),
("consentsTitle","موافقاتك","Your consents","I tuoi consensi"),
("consentRequiredBadge","مطلوب","Required","Obbligatorio"),
("consentsHint","يمكنك تغيير الموافقات الاختيارية في أي وقت.","You can change optional consents at any time.","Puoi modificare i consensi facoltativi in qualsiasi momento."),
("exportTitle","تصدير بياناتي","Export my data","Esporta i miei dati"),
("exportBody","اطلب نسخة من بياناتك الشخصية. الحد الأقصى 5 طلبات في الساعة.","Request a copy of your personal data. Limit: 5 requests per hour.","Richiedi una copia dei tuoi dati personali. Limite: 5 richieste all'ora."),
("exportRequest","طلب التصدير","Request export","Richiedi l'esportazione"),
("exportDone","تم تجهيز بياناتك ({n} أقسام). لم يتم حفظها على الجهاز.","Your data is ready ({n} sections). It was not saved on this device.","I tuoi dati sono pronti ({n} sezioni). Non sono stati salvati sul dispositivo."),
("deleteAccountTitle","حذف الحساب","Delete account","Elimina account"),
("deleteAccountBody","الحذف نهائي. يتوقف الوصول فورًا ويكتمل مسح البيانات لاحقًا. أدخل كلمة المرور للتأكيد.","Deletion is permanent. Access stops immediately and erasure completes later. Enter your password to confirm.","L'eliminazione è definitiva. L'accesso si interrompe subito e la cancellazione si completa dopo. Inserisci la password per confermare."),
("deleteAccountConfirm","طلب حذف الحساب","Request account deletion","Richiedi eliminazione account"),
("deleteRequested","تم تقديم طلب الحذف.","Deletion requested.","Richiesta di eliminazione inviata."),
("onboardingTitle","عن وضعك في إيطاليا","About you in Italy","La tua situazione in Italia"),
("onboardingIntro","نجمع فقط ما يلزم للتخصيص. يمكنك تخطي الأسئلة الاختيارية.","We only collect what personalization needs. You can skip optional questions.","Raccogliamo solo ciò che serve alla personalizzazione. Puoi saltare le domande facoltative."),
("fieldSegment","وضعك الحالي","Current status","Situazione attuale"),
("fieldNationality","الجنسية (رمز من حرفين، مثل EG)","Nationality (2-letter code, e.g. EG)","Nazionalità (codice a 2 lettere, es. EG)"),
("fieldCity","المدينة","City","Città"),
("fieldResidence","نوع الإقامة","Residence type","Tipo di soggiorno"),
("fieldItalian","مستوى الإيطالية","Italian level","Livello di italiano"),
("fieldEnglish","مستوى الإنجليزية","English level","Livello di inglese"),
("fieldGoals","أهدافك","Your goals","I tuoi obiettivi"),
("fieldAge","الفئة العمرية","Age range","Fascia d'età"),
("notSelected","غير محدد","Not set","Non impostato"),
("completeOnboarding","إنهاء","Finish","Fine"),
("onboardingSegmentRequired","اختر وضعك الحالي لإنهاء الإعداد.","Choose your current status to finish.","Scegli la tua situazione per terminare."),
]
ph = re.compile(r"\{(\w+)\}")
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
for i, lang in enumerate(["ar","en","it"], start=1):
    d = {"@@locale": lang}
    for row in S:
        k, v = row[0], row[i]
        d[k] = v
        if lang == "ar":
            names = ph.findall(v)
            if names:
                d["@"+k] = {"placeholders": {n: {"type": "String"} for n in names}}
    keys = {r[0] for r in S}
    assert len(keys) == len(S), "duplicate keys"
    for r in S:
        assert set(ph.findall(r[1])) == set(ph.findall(r[2])) == set(ph.findall(r[3])), r[0]
    json.dump(d, open(f"lib/l10n/app_{lang}.arb","w"), ensure_ascii=False, indent=2)
print(len(S), "keys")
