<?php

namespace App\Domains\Ai\Services;

use App\Domains\Learning\Models\ItalianVocabulary;
use App\Domains\Patente\Models\PatenteQuestion;
use App\Domains\Patente\Models\PatenteTopic;
use App\Support\Text\TextNormalizer;
use Illuminate\Database\Eloquent\Model;

/**
 * "AI Patente Teacher" (CLAUDE.md s7): explains ONE theory topic or ONE exam question, using only content that is
 * published (for questions that means the licence/rights check passed) and carries a complete https source. Nothing is
 * retrieved from the wider knowledge index, and exam questions never reach the general assistant. The Italian -> Arabic
 * glossary is appended by EXPA itself (deterministic text), not generated by the model.
 */
class PatenteTeacher
{
    public function __construct(private TextNormalizer $n) {}

    /**
     * @param  array{topic?:?string,question?:?string}  $ctx
     * @return array{sources:list<array>,glossary:list<array{it:string,gloss:string}>}
     */
    public function material(array $ctx, string $locale): array
    {
        $sources = [];
        $texts = [];

        if (filled($ctx['topic'] ?? null)) {
            $t = PatenteTopic::published()->with('translations')->where('slug', $ctx['topic'])->first();
            if ($t && ($s = $this->source($t, 'patente_topic', 'patente/topics', $this->flatten([$t->localized('title'), $t->localized('summary'), $t->localized('body')]), count($sources) + 1))) {
                $sources[] = $s;
                $texts[] = $s['excerpts'][0];
            }
        }

        if (filled($ctx['question'] ?? null)) {
            $q = PatenteQuestion::published()->with(['translations', 'topic.translations'])->where('slug', $ctx['question'])->first();
            if ($q && $q->rightsComplete()) {
                $statement = $q->translation('it')?->statement ?? $q->localized('statement');
                $body = "Statement (as in the exam): {$statement}\nCorrect answer: ".($q->is_true ? 'TRUE' : 'FALSE')."\nExplanation: ".($q->localized('explanation') ?? '');
                if ($s = $this->source($q, 'patente_question', 'patente/questions', $body, count($sources) + 1, $statement)) {
                    $sources[] = $s;
                    $texts[] = $statement.' '.($q->localized('explanation') ?? '');
                }
            }
        }

        return ['sources' => $sources, 'glossary' => $sources ? $this->glossary(implode(' ', $texts), $locale) : []];
    }

    /** Plain-text glossary block appended to the answer (empty string when nothing matches). */
    public function glossaryText(array $glossary): string
    {
        if (! $glossary) {
            return '';
        }

        return "\n\n".__('ai.patente_teacher.glossary_title')."\n".collect($glossary)->map(fn ($g) => "- {$g['it']}: {$g['gloss']}")->implode("\n");
    }

    private function source(Model $item, string $type, string $route, string $body, int $n, ?string $title = null): ?array
    {
        $src = $item->sourcePayload();
        if (blank($src['name']) || ! str_starts_with((string) $src['url'], 'https://') || trim($body) === '') {
            return null;
        }

        return [
            'n' => $n,
            'title' => $title ?? (string) ($item->localized('title') ?? $item->slug),
            'type' => $type,
            'ref' => ['type' => $type, 'slug' => $item->slug, 'route' => $route.'/'.$item->slug],
            'source' => $src,
            'excerpts' => [mb_substr($body, 0, 4000)],
        ];
    }

    /** @param  list<?string>  $parts */
    private function flatten(array $parts): string
    {
        return trim(collect($parts)->filter()->map(fn ($p) => is_array($p) ? json_encode($p, JSON_UNESCAPED_UNICODE) : (string) $p)->implode("\n"));
    }

    /** @return list<array{it:string,gloss:string}> published `patente` vocabulary whose lemma occurs in the text */
    private function glossary(string $text, string $locale): array
    {
        $hay = ' '.$this->n->normalize($text).' ';
        $out = [];
        foreach (ItalianVocabulary::published()->with('translations')->where('category', 'patente')->orderBy('id')->limit(300)->get() as $w) {
            $lemma = $this->n->normalize((string) $w->lemma);
            $gloss = $w->localized('gloss', $locale === 'it' ? 'ar' : $locale);
            if ($lemma !== '' && $gloss && str_contains($hay, ' '.$lemma.' ')) {
                $out[] = ['it' => $w->lemma, 'gloss' => $gloss];
            }
        }

        return array_slice($out, 0, 12);
    }
}
