<?php

namespace Database\Seeders;

use App\Domains\Guides\Models\Guide;
use Illuminate\Database\Seeder;

/**
 * EXPA content expansion V6: fills gaps across existing product categories.
 * Content is original guidance linked to official sources; production remains in review.
 */
class OfficialContentV6Seeder extends Seeder
{
    private const VERIFIED_AT = '2026-10-10';

    public function run(): void
    {
        foreach ($this->items() as $index => $item) {
            $guide = Guide::updateOrCreate(
                ['slug' => $item['slug']],
                [
                    'category' => $item['category'],
                    'italian_term' => $item['italian_term'],
                    'sort_order' => 3000 + ($index * 10),
                    'source_name' => $item['source_name'],
                    'source_url' => $item['source_url'],
                    'source_type' => 'official',
                    'last_verified_at' => self::VERIFIED_AT,
                ]
            );

            $guide->setTranslations($item['translations']);
            $local = app()->environment('local', 'testing');
            $guide->forceFill([
                'status' => $local ? 'published' : 'review',
                'published_at' => $local ? ($guide->published_at ?? now()) : null,
            ])->save();
        }
    }

    private function tr(array $ar, array $en, array $it): array
    {
        return ['ar' => $ar, 'en' => $en, 'it' => $it];
    }

    private function guide(string $title, string $summary, string $what, string $who, array $docs, array $steps, string $where, string $cost, string $time, string $body): array
    {
        return compact('title', 'summary', 'what', 'who', 'docs', 'steps', 'where', 'cost', 'time', 'body');
    }

    private function items(): array
    {
        return [
            [
                'slug' => 'permesso-soggiorno-renewal-checklist',
                'category' => 'immigration',
                'italian_term' => 'Rinnovo del permesso di soggiorno',
                'source_name' => 'Portale Immigrazione',
                'source_url' => 'https://www.portaleimmigrazione.it/',
                'translations' => $this->tr(
                    $this->guide('تجديد تصريح الإقامة: قائمة التحضير', 'جهّز ملف التجديد وتحقق من القناة المناسبة لحالتك قبل إرسال الطلب.', 'تجديد permesso di soggiorno يعتمد على نوع التصريح وسبب الإقامة. هذه قائمة تحضير عامة وليست بديلًا عن تعليمات نوع التصريح المحدد.', 'الأشخاص الذين يقترب موعد انتهاء تصريح إقامتهم أو يحتاجون إلى فهم الخطوة التالية بعد تقديم الطلب.', ['جواز سفر ساري ونسخة من الصفحات المطلوبة', 'تصريح الإقامة الحالي ونسخة منه', 'إيصال الطلب السابق عند وجوده', 'Codice Fiscale وإثبات السكن عند طلبهما', 'مستندات العمل أو الدراسة أو الدخل المطلوبة لنوع التصريح'], [['حدد نوع التصريح وسبب التجديد', 'تحقق من قائمة المستندات الخاصة بنوع تصريحك؛ لا تستخدم قائمة عامة وحدها.'], ['راجع التعليمات الرسمية', 'استخدم Portale Immigrazione أو تعليمات Questura المختصة لتحديد النموذج والقناة.'], ['جهّز النسخ والإثباتات', 'طابق الأسماء والتواريخ والبيانات بين المستندات قبل التقديم.'], ['احتفظ بالإيصال وتابع الموعد', 'احتفظ بإثبات الإرسال وأي موعد أو رمز متابعة، وراجع تعليمات البصمات إن طُلبت.']], 'Portale Immigrazione وQuestura المختصة، وقد تختلف القناة حسب نوع التصريح.', 'الرسوم تختلف حسب نوع التصريح والإجراء. تحقق من المبالغ الحالية في التعليمات الرسمية قبل الدفع.', 'تختلف المدة حسب Questura ونوع الطلب والضغط على المواعيد؛ لا تعتمد على تقدير ثابت.', 'إذا انتهت صلاحية التصريح أو تغيرت ظروفك، اطلب توجيهًا من جهة رسمية أو patronato مؤهل. لا تعتمد على نصائح عامة في الحالات المعقدة.'),
                    $this->guide('Residence permit renewal: preparation checklist', 'Prepare your renewal file and confirm the correct channel for your specific status before submitting.', 'Renewal of an Italian permesso di soggiorno depends on the permit type and reason for residence. This is a general preparation checklist, not a substitute for the rules for your permit.', 'People whose residence permit is approaching expiry or who need to understand the next step after filing.', ['Valid passport and required copies', 'Current residence permit and copy', 'Previous application receipt, if applicable', 'Codice Fiscale and proof of accommodation if requested', 'Work, study or income evidence required for the permit type'], [['Identify your permit type', 'Check the document list for your exact permit; do not rely on a generic checklist alone.'], ['Check official instructions', 'Use Portale Immigrazione or the competent Questura instructions to confirm forms and filing channel.'], ['Prepare copies and evidence', 'Check names, dates and details across documents before submitting.'], ['Keep the receipt and track the appointment', 'Keep filing proof and any appointment or tracking details; follow fingerprint instructions if issued.']], 'Portale Immigrazione and the competent Questura; the channel can vary by permit type.', 'Fees vary by permit and procedure. Check current official instructions before paying.', 'Timing depends on the Questura, permit type and appointment demand; there is no reliable universal estimate.', 'If your permit has expired or your circumstances have changed, seek guidance from an official office or qualified patronato. Complex cases need case-specific advice.'),
                    $this->guide('Rinnovo del permesso di soggiorno: checklist', 'Prepara la pratica di rinnovo e verifica il canale corretto per la tua situazione prima dell’invio.', 'Il rinnovo del permesso di soggiorno dipende dal tipo di permesso e dal motivo del soggiorno. Questa è una lista generale, non sostituisce le istruzioni specifiche.', 'Persone con permesso in scadenza o che devono capire il passo successivo dopo la presentazione.', ['Passaporto valido e copie richieste', 'Permesso attuale e copia', 'Ricevuta della domanda precedente, se pertinente', 'Codice Fiscale e prova dell’alloggio se richiesti', 'Documenti di lavoro, studio o reddito previsti per il tipo di permesso'], [['Individua il tipo di permesso', 'Controlla l’elenco relativo al tuo caso; una lista generica non basta.'], ['Consulta le istruzioni ufficiali', 'Usa Portale Immigrazione o le indicazioni della Questura competente.'], ['Prepara copie e prove', 'Controlla nomi, date e dati prima dell’invio.'], ['Conserva la ricevuta', 'Tieni la prova d’invio e segui le indicazioni per appuntamento e impronte, se previste.']], 'Portale Immigrazione e Questura competente; la procedura varia in base al permesso.', 'Costi e contributi variano. Verifica gli importi aggiornati nelle istruzioni ufficiali.', 'I tempi dipendono dalla Questura, dal tipo di pratica e dalla disponibilità degli appuntamenti.', 'In caso di scadenza o cambiamenti della situazione personale, chiedi indicazioni a un ufficio competente o a un patronato qualificato.')
                ),
            ],
            [
                'slug' => 'codice-fiscale-request-and-corrections',
                'category' => 'documents',
                'italian_term' => 'Attribuzione o correzione del codice fiscale',
                'source_name' => 'Agenzia delle Entrate',
                'source_url' => 'https://www.agenziaentrate.gov.it/portale/schede/istanze/richiesta-ts_cf/come-richiedere-il-codice-fiscale',
                'translations' => $this->tr(
                    $this->guide('طلب Codice Fiscale أو تصحيح بياناته', 'تعرف على الجهة التي تصدر الرقم الضريبي وما الذي تفعله إذا كانت بياناتك غير صحيحة.', 'Codice Fiscale رمز تعريفي تستخدمه جهات عامة وخاصة في إيطاليا. يجب أن تتطابق بياناته مع وثائق الهوية، وقد تحتاج إلى طلب تصحيح عند وجود اختلاف.', 'القادمون الجدد، ومن يحتاجون إلى الرقم لأول مرة، أو اكتشفوا خطأ في الاسم أو تاريخ الميلاد.', ['جواز سفر أو وثيقة هوية', 'نموذج الطلب الرسمي عند الحاجة', 'تصريح الإقامة أو مستند يوضح سبب الإقامة إذا طُلب', 'مستند يثبت البيانات الصحيحة عند طلب التصحيح'], [['حدد هل تحتاج إصدارًا أم تصحيحًا', 'تحقق من الإجراء المناسب بدل طلب رقم جديد دون داعٍ.'], ['راجع تعليمات Agenzia delle Entrate', 'اتبع قائمة المستندات وطريقة التقديم الخاصة بحالتك.'], ['قارن البيانات حرفيًا', 'انتبه لترتيب الاسم وتاريخ الميلاد والجنسية كما تظهر في الوثائق الرسمية.'], ['احتفظ بالمستند الصادر', 'احتفظ بالشهادة أو بطاقة البيانات واستخدم الرقم نفسه في معاملاتك.']], 'Agenzia delle Entrate؛ قد توجد قنوات مختلفة حسب مكانك ووضعك.', 'الإصدار العادي للرقم الضريبي مجاني عادةً؛ تحقق من القناة الرسمية ولا تدفع لوسيط غير موثوق.', 'المدة تختلف حسب المكتب وطريقة التقديم واكتمال المستندات.', 'لا تنشئ حسابات متعددة بأرقام مختلفة. إذا وجدت رقمين أو تعارضًا في البيانات، اطلب التحقق والتصحيح من الجهة المختصة.'),
                    $this->guide('Requesting or correcting your Codice Fiscale', 'Find the correct authority for a tax code and learn what to do if your personal details are wrong.', 'The Codice Fiscale is an identifier used by public and private organisations in Italy. Its details should match your identity documents; errors may require a correction request.', 'New arrivals applying for the code for the first time, or anyone who finds an error in their name or date of birth.', ['Passport or identity document', 'Official request form where required', 'Residence permit or evidence of the reason for stay if requested', 'Evidence supporting the correct details for a correction'], [['Identify whether you need a first issue or correction', 'Confirm the right procedure instead of requesting another code unnecessarily.'], ['Read Agenzia delle Entrate instructions', 'Follow the document list and submission method for your situation.'], ['Compare personal details carefully', 'Check name order, date of birth and nationality against official documents.'], ['Keep the issued record', 'Keep the certificate or card and use the same code for your transactions.']], 'Agenzia delle Entrate; channels may vary by location and status.', 'Ordinary issuance is generally free; use official channels and avoid untrusted intermediaries.', 'Timing varies by office, filing channel and document completeness.', 'Do not create multiple accounts with different codes. If you find duplicate codes or conflicting details, request verification and correction from the competent authority.'),
                    $this->guide('Richiesta o correzione del Codice Fiscale', 'Scopri a quale ufficio rivolgerti e come procedere se i dati del codice fiscale sono errati.', 'Il Codice Fiscale identifica la persona nei rapporti con enti pubblici e privati. I dati devono corrispondere ai documenti d’identità; gli errori possono richiedere una correzione.', 'Chi arriva in Italia e richiede il codice per la prima volta o rileva errori nei dati personali.', ['Passaporto o documento d’identità', 'Modulo ufficiale, se richiesto', 'Permesso di soggiorno o prova del motivo del soggiorno, se richiesti', 'Documenti che dimostrano i dati corretti in caso di rettifica'], [['Individua la procedura', 'Verifica se serve una prima attribuzione o una correzione.'], ['Consulta Agenzia delle Entrate', 'Segui elenco documenti e modalità per il tuo caso.'], ['Controlla i dati', 'Confronta ordine del nome, data di nascita e cittadinanza con i documenti ufficiali.'], ['Conserva il documento', 'Conserva l’attestazione e usa lo stesso codice nelle pratiche.']], 'Agenzia delle Entrate; le modalità possono cambiare in base al luogo e alla situazione.', 'L’attribuzione ordinaria è generalmente gratuita; usa canali ufficiali.', 'I tempi variano secondo ufficio, canale e completezza dei documenti.', 'Non creare più codici o account. In caso di duplicati o dati discordanti, chiedi verifica e rettifica all’ufficio competente.')
                ),
            ],
            [
                'slug' => 'patente-b-driving-exam-roadmap',
                'category' => 'driving',
                'italian_term' => 'Patente B: percorso per l’esame',
                'source_name' => 'Ministero delle Infrastrutture e dei Trasporti',
                'source_url' => 'https://www.ilportaledellautomobilista.it/',
                'translations' => $this->tr(
                    $this->guide('رخصة القيادة B: خطوات الاستعداد للامتحان', 'خريطة عامة للتسجيل والمذاكرة والامتحان النظري والعملي مع روابط رسمية.', 'Patente B هي رخصة قيادة السيارات ضمن الشروط المحددة بالقانون. إجراءات التسجيل والاختبارات والوثائق والرسوم يجب تأكيدها من Motorizzazione أو مدرسة قيادة معتمدة.', 'من يستعد للحصول على رخصة B لأول مرة أو يريد فهم تسلسل الخطوات.', ['وثيقة هوية سارية', 'Codice Fiscale', 'شهادة طبية وفق المتطلبات الحالية', 'صور أو نماذج مطلوبة حسب جهة التقديم', 'مستندات الإقامة عند انطباقها'], [['تحقق من الأهلية والمتطلبات', 'راجع Portale dell’Automobilista أو Motorizzazione لمعرفة القواعد الحالية.'], ['اختر مدرسة قيادة أو التقديم الذاتي', 'اسأل عن الخدمات المشمولة والتكاليف والمواعيد قبل التسجيل.'], ['استعد للنظري من مواد مرخصة ومحدثة', 'تدرّب على الإشارات والأولوية والسلامة، وتحقق من أحدث صيغة للاختبار.'], ['احجز العملي بعد استيفاء الشروط', 'اتبع متطلبات التدريب والمدة وعدد المحاولات وفق القواعد الحالية.'], ['تحقق من صلاحية الرخصة وتجديدها', 'بعد النجاح، احتفظ بالوثائق وتابع تاريخ الانتهاء والفحوص المطلوبة.']], 'Portale dell’Automobilista وMotorizzazione Civile أو مدرسة قيادة مرخصة.', 'تختلف الرسوم بحسب التسجيل والاختبارات والدروس والمدرسة. اطلب قائمة مكتوبة بالتكاليف.', 'تعتمد المواعيد على المكتب والمنطقة وتوافر الاختبارات.', 'هذا الدليل لا يغني عن دراسة قواعد المرور الرسمية. لا تستخدم مواد اختبار غير مرخصة أو إجابات قديمة، وتحقق من القواعد التي تسري وقت تقديمك.'),
                    $this->guide('Patente B: roadmap to the driving exam', 'A general roadmap for registration, study, theory and practical tests, with official links.', 'The Patente B allows driving cars subject to legal requirements. Confirm current registration, test, document and fee rules with the Motorizzazione or a licensed driving school.', 'People preparing for a first category B licence or trying to understand the steps.', ['Valid identity document', 'Codice Fiscale', 'Medical certificate under current requirements', 'Required photos or forms, depending on the channel', 'Residence documents where applicable'], [['Check eligibility and requirements', 'Consult Portale dell’Automobilista or the Motorizzazione for current rules.'], ['Choose a driving school or self-application route', 'Ask which services are included, the costs and appointment process before enrolling.'], ['Study with current authorised material', 'Practise road signs, right of way and safety, and check the current exam format.'], ['Book the practical test when eligible', 'Follow current training, timing and attempt requirements.'], ['Track licence validity', 'After passing, keep your documents and note expiry and medical renewal requirements.']], 'Portale dell’Automobilista, Motorizzazione Civile or a licensed driving school.', 'Fees vary by registration, tests, lessons and school. Request an itemised written quote.', 'Appointments depend on the local office and test availability.', 'This guide does not replace official road-rule study. Avoid unlicensed or outdated test materials and verify the rules in force when you apply.'),
                    $this->guide('Patente B: percorso per l’esame', 'Una panoramica su iscrizione, studio, prova teorica e pratica con collegamenti ufficiali.', 'La patente B consente di guidare autovetture nel rispetto dei requisiti di legge. Verifica le regole aggiornate con Motorizzazione o autoscuola autorizzata.', 'Chi prepara la prima patente B o vuole capire l’ordine dei passaggi.', ['Documento d’identità valido', 'Codice Fiscale', 'Certificato medico secondo i requisiti vigenti', 'Foto o moduli richiesti dalla procedura', 'Documenti di soggiorno, se applicabili'], [['Verifica requisiti e regole', 'Consulta Portale dell’Automobilista o Motorizzazione.'], ['Scegli autoscuola o privatista', 'Chiedi servizi inclusi, costi e modalità degli appuntamenti.'], ['Studia con materiali aggiornati e autorizzati', 'Esercitati su segnali, precedenze e sicurezza; verifica il formato attuale.'], ['Prenota la pratica quando ne hai diritto', 'Segui i requisiti vigenti per esercitazioni, tempi e tentativi.'], ['Controlla la validità della patente', 'Dopo il superamento, conserva i documenti e annota scadenza e visite richieste.']], 'Portale dell’Automobilista, Motorizzazione Civile o autoscuola autorizzata.', 'I costi variano per iscrizione, esami, lezioni e autoscuola. Chiedi un preventivo dettagliato.', 'Le attese dipendono dall’ufficio locale e dalla disponibilità degli esami.', 'La guida non sostituisce lo studio delle regole ufficiali. Evita materiale non autorizzato o non aggiornato.')
                ),
            ],
            [
                'slug' => 'choose-family-doctor-roma',
                'category' => 'healthcare',
                'italian_term' => 'Scelta del medico di medicina generale',
                'source_name' => 'Ministero della Salute',
                'source_url' => 'https://www.salute.gov.it/',
                'translations' => $this->tr(
                    $this->guide('اختيار طبيب الأسرة في إيطاليا', 'ما الذي تفعله بعد التسجيل الصحي للعثور على طبيب الأسرة المناسب في منطقتك.', 'Medico di medicina generale أو medico di base هو طبيب الرعاية الأولية للمسجلين المؤهلين في SSN. الاختيار والتغيير يتمان وفق الإجراءات المحلية وتوافر الأطباء.', 'المسجلون في SSN الذين يحتاجون إلى اختيار طبيب أو تغييره أو معرفة كيفية الوصول إلى الخدمات المحلية.', ['Codice Fiscale أو Tessera Sanitaria', 'وثيقة هوية', 'بيانات التسجيل في SSN', 'عنوان الإقامة أو السكن إذا طُلب'], [['تحقق من تسجيلك في SSN', 'إذا لم يكن التسجيل مكتملًا، اتبع دليل التسجيل أولًا.'], ['افتح موقع ASL المحلي', 'ابحث عن قائمة الأطباء المتاحين وطريقة الاختيار أو التغيير.'], ['قدّم الطلب بالقناة المحددة', 'قد تكون الخدمة عبر الإنترنت أو في المكتب، حسب المنطقة.'], ['احفظ بيانات الطبيب', 'تحقق من ساعات الاستقبال وطريقة طلب الزيارة والوصفات والإحالات.']], 'ASL المختصة بمنطقتك؛ في روما استخدم خدمات ASL Roma التابعة لمنطقة سكنك.', 'اختيار الطبيب ضمن الخدمة العامة لا يعني أن كل خدمة صحية مجانية؛ قد تطبق قواعد التذاكر الصحية على بعض الخدمات.', 'يعتمد الاختيار على توفر الأطباء والإجراء المحلي.', 'في حالة الطوارئ لا تنتظر موعد طبيب الأسرة؛ استخدم خدمات الطوارئ المناسبة. هذا الدليل إداري وليس تشخيصًا طبيًا.'),
                    $this->guide('Choosing a family doctor in Italy', 'What to do after SSN registration to find an available primary-care doctor in your area.', 'A medico di medicina generale (medico di base) provides primary care to eligible SSN members. Selection and changes follow local procedures and doctor availability.', 'People registered with the SSN who need to select or change a doctor or understand local access.', ['Codice Fiscale or Tessera Sanitaria', 'Identity document', 'SSN registration details', 'Residence or domicile information if requested'], [['Confirm SSN registration', 'If registration is incomplete, follow the registration guide first.'], ['Open your local ASL website', 'Find the available doctor list and the selection or change procedure.'], ['Submit through the stated channel', 'The service may be online or in person depending on the area.'], ['Save the doctor’s details', 'Check office hours and how to request visits, prescriptions and referrals.']], 'The ASL serving your area; in Rome, use the ASL Roma services for your district.', 'Primary-care selection does not mean every healthcare service is free; co-payments may apply to some services.', 'Selection depends on local procedure and doctor availability.', 'For emergencies, do not wait for a family-doctor appointment; use the appropriate emergency service. This is administrative guidance, not a diagnosis.'),
                    $this->guide('Scegliere il medico di base in Italia', 'Come trovare un medico disponibile dopo l’iscrizione al SSN.', 'Il medico di medicina generale assiste gli iscritti aventi diritto al SSN. Scelta e cambio seguono procedure locali e disponibilità dei medici.', 'Persone iscritte al SSN che devono scegliere o cambiare medico o capire come accedere ai servizi.', ['Codice Fiscale o Tessera Sanitaria', 'Documento d’identità', 'Dati di iscrizione al SSN', 'Residenza o domicilio, se richiesti'], [['Verifica l’iscrizione al SSN', 'Se non è completa, segui prima la procedura d’iscrizione.'], ['Consulta il sito della ASL', 'Cerca elenco dei medici e modalità di scelta o cambio.'], ['Invia la richiesta', 'Il servizio può essere online o allo sportello secondo la zona.'], ['Conserva i riferimenti', 'Controlla orari e modalità per visite, ricette e impegnative.']], 'ASL competente; a Roma usa i servizi della ASL Roma della tua zona.', 'La scelta del medico non rende gratuite tutte le prestazioni: per alcuni servizi possono essere previsti ticket.', 'Dipende dalla procedura locale e dalla disponibilità.', 'In emergenza non attendere l’appuntamento con il medico di base. Questa guida è amministrativa, non una diagnosi.')
                ),
            ],
            [
                'slug' => 'residenza-anagrafica-change-address',
                'category' => 'daily_life',
                'italian_term' => 'Iscrizione anagrafica e cambio di residenza',
                'source_name' => 'ANPR',
                'source_url' => 'https://www.anagrafenazionale.interno.it/',
                'translations' => $this->tr(
                    $this->guide('تسجيل السكن وتغيير العنوان', 'افهم الفرق بين عنوان السكن المسجل والعنوان الفعلي، وكيفية تقديم طلب تغيير الإقامة البلدية.', 'Residenza anagrafica هي الإقامة المسجلة لدى البلدية. الإجراء يعتمد على الانتقال الفعلي وشروط البلدية، وقد تتبع الطلب مراجعات للتحقق من السكن.', 'من انتقل إلى عنوان جديد داخل إيطاليا أو يحتاج إلى تحديث الإقامة البلدية.', ['وثائق الهوية لكل مقدم طلب', 'Codice Fiscale', 'بيانات العنوان الجديد ورقم الوحدة', 'مستندات الإقامة للأجانب عند طلبها', 'معلومات أو إقرار يثبت حق إشغال السكن وفق النموذج'], [['تحقق من خدمة البلدية أو ANPR', 'اعرف هل يمكن تقديم الطلب إلكترونيًا في حالتك وما البيانات المطلوبة.'], ['أدخل العنوان بدقة', 'تحقق من اسم الشارع ورقم المبنى والدرج والشقة وأفراد الأسرة المشمولين.'], ['أرسل الطلب واحتفظ بالإيصال', 'احتفظ برقم البروتوكول وأي إشعار من البلدية.'], ['تابع التحقق', 'قد تتحقق البلدية من الإقامة الفعلية؛ أجب عن الطلبات الرسمية في المواعيد المحددة.']], 'بوابة ANPR أو Ufficio Anagrafe في البلدية المختصة.', 'الخدمة البلدية نفسها لا تتطلب عادةً رسومًا، لكن تحقق من متطلبات الخدمة المحلية.', 'تختلف المدد بحسب البلدية والتحقق من العنوان واكتمال الطلب.', 'لا تسجل عنوانًا لا تقيم فيه فعليًا. الإقامة البلدية قد تؤثر في مراسلات وخدمات أخرى، لكن لكل خدمة قواعدها الخاصة.'),
                    $this->guide('Registering or changing your residence address', 'Understand registered residence and how to submit a municipal change-of-address request.', 'Residenza anagrafica is the address recorded by the municipality. The procedure depends on an actual move and local requirements; checks may be carried out.', 'People who have moved to a new address in Italy or need to update their municipal registration.', ['Identity documents for applicants', 'Codice Fiscale', 'New address and unit details', 'Residence documents for foreign nationals if requested', 'Evidence or declaration of the right to occupy the property under the form'], [['Check the municipality or ANPR service', 'Confirm whether online filing is available for your case and what details are required.'], ['Enter the address accurately', 'Check street, building number, staircase, apartment and household members.'], ['Submit and keep the receipt', 'Keep the protocol number and any municipal notices.'], ['Follow verification', 'The municipality may verify actual residence; respond to official requests on time.']], 'ANPR portal or the Ufficio Anagrafe of the competent municipality.', 'The municipal service is generally free, but check local service requirements.', 'Timing varies by municipality, address verification and application completeness.', 'Do not register at an address where you do not actually live. Residence registration can affect other services, each of which may have separate rules.'),
                    $this->guide('Iscrizione anagrafica e cambio di residenza', 'Come aggiornare l’indirizzo registrato presso il Comune dopo un trasferimento effettivo.', 'La residenza anagrafica è l’indirizzo registrato dal Comune. La procedura richiede un trasferimento effettivo e può prevedere verifiche.', 'Chi si trasferisce a un nuovo indirizzo in Italia o deve aggiornare l’iscrizione comunale.', ['Documenti d’identità dei richiedenti', 'Codice Fiscale', 'Indirizzo nuovo e dati dell’unità abitativa', 'Documenti di soggiorno per cittadini stranieri, se richiesti', 'Dichiarazione o prova del titolo di occupazione prevista dal modulo'], [['Consulta Comune o ANPR', 'Verifica se puoi presentare la domanda online e quali dati servono.'], ['Inserisci l’indirizzo esatto', 'Controlla via, numero civico, scala, interno e componenti coinvolti.'], ['Invia e conserva la ricevuta', 'Conserva numero di protocollo e comunicazioni del Comune.'], ['Segui le verifiche', 'Il Comune può verificare la dimora effettiva; rispondi alle richieste ufficiali.']], 'Portale ANPR o Ufficio Anagrafe del Comune competente.', 'Il servizio comunale è generalmente gratuito; verifica eventuali requisiti locali.', 'I tempi dipendono dal Comune, dalle verifiche e dalla completezza della domanda.', 'Non dichiarare una residenza in cui non vivi realmente. Altri servizi possono applicare regole specifiche.')
                ),
            ],
            [
                'slug' => 'university-scholarships-italy',
                'category' => 'study',
                'italian_term' => 'Borse di studio universitarie e diritto allo studio',
                'source_name' => 'Universitaly',
                'source_url' => 'https://www.universitaly.it/',
                'translations' => $this->tr(
                    $this->guide('المنح الجامعية والدعم الدراسي في إيطاليا', 'كيف تبحث عن منح الجامعة والدعم الإقليمي وتجهز الطلب دون تفويت المواعيد.', 'تختلف المنح بحسب الجامعة والإقليم والسنة الدراسية ووضع الطالب الاقتصادي والأكاديمي. لا توجد قاعدة واحدة أو موعد موحد لجميع المؤسسات.', 'الطلاب المحتملون والطلاب المسجلون الذين يريدون البحث عن إعفاءات الرسوم أو المنح أو السكن الجامعي.', ['جواز السفر ووثائق الإقامة عند انطباقها', 'شهادة التسجيل أو القبول حسب المرحلة', 'بيانات الدخل والأصول للأسرة وفق متطلبات الجهة', 'ترجمات وتصديقات للوثائق الأجنبية إذا طلبت', 'الدرجات أو السجل الأكاديمي عند طلبه'], [['حدد الجامعة والإقليم', 'ابدأ من موقع الجامعة والجهة الإقليمية المختصة بالحق في الدراسة.'], ['اقرأ إعلان السنة الحالية', 'تحقق من الأهلية والمواعيد والحدود الاقتصادية والائتمانية المطلوبة.'], ['جهز وثائق الأسرة والاقتصاد', 'اتبع تعليمات الوثائق الأجنبية والترجمة والتصديق بدقة.'], ['قدّم قبل الموعد واحتفظ بالإثبات', 'احفظ رقم الطلب وتحقق من القوائم المؤقتة والنهائية والطلبات الناقصة.']], 'موقع الجامعة والجهة الإقليمية للحق في الدراسة؛ Universitaly يساعد في البحث عن البرامج وليس بديلًا عن إعلان المنحة.', 'التقديم قد يكون مجانيًا أو يتضمن تكاليف مستندات وترجمة؛ راجع الإعلان الرسمي.', 'المواعيد والنتائج تحددها كل جهة للسنة الدراسية المعنية.', 'لا تفترض أن ISEE العادي يكفي لكل طالب أجنبي؛ قد توجد متطلبات ISEE parificato أو وثائق دخل أجنبية حسب الإعلان.'),
                    $this->guide('University scholarships and student support in Italy', 'Find university and regional support opportunities and prepare an application without missing deadlines.', 'Scholarships depend on the university, region, academic year and the student’s financial and academic status. There is no single rule or deadline for all institutions.', 'Prospective and enrolled students looking for fee waivers, scholarships or student housing.', ['Passport and residence documents where applicable', 'Enrolment or admission evidence, depending on stage', 'Household income and asset information required by the authority', 'Translations and legalisation of foreign documents if requested', 'Academic transcripts or grades where required'], [['Identify the university and region', 'Start with the university website and the regional right-to-study authority.'], ['Read the current-year call', 'Check eligibility, deadlines, financial thresholds and credit requirements.'], ['Prepare household and financial evidence', 'Follow rules for foreign documents, translations and legalisation.'], ['Submit on time and keep proof', 'Save the application number and check provisional/final rankings and requests for missing documents.']], 'University website and regional right-to-study body; Universitaly helps explore programmes but does not replace scholarship calls.', 'Applications may be free, but document, translation or certification costs can apply. Check the official call.', 'Deadlines and results are set by each authority for the relevant academic year.', 'Do not assume an ordinary ISEE is sufficient for every international student; ISEE parificato or foreign income documents may be required by the current call.'),
                    $this->guide('Borse di studio universitarie e diritto allo studio', 'Come cercare agevolazioni universitarie e regionali e preparare la domanda in tempo.', 'Le borse dipendono da università, regione, anno accademico e condizioni economiche e di merito. Non esiste una scadenza unica.', 'Studenti e futuri iscritti che cercano esoneri, borse o alloggi universitari.', ['Passaporto e documenti di soggiorno, se applicabili', 'Ammissione o iscrizione, secondo la fase', 'Dati economici e patrimoniali richiesti', 'Traduzioni e legalizzazioni di documenti esteri, se richieste', 'Carriera o voti, se richiesti'], [['Individua ateneo e regione', 'Consulta sito dell’università ed ente regionale per il diritto allo studio.'], ['Leggi il bando dell’anno corrente', 'Controlla requisiti, scadenze, soglie economiche e crediti.'], ['Prepara i documenti', 'Segui le istruzioni per documenti esteri, traduzioni e legalizzazioni.'], ['Invia entro il termine', 'Conserva il numero domanda e controlla graduatorie e richieste d’integrazione.']], 'Sito dell’ateneo e ente regionale per il diritto allo studio; Universitaly aiuta a cercare corsi ma non sostituisce i bandi.', 'La domanda può essere gratuita, ma possono esserci costi documentali. Controlla il bando.', 'Scadenze e risultati sono stabiliti da ciascun ente per l’anno accademico.', 'Non presumere che basti l’ISEE ordinario: per studenti internazionali possono essere richiesti ISEE parificato o documenti reddituali esteri.')
                ),
            ],
            [
                'slug' => 'employment-payslip-checklist',
                'category' => 'work',
                'italian_term' => 'Lettura della busta paga',
                'source_name' => 'Ministero del Lavoro e delle Politiche Sociali',
                'source_url' => 'https://www.lavoro.gov.it/',
                'translations' => $this->tr(
                    $this->guide('فهم قسيمة الراتب Busta Paga', 'تعرف على أهم البنود التي تراجعها عند استلام الراتب وكيف تحفظ الأدلة إذا وجدت اختلافًا.', 'Busta paga توضح عناصر الأجر والاستقطاعات وبعض بيانات العمل والفترة المدفوعة. تختلف التفاصيل حسب العقد والقطاع والاتفاقية الجماعية CCNL.', 'الموظفون الذين يريدون التحقق من الساعات والأجر والإجازات والخصومات مقارنة بالعقد والعمل الفعلي.', ['عقد العمل أو خطاب التوظيف', 'قسيمة الراتب للشهر المعني', 'سجل ساعات العمل والمناوبات', 'طلبات الإجازة والغياب والمراسلات المتعلقة بها', 'قسائم الأشهر السابقة للمقارنة'], [['راجع الفترة والأجر الأساسي', 'قارن المستوى الوظيفي وساعات العمل ونوع العقد مع المستندات المتاحة.'], ['طابق الساعات والإضافي', 'قارن سجل المناوبات مع الساعات المدفوعة والإضافات أو العمل الليلي إن وجد.'], ['راجع الإجازات والخصومات', 'تحقق من ferie وpermessi والغياب والاستقطاعات التي لا تفهمها.'], ['اطلب توضيحًا كتابيًا', 'أرسل للشركة أو consulente del lavoro الفروقات المحددة واحتفظ بالرد.']], 'صاحب العمل أو مسؤول الرواتب أو consulente del lavoro؛ ويمكن طلب مساعدة نقابية أو patronato عند الحاجة.', 'قد تكون الاستشارة المهنية مدفوعة أو مجانية حسب الجهة؛ اسأل قبل الحجز.', 'موعد التصحيح يعتمد على الشركة وطبيعة الاختلاف. اطلب الرد كتابةً وبأرقام واضحة.', 'لا تعتمد على صافي الراتب وحده للحكم على صحة الحساب. إذا كان هناك نقص متكرر أو تأخير، احتفظ بالعقد والقسائم وسجلات الساعات والمراسلات.'),
                    $this->guide('How to check your Italian payslip (busta paga)', 'Learn the key payslip items and how to document a discrepancy in pay or hours.', 'A busta paga shows pay components, deductions and details for a pay period. The exact layout depends on your contract, sector and collective agreement (CCNL).', 'Employees checking paid hours, wages, leave and deductions against their contract and actual work.', ['Employment contract or hiring letter', 'Payslip for the relevant month', 'Work-hour and shift records', 'Leave requests, absence records and related messages', 'Previous payslips for comparison'], [['Check the period and base pay', 'Compare job level, hours and contract type with your documents.'], ['Reconcile hours and overtime', 'Compare shift records with paid hours, overtime and night-work entries where applicable.'], ['Review leave and deductions', 'Check ferie, permessi, absences and any deductions you do not understand.'], ['Ask for a written explanation', 'Send specific discrepancies to the employer or consulente del lavoro and keep the response.']], 'Employer/payroll office or a consulente del lavoro; a union or patronato may also help.', 'Professional advice may be free or paid depending on the provider; ask before booking.', 'Correction timing depends on the employer and the issue. Ask for a written, itemised response.', 'Net pay alone does not prove that a calculation is correct. For repeated shortfalls or late payment, keep the contract, payslips, hour records and correspondence.'),
                    $this->guide('Come controllare la busta paga', 'I principali elementi da verificare e come documentare differenze di stipendio o ore.', 'La busta paga riepiloga voci retributive, trattenute e dati del periodo. Il formato varia secondo contratto, settore e CCNL.', 'Lavoratori che verificano ore pagate, retribuzione, ferie e trattenute rispetto al contratto e al lavoro svolto.', ['Contratto o lettera di assunzione', 'Busta paga del mese', 'Registro di ore e turni', 'Richieste ferie, assenze e messaggi relativi', 'Buste paga precedenti per confronto'], [['Controlla periodo e paga base', 'Confronta livello, orario e tipo di contratto con i documenti.'], ['Confronta ore e straordinari', 'Verifica turni, ore pagate, straordinari e lavoro notturno se presente.'], ['Controlla ferie e trattenute', 'Esamina ferie, permessi, assenze e trattenute non chiare.'], ['Chiedi spiegazioni scritte', 'Invia le differenze precise al datore o al consulente del lavoro e conserva la risposta.']], 'Datore di lavoro, ufficio paghe o consulente del lavoro; può aiutare anche un sindacato o patronato.', 'La consulenza può essere gratuita o a pagamento secondo il servizio; chiedi prima.', 'I tempi di correzione dipendono dal datore e dal problema. Chiedi una risposta scritta e dettagliata.', 'Il netto da solo non dimostra che il calcolo sia corretto. In caso di differenze ricorrenti conserva contratto, buste paga, ore e comunicazioni.')
                ),
            ],
            [
                'slug' => 'partita-iva-starting-checklist',
                'category' => 'money',
                'italian_term' => 'Apertura della Partita IVA',
                'source_name' => 'Agenzia delle Entrate',
                'source_url' => 'https://www.agenziaentrate.gov.it/portale/web/guest/schede/istanze/aa9_12-inizio-variazione-dati-iva/aa9_12-modello-e-istruzioni',
                'translations' => $this->tr(
                    $this->guide('فتح Partita IVA للعمل الحر', 'قائمة أولية لفهم النشاط ورمز ATECO والنظام الضريبي والاشتراكات قبل فتح الرقم.', 'Partita IVA تُستخدم لممارسة أنشطة مستقلة أو تجارية وفق القواعد الضريبية. اختيار النشاط والنظام والاشتراكات قد يغيّر الالتزامات؛ يجب تحديدها بناءً على نشاطك الفعلي.', 'من يخطط للعمل الحر أو تقديم خدمات أو البيع بشكل مستقل في إيطاليا.', ['وثيقة هوية وCodice Fiscale', 'وصف دقيق للنشاط وطريقة تحقيق الدخل', 'عنوان النشاط وبيانات الاتصال', 'معلومات عن العمل أو التسجيلات السابقة إن وجدت', 'بيانات لازمة لتحديد نظام الضريبة والتسجيلات الاجتماعية'], [['صف نشاطك بدقة', 'لا تختَر رمز ATECO فقط لأنه يبدو أرخص؛ يجب أن يطابق النشاط الفعلي.'], ['قارن الأنظمة الضريبية', 'تحقق من شروط النظام العادي أو forfettario عند انطباقه وحدود الأهلية الحالية.'], ['حدد الاشتراكات والتراخيص', 'اسأل إن كان النشاط يتطلب INPS أو INAIL أو SCIA أو تسجيلًا بالغرفة التجارية.'], ['قدّم الإخطار الصحيح', 'استخدم تعليمات Agenzia delle Entrate واستعن بـ commercialista إذا كانت الحالة مركبة.'], ['نظّم الفواتير والمواعيد', 'حدد طريقة إصدار الفواتير الإلكترونية واحتفظ بالمستندات والتزامات التصريح والدفع.']], 'Agenzia delle Entrate، وقد تحتاج إلى Camera di Commercio أو INPS أو SUAP حسب النشاط.', 'التكلفة والضرائب والاشتراكات تختلف حسب النشاط والنظام والدخل؛ اطلب تقديرًا مكتوبًا من مختص قبل البدء.', 'مدة فتح الرقم ليست هي نفسها مدة استكمال كل التراخيص أو التسجيلات الأخرى.', 'لا تبدأ اعتمادًا على تقدير ضريبي عام. قبل اختيار النظام، احسب الضرائب والاشتراكات والتكاليف المهنية وتأثير أي وظيفة أخرى أو نشاط قائم.'),
                    $this->guide('Starting a Partita IVA for self-employment', 'A preparation checklist covering activity classification, tax regime and social contributions before opening a VAT number.', 'A Partita IVA is used for independent or business activity under Italian tax rules. Activity classification, tax regime and contributions depend on what you actually do.', 'People planning freelance work, services or independent sales in Italy.', ['Identity document and Codice Fiscale', 'Accurate description of the activity and income model', 'Business address and contact details', 'Information about existing work or prior registrations', 'Details needed to determine tax and social-security registration'], [['Describe the activity precisely', 'Do not choose an ATECO code merely because it seems cheaper; it must match the actual activity.'], ['Compare tax regimes', 'Check current eligibility for the ordinary or forfettario regime and any limits.'], ['Identify contributions and licences', 'Check whether INPS, INAIL, SCIA or Chamber of Commerce registration applies.'], ['Submit the correct declaration', 'Follow Agenzia delle Entrate instructions and consult a commercialista for complex cases.'], ['Set up invoicing and deadlines', 'Plan electronic invoicing and keep records for tax returns and payments.']], 'Agenzia delle Entrate; depending on the activity, Camera di Commercio, INPS or SUAP may also be involved.', 'Taxes, contributions and professional costs vary by activity, regime and income. Get a written estimate before starting.', 'Opening the VAT number does not necessarily complete all licences or other registrations.', 'Do not rely on a generic tax estimate. Model taxes, contributions, professional fees and the effect of other employment or existing business activity before choosing a regime.'),
                    $this->guide('Aprire una Partita IVA per lavoro autonomo', 'Checklist iniziale su attività, regime fiscale e contributi prima dell’apertura.', 'La Partita IVA serve per attività autonome o d’impresa secondo le regole fiscali italiane. Codice attività, regime e contributi dipendono dall’attività effettiva.', 'Chi vuole lavorare come freelance, offrire servizi o vendere in autonomia in Italia.', ['Documento d’identità e Codice Fiscale', 'Descrizione precisa dell’attività e del modello di ricavo', 'Indirizzo e recapiti', 'Informazioni su lavoro o registrazioni già esistenti', 'Dati per valutare regime fiscale e iscrizione previdenziale'], [['Descrivi l’attività', 'Il codice ATECO deve corrispondere all’attività effettiva.'], ['Confronta i regimi fiscali', 'Verifica requisiti e limiti aggiornati per regime ordinario o forfettario.'], ['Verifica contributi e autorizzazioni', 'Controlla se servono INPS, INAIL, SCIA o Camera di Commercio.'], ['Presenta la dichiarazione corretta', 'Segui Agenzia delle Entrate e consulta un commercialista per casi complessi.'], ['Organizza fatture e scadenze', 'Pianifica fatturazione elettronica, documenti, dichiarazioni e pagamenti.']], 'Agenzia delle Entrate; secondo l’attività possono servire Camera di Commercio, INPS o SUAP.', 'Imposte, contributi e costi professionali variano. Chiedi una stima scritta prima di iniziare.', 'L’apertura della Partita IVA non completa necessariamente autorizzazioni e altre iscrizioni.', 'Prima di scegliere il regime valuta imposte, contributi, costi professionali ed eventuale lavoro dipendente o attività già esistente.')
                ),
            ],
            [
                'slug' => 'family-marriage-documents-italy',
                'category' => 'family',
                'italian_term' => 'Matrimonio in Italia con cittadino straniero',
                'source_name' => 'Ministero dell’Interno',
                'source_url' => 'https://www.interno.gov.it/',
                'translations' => $this->tr(
                    $this->guide('الزواج في إيطاليا: المستندات الأساسية', 'نظرة عامة على الخطوات الإدارية قبل حجز موعد الزواج، مع ضرورة تأكيد المتطلبات مع البلدية والقنصلية.', 'متطلبات الزواج المدني تختلف بحسب الجنسية والحالة المدنية والبلدية. قد تُطلب وثيقة تثبت عدم وجود مانع للزواج، مع ترجمة وتصديق حسب البلد والوثيقة.', 'الأزواج الذين يخططون للزواج في إيطاليا وكان أحدهما أو كلاهما أجنبيًا.', ['جوازات سفر أو وثائق هوية سارية', 'شهادات الميلاد أو بيانات الحالة المدنية إذا طلبت', 'وثيقة nulla osta أو شهادة أهلية للزواج حسب الجنسية', 'ترجمات وتصديقات أو apostille عند انطباقها', 'بيانات الإقامة والمواعيد المطلوبة من البلدية'], [['اتصل بـ Ufficio di Stato Civile', 'اطلب قائمة المستندات الخاصة بجنسيتيكما ووضعكما المدني.'], ['راجع القنصلية المختصة', 'تحقق من طريقة إصدار nulla osta أو الوثيقة البديلة المطلوبة.'], ['ترجم وصادق على الوثائق', 'لا تفترض أن كل ترجمة أو وثيقة أجنبية تُقبل دون تصديق.'], ['احجز إجراءات النشر أو الموعد', 'اتبع تعليمات البلدية بشأن pubblicazioni والمواعيد والرسوم إن وجدت.']], 'Ufficio di Stato Civile في البلدية التي ستتم فيها الإجراءات، مع مراجعة القنصلية عند الحاجة.', 'قد توجد رسوم للوثائق أو الترجمة أو التصديق؛ البلدية والقنصلية تحددان المطلوب لحالتكما.', 'المدة تعتمد على الحصول على الوثائق الأجنبية ومواعيد البلدية.', 'لا تحجز موعدًا نهائيًا أو ترتب السفر قبل تأكيد قبول المستندات. تختلف المتطلبات حسب الجنسية والاتفاقيات الدولية والحالة المدنية.'),
                    $this->guide('Marriage in Italy: document checklist', 'An overview of administrative steps before booking a wedding appointment. Confirm the requirements with the municipality and consulate.', 'Civil marriage requirements depend on nationality, civil status and municipality. A certificate confirming no impediment to marriage may be required, with translation and legalisation depending on the country and document.', 'Couples planning to marry in Italy where one or both partners are foreign nationals.', ['Valid passports or identity documents', 'Birth or civil-status records if requested', 'Nulla osta or equivalent certificate of capacity to marry, depending on nationality', 'Translations and legalisation or apostille where applicable', 'Residence details and appointment information requested by the municipality'], [['Contact the Ufficio di Stato Civile', 'Ask for the checklist specific to both nationalities and civil statuses.'], ['Check with the competent consulate', 'Confirm how to obtain the nulla osta or required alternative document.'], ['Translate and legalise documents', 'Do not assume every foreign document or translation is accepted without legalisation.'], ['Book the required formalities', 'Follow the municipality’s instructions for pubblicazioni, appointments and any fees.']], 'The Ufficio di Stato Civile of the municipality handling the marriage, and the relevant consulate if needed.', 'Document, translation and legalisation costs may apply; the municipality and consulate determine what is needed.', 'Timing depends on obtaining foreign documents and municipal appointment availability.', 'Do not finalise travel or wedding arrangements before confirming that the documents will be accepted. Requirements vary by nationality, international agreements and civil status.'),
                    $this->guide('Matrimonio in Italia: documenti essenziali', 'Panoramica dei passaggi amministrativi prima di fissare la data. Conferma i requisiti con Comune e consolato.', 'I requisiti del matrimonio civile variano in base a cittadinanza, stato civile e Comune. Può essere richiesto un nulla osta o certificato equivalente, con traduzione e legalizzazione secondo il caso.', 'Coppie che intendono sposarsi in Italia quando uno o entrambi sono cittadini stranieri.', ['Passaporti o documenti validi', 'Certificati di nascita o stato civile se richiesti', 'Nulla osta o certificato di capacità matrimoniale secondo la cittadinanza', 'Traduzioni e legalizzazioni o apostille se necessarie', 'Dati di residenza e appuntamenti richiesti dal Comune'], [['Contatta l’Ufficio di Stato Civile', 'Chiedi l’elenco specifico per entrambe le cittadinanze e gli stati civili.'], ['Verifica con il consolato competente', 'Conferma come ottenere il nulla osta o il documento alternativo.'], ['Traduci e legalizza i documenti', 'Non presumere che ogni documento estero sia accettato senza formalità.'], ['Prenota gli adempimenti', 'Segui le indicazioni comunali su pubblicazioni, appuntamenti e costi.']], 'Ufficio di Stato Civile del Comune competente e consolato, se necessario.', 'Possono esserci costi per documenti, traduzioni e legalizzazioni; verifica con Comune e consolato.', 'I tempi dipendono dai documenti esteri e dalla disponibilità degli appuntamenti.', 'Conferma l’accettazione dei documenti prima di organizzare viaggi o fissare tutto. I requisiti variano per cittadinanza, accordi internazionali e stato civile.')
                ),
            ],
            [
                'slug' => 'rental-home-viewing-checklist',
                'category' => 'housing',
                'italian_term' => 'Controlli prima di affittare una casa',
                'source_name' => 'Agenzia delle Entrate',
                'source_url' => 'https://www.agenziaentrate.gov.it/portale/',
                'translations' => $this->tr(
                    $this->guide('قبل استئجار شقة: قائمة التحقق', 'خطوات لتقليل المفاجآت قبل دفع العربون أو توقيع عقد الإيجار.', 'قبل الاستئجار، تحقق من هوية المؤجر وحقه في التأجير وشروط العقد والتكاليف الإضافية. تختلف الحماية والالتزامات بحسب نوع العقد والوقائع.', 'من يبحث عن غرفة أو شقة أو يغير سكنه داخل إيطاليا.', ['وثيقة هوية الطرف الذي يوقع معك', 'مسودة العقد وشروطه', 'قائمة مكتوبة بالإيجار والمصاريف والوديعة', 'إثباتات الدفع وإيصالات أي مبلغ مقدم', 'محضر حالة العقار وصور عند الاستلام'], [['تحقق من العقار والطرف', 'شاهد العقار وتحقق من هوية المؤجر أو صلاحية الوكيل.'], ['اقرأ التكاليف كاملة', 'اسأل عن المصاريف المشتركة والفواتير والوديعة وشروط استردادها.'], ['راجع العقد والتسجيل', 'تأكد من المدة ونوع العقد والإشعار والالتزام بالتسجيل وفق القواعد.'], ['وثّق التسليم والدفع', 'استخدم وسيلة دفع قابلة للتتبع واحتفظ بالإيصالات وصور حالة العقار.']], 'المؤجر أو الوكالة، وللاستفسارات الضريبية راجع Agenzia delle Entrate أو مختصًا.', 'قد توجد مصاريف وكالة أو تسجيل أو وديعة؛ يجب توضيحها قبل التوقيع.', 'الوقت يعتمد على الاتفاق والتسجيل؛ لا تدفع تحت ضغط قبل التحقق.', 'احذر طلب تحويل الأموال قبل رؤية العقار أو تقديم عقد واضح. هذه قائمة وقائية عامة وليست رأيًا قانونيًا في عقد بعينه.'),
                    $this->guide('Rental viewing checklist: before you sign', 'Practical checks to reduce surprises before paying a deposit or signing a lease.', 'Before renting, verify the landlord’s identity and authority, contract terms and extra costs. Rights and obligations depend on the contract type and facts.', 'People searching for a room or apartment or moving within Italy.', ['Identity details of the person signing the lease', 'Draft lease and terms', 'Written breakdown of rent, expenses and deposit', 'Payment evidence and receipts for any advance', 'Property condition report and photos at handover'], [['Verify the property and person', 'View the property and check the landlord’s identity or the agent’s authority.'], ['List all costs', 'Ask about building charges, utilities, deposit and refund conditions.'], ['Review contract and registration', 'Check duration, contract type, notice terms and applicable registration duties.'], ['Document handover and payments', 'Use traceable payments and keep receipts and condition photos.']], 'Landlord or agency; for tax-registration questions, consult Agenzia delle Entrate or a qualified adviser.', 'Agency, registration or deposit costs may apply and should be explained before signing.', 'Timing depends on the agreement and registration. Do not pay under pressure before checking.', 'Be cautious if asked to transfer money before viewing the property or receiving clear written terms. This is general prevention guidance, not legal advice on a specific lease.'),
                    $this->guide('Checklist prima di affittare casa', 'Controlli pratici prima di versare una caparra o firmare il contratto.', 'Prima di affittare, verifica identità e titolo del locatore, condizioni contrattuali e costi aggiuntivi. Diritti e obblighi dipendono dal contratto e dal caso.', 'Chi cerca una stanza o un appartamento o cambia casa in Italia.', ['Dati d’identità di chi firma il contratto', 'Bozza del contratto e condizioni', 'Elenco scritto di canone, spese e deposito', 'Prove di pagamento e ricevute', 'Verbale sullo stato dell’immobile e foto alla consegna'], [['Verifica immobile e interlocutore', 'Visita la casa e controlla identità del locatore o mandato dell’agente.'], ['Chiarisci tutti i costi', 'Chiedi spese condominiali, utenze, deposito e condizioni di restituzione.'], ['Leggi contratto e registrazione', 'Controlla durata, tipo, preavviso e obblighi di registrazione.'], ['Documenta consegna e pagamenti', 'Usa pagamenti tracciabili e conserva ricevute e foto.']], 'Locatore o agenzia; per dubbi fiscali consulta Agenzia delle Entrate o un professionista.', 'Possono esserci costi di agenzia, registrazione o deposito: chiariscili prima di firmare.', 'Dipende dall’accordo e dalla registrazione. Non pagare sotto pressione senza verifiche.', 'Diffida da richieste di bonifico prima della visita o senza condizioni scritte. Guida preventiva generale, non parere legale sul singolo contratto.')
                ),
            ],
            [
                'slug' => 'italian-language-course-levels',
                'category' => 'daily_life',
                'italian_term' => 'Livelli QCER e corsi di italiano',
                'source_name' => 'Ministero dell’Università e della Ricerca',
                'source_url' => 'https://www.universitaly.it/',
                'translations' => $this->tr(
                    $this->guide('اختيار كورس اللغة الإيطالية حسب مستواك', 'افهم مستويات A1 إلى C2 وكيف تختار دورة تناسب هدفك اليومي أو الدراسي أو المهني.', 'يصف الإطار الأوروبي المرجعي للغات (QCER/CEFR) مستويات الكفاءة من A1 إلى C2. قد تستخدم المدارس اختبارات تحديد مستوى مختلفة، لذلك تحقق من وصف الدورة وطريقة التقييم.', 'المقيمون الجدد والطلاب والعاملون الذين يريدون تحسين الإيطالية للمحادثة أو الدراسة أو العمل.', ['تحديد هدفك: محادثة أو عمل أو دراسة أو امتحان', 'نتيجة اختبار تحديد المستوى إن توفرت', 'جدولك الأسبوعي والميزانية', 'أي متطلبات رسمية للامتحان أو الشهادة المستهدفة'], [['حدد هدفًا قابلًا للقياس', 'مثلاً إجراء مكالمة أو فهم تعليمات العمل أو التحضير لشهادة معترف بها.'], ['ابدأ باختبار مستوى', 'استخدم اختبارًا أوليًا ثم تأكد من المستوى مع مدرس أو مؤسسة.'], ['اختر دورة تناسب الوقت', 'قارن ساعات التدريس والمحادثة والواجبات وطريقة المتابعة.'], ['تابع التقدم عمليًا', 'راجع التقدم كل عدة أسابيع وعدّل الدورة إذا كانت سهلة جدًا أو صعبة جدًا.']], 'مدارس اللغة، CPIA، الجامعات أو الدورات المحلية؛ تحقق من الجهة التي تقدم الشهادة إذا كان الاعتراف الرسمي مهمًا.', 'تختلف الدورات المجانية والمدفوعة حسب الجهة والمدينة والمستوى.', 'مدة الوصول إلى المستوى تختلف حسب ساعات الدراسة والخبرة السابقة والممارسة.', 'لا تخلط بين إكمال دورة والحصول على شهادة رسمية. إذا كانت الشهادة مطلوبة للإقامة أو الدراسة أو العمل، تحقق من الجهات المعترف بها والمتطلبات السارية.'),
                    $this->guide('Choosing an Italian course by level', 'Understand CEFR levels A1 to C2 and choose a course for daily life, study or work.', 'The Common European Framework of Reference for Languages (CEFR) describes proficiency from A1 to C2. Providers may use different placement tests, so check course outcomes and assessment.', 'New residents, students and workers improving Italian for conversation, education or employment.', ['A clear goal: conversation, work, study or an exam', 'Placement-test result if available', 'Weekly availability and budget', 'Any formal requirements for a target exam or certificate'], [['Set a measurable goal', 'For example, handle a phone call, understand workplace instructions or prepare for a recognised certificate.'], ['Take a placement test', 'Use an initial test and confirm your level with a teacher or provider.'], ['Choose a realistic course', 'Compare teaching hours, conversation practice, homework and feedback.'], ['Track practical progress', 'Review progress every few weeks and adjust if the course is too easy or too difficult.']], 'Language schools, CPIA, universities or local courses; verify the certifying body if formal recognition matters.', 'Free and paid options vary by provider, city and level.', 'Time to reach a level depends on study hours, prior experience and practice.', 'Completing a course is not the same as receiving an official certificate. If a certificate is required for residence, study or work, verify recognised providers and current requirements.'),
                    $this->guide('Scegliere un corso d’italiano per livello', 'Capire i livelli A1-C2 e scegliere un corso adatto a vita quotidiana, studio o lavoro.', 'Il Quadro Comune Europeo di Riferimento per le Lingue descrive livelli da A1 a C2. I corsi possono usare test diversi: controlla obiettivi e valutazione.', 'Nuovi residenti, studenti e lavoratori che vogliono migliorare l’italiano.', ['Obiettivo: conversazione, lavoro, studio o esame', 'Risultato di un test di livello, se disponibile', 'Tempo settimanale e budget', 'Requisiti formali per l’esame o certificato desiderato'], [['Definisci un obiettivo concreto', 'Per esempio gestire una telefonata o capire istruzioni sul lavoro.'], ['Fai un test iniziale', 'Conferma il livello con un docente o un ente.'], ['Scegli un corso sostenibile', 'Confronta ore, conversazione, compiti e feedback.'], ['Controlla i progressi', 'Rivaluta ogni alcune settimane e cambia livello se necessario.']], 'Scuole di lingua, CPIA, università o corsi locali; verifica l’ente certificatore se serve riconoscimento formale.', 'Le opzioni gratuite e a pagamento variano per ente, città e livello.', 'I tempi dipendono da ore di studio, esperienza e pratica.', 'Finire un corso non equivale a ottenere una certificazione ufficiale. Se serve per soggiorno, studio o lavoro, verifica enti riconosciuti e requisiti vigenti.')
                ),
            ],
        ];
    }
}
