<?php

namespace Database\Seeders;

use App\Domains\Geo\Models\City;
use App\Domains\Jobs\Models\JobListing;
use App\Domains\Jobs\Models\JobSource;
use Illuminate\Database\Seeder;

class VerifiedItalyJobsV2Seeder extends Seeder
{
    /**
     * Second manually verified batch. Keep summaries short and link to the employer's original posting.
     * All records expire quickly and remain hidden outside local/testing until reviewed.
     */
    public function run(): void
    {
        $sourceKey = 'verified-italy-careers-v2';
        $source = JobSource::updateOrCreate(
            ['key' => $sourceKey],
            [
                'name' => 'IKEA, TSMG and Amazon Jobs — manually verified listings',
                'driver' => 'json_feed',
                'config' => null,
                'legal_basis' => 'Manual curation of minimal vacancy metadata from public employer career pages, with direct links to original listings. No full descriptions copied. Re-verify status and URL before production publication.',
                'active' => false,
                'schedule_hours' => 24,
            ],
        );

        $jobs = [
            [
                'id' => 'ikea-368585',
                'title' => 'Stage Supply Chain - IKEA Store',
                'company' => 'IKEA',
                'location' => 'Catania, Sicilia',
                'city' => 'catania',
                'category' => 'logistics',
                'type' => 'internship',
                'remote' => 'onsite',
                'salary_min' => 850,
                'salary_max' => 850,
                'salary_period' => 'month',
                'published_at' => '2026-09-28 00:00:00',
                'url' => 'https://jobs.ikea.com/it/lavoro/catania/stage-supply-chain-ikea-store/24107/101269815136',
                'description' => 'IKEA — six-month in-store logistics internship in Catania focused on warehouse processes, inventory, goods handling and supply-chain performance. The employer lists an €850 gross monthly internship allowance and asks for English at B2 level. Review the official posting for full terms.',
                'skills' => ['logistics', 'inventory', 'supply chain', 'English B2'],
                'italian_level' => null,
                'english_level' => 'b2',
                'experience_years' => 0,
            ],
            [
                'id' => 'ikea-353959',
                'title' => 'Addetto/a alla Logistica - Part time',
                'company' => 'IKEA',
                'location' => 'Afragola, Napoli, Campania',
                'city' => 'afragola',
                'category' => 'logistics',
                'type' => 'part_time',
                'remote' => 'onsite',
                'salary_min' => 23241.12,
                'salary_max' => 23241.12,
                'salary_period' => 'year',
                'published_at' => '2026-09-22 00:00:00',
                'url' => 'https://jobs.ikea.com/it/lavoro/afragola/addetto-a-alla-logistica-part-time/24107/97915402672',
                'description' => 'IKEA — part-time store logistics role in Afragola involving stock availability, loading/unloading, replenishment and order preparation. The employer lists a gross annual salary reference of €23,241.12, prorated to the part-time percentage; fixed-term contract and rotating shifts including weekends. Check the original posting for current availability.',
                'skills' => ['warehouse', 'stock replenishment', 'order picking', 'teamwork'],
                'italian_level' => 'b1',
                'english_level' => null,
                'experience_years' => 0,
            ],
            [
                'id' => 'ikea-353373',
                'title' => 'Addetto/a alla Ristorazione - Part time',
                'company' => 'IKEA',
                'location' => 'Carugate, Milano, Lombardia',
                'city' => 'carugate',
                'category' => 'hospitality',
                'type' => 'part_time',
                'remote' => 'onsite',
                'salary_min' => 23241.12,
                'salary_max' => 23241.12,
                'salary_period' => 'year',
                'published_at' => '2026-10-01 00:00:00',
                'url' => 'https://jobs.ikea.com/it/lavoro/carugate/addetto-a-alla-ristorazione-part-time/24107/97221439232',
                'description' => 'IKEA — part-time restaurant and food-service role in Carugate, serving customers and preparing food in the restaurant, bar and Swedish Food Market. The employer lists a gross annual salary reference of €23,241.12 prorated to the part-time percentage; fixed-term contract with shifts across five days out of seven, including weekends.',
                'skills' => ['food service', 'customer service', 'HACCP', 'teamwork'],
                'italian_level' => 'b1',
                'english_level' => null,
                'experience_years' => 0,
            ],
            [
                'id' => 'tsmg-6517b738-8c37-4799-9607-1f85312959b5',
                'title' => 'AI Tester with Italian Language',
                'company' => 'TSMG',
                'location' => 'Remote, Italy (listed under Rome)',
                'city' => 'roma',
                'category' => 'tech',
                'type' => 'contract',
                'remote' => 'remote',
                'salary_min' => null,
                'salary_max' => null,
                'salary_period' => null,
                'published_at' => '2026-10-10 00:00:00',
                'url' => 'https://jobs.lever.co/tsmg/6517b738-8c37-4799-9607-1f85312959b5',
                'description' => 'TSMG — remote, full-time, project-based role testing and evaluating AI-agent responses. The listing asks for fluent Italian, intermediate English and basic technical confidence; online training is provided. The employer describes the project as lasting several months, depending on progress. No salary is stated.',
                'skills' => ['Italian', 'English', 'AI evaluation', 'quality review'],
                'italian_level' => 'c1',
                'english_level' => 'b1',
                'experience_years' => 0,
            ],
            [
                'id' => 'tsmg-1723fa14-0d88-4197-a959-eda55123d804',
                'title' => 'Speech Recording Participant - Italian Language',
                'company' => 'TSMG',
                'location' => 'Rome, Lazio',
                'city' => 'roma',
                'category' => 'other',
                'type' => 'part_time',
                'remote' => 'onsite',
                'salary_min' => null,
                'salary_max' => null,
                'salary_period' => null,
                'published_at' => '2026-10-10 00:00:00',
                'url' => 'https://jobs.lever.co/tsmg/1723fa14-0d88-4197-a959-eda55123d804',
                'description' => 'TSMG — part-time contract project in Rome for highly proficient Italian speakers to record natural conversations in pairs in a quiet indoor environment. The posting says each participant can take part in only one recording set. Compensation is not stated on the listing.',
                'skills' => ['Italian fluency', 'clear speech', 'conversation'],
                'italian_level' => 'c1',
                'english_level' => null,
                'experience_years' => 0,
            ],
            [
                'id' => 'tsmg-1c90a38d-a707-4cf8-9f31-c936dfd85c17',
                'title' => 'Mapping Data Collection Driver',
                'company' => 'TSMG',
                'location' => 'Rome, Lazio (travel across assigned zones)',
                'city' => 'roma',
                'category' => 'logistics',
                'type' => 'contract',
                'remote' => 'onsite',
                'salary_min' => null,
                'salary_max' => null,
                'salary_period' => null,
                'published_at' => '2026-09-19 00:00:00',
                'url' => 'https://jobs.lever.co/tsmg/1c90a38d-a707-4cf8-9f31-c936dfd85c17',
                'description' => 'TSMG — full-time contract role driving client-provided vehicles fitted with mapping equipment. Requires at least five years of driving experience, including two years professionally, good English and willingness to travel and stay in hotels during assignments. No salary is stated.',
                'skills' => ['professional driving', 'GPS', 'data collection', 'English'],
                'italian_level' => null,
                'english_level' => 'b1',
                'experience_years' => 2,
            ],
            [
                'id' => 'tsmg-acd7f59f-1a8d-460b-b76f-3c4f6ca651ea',
                'title' => 'Field Data Collection Specialist / Surveyor',
                'company' => 'TSMG',
                'location' => 'Rome, Lazio (project travel)',
                'city' => 'roma',
                'category' => 'other',
                'type' => 'contract',
                'remote' => 'onsite',
                'salary_min' => null,
                'salary_max' => null,
                'salary_period' => null,
                'published_at' => '2026-09-19 00:00:00',
                'url' => 'https://jobs.lever.co/tsmg/acd7f59f-1a8d-460b-b76f-3c4f6ca651ea',
                'description' => 'TSMG — field survey role collecting visual and geographic data for mapping projects. Work is Monday to Friday, around six to eight hours daily, with extensive walking. The employer states that paid training, equipment and project travel expenses are provided. Requires fluent English at B1+ and a driving licence.',
                'skills' => ['field research', 'data collection', 'English B1+', 'driving licence'],
                'italian_level' => null,
                'english_level' => 'b1',
                'experience_years' => 0,
            ],
            [
                'id' => 'tsmg-03cfb801-19e5-4e8c-b9c5-4b55c82b19c7',
                'title' => 'Field Operator - Public Transport Survey Project',
                'company' => 'TSMG',
                'location' => 'Rome, Lazio (city-based project)',
                'city' => 'roma',
                'category' => 'other',
                'type' => 'contract',
                'remote' => 'onsite',
                'salary_min' => null,
                'salary_max' => null,
                'salary_period' => null,
                'published_at' => '2026-09-19 00:00:00',
                'url' => 'https://jobs.lever.co/tsmg/03cfb801-19e5-4e8c-b9c5-4b55c82b19c7',
                'description' => 'TSMG — full-time contract field role visiting public-transport stations and routes and recording survey information with company-provided equipment. No technical background is required; training and equipment are provided. The listing asks for good English, attention to detail and comfort walking six to eight hours per day.',
                'skills' => ['field surveys', 'public transport', 'mobile apps', 'English'],
                'italian_level' => null,
                'english_level' => 'b1',
                'experience_years' => 0,
            ],
            [
                'id' => 'amazon-10458966',
                'title' => 'Robotics Deployment Engineer — Delivery & Packaging Innovation',
                'company' => 'Amazon',
                'location' => 'Italy / South Europe (multi-site)',
                'city' => null,
                'category' => 'tech',
                'type' => 'full_time',
                'remote' => 'onsite',
                'salary_min' => null,
                'salary_max' => null,
                'salary_period' => null,
                'published_at' => '2026-10-08 00:00:00',
                'url' => 'https://amazon.jobs/en/jobs/10458966/robotics-deployment-engineer-robotics-delivery-packaging-innovation',
                'description' => 'Amazon Development Centre Italy — engineering role delivering large-scale logistics automation, robotics and storage initiatives across the South Europe fulfilment network. Requires engineering/project-delivery experience and strong technical problem-solving. The official page does not state a salary in the summary reviewed.',
                'skills' => ['robotics', 'automation', 'engineering', 'project delivery'],
                'italian_level' => null,
                'english_level' => null,
                'experience_years' => 3,
            ],
        ];

        $publishLocally = app()->environment('local', 'testing');

        foreach ($jobs as $job) {
            $cityId = $job['city'] ? City::where('slug', $job['city'])->value('id') : null;
            $attrs = [
                'job_source_id' => $source->id,
                'external_id' => $job['id'],
                'title' => $job['title'],
                'company' => $job['company'],
                'city_id' => $cityId,
                'location_text' => $job['location'],
                'remote_mode' => $job['remote'],
                'employment_type' => $job['type'],
                'category' => $job['category'],
                'salary_min' => $job['salary_min'],
                'salary_max' => $job['salary_max'],
                'salary_currency' => 'EUR',
                'salary_period' => $job['salary_period'],
                'italian_level' => $job['italian_level'],
                'english_level' => $job['english_level'],
                'experience_years' => $job['experience_years'],
                'skills' => $job['skills'],
                'description' => $job['description'],
                'apply_url' => $job['url'],
                'visa_sponsorship_stated' => false,
                'published_at' => $job['published_at'],
                'expires_at' => '2026-10-24 23:59:59',
                'status' => $publishLocally ? 'published' : 'hidden',
            ];
            $attrs['dedupe_hash'] = sha1(mb_strtolower($attrs['company'].'|'.$attrs['title'].'|'.$attrs['location_text']));
            $attrs['content_hash'] = sha1(json_encode([$attrs['title'], $attrs['company'], $attrs['description'], $attrs['apply_url'], $attrs['expires_at'], $attrs['salary_min'], $attrs['salary_max']]));

            JobListing::updateOrCreate(
                ['job_source_id' => $source->id, 'external_id' => $job['id']],
                $attrs,
            );
        }
    }
}
